decred/decrediton

README.md

Fix README.md typos and errors.

---

README.md
app/middleware/grpc/client.js

This also updates the README to give proper dcrwallet
launching instructions.
Closes #3

Reenable ssl for grpc.

---

app/middleware/grpc/client.js

Taken from decred/dcrwallet#445
Closes #42

Fix possible exception in cert load.

---

app/main.development.js
package.json

Correct app name and menu links.

---

app/package.json
package.json

Not even released yet, so clearly not 1.0
Also use same version in both places.
Closes #27

Set version to something more reasonable.

---

app/middleware/grpc/client.js

Combine duplicate code for rpc cert loading.

---

app/main.development.js

Launch dcrd and dcrwallet on startup.

---

app/actions/WalletLoaderActions.js
app/config.js
app/index.js
app/main.development.js
app/middleware/grpc/client.js
app/middleware/grpc/seeder.js
app/package.json
package.json

Move config options to file instead of hardcoding.

---

app/main.development.js

Explicitly set rpc ports for dcrd.

---

package.json

Add eslint-formatter-pretty back.

---

.eslintrc.js
app/materialUITheme.js
app/reducers/control.js
app/reducers/grpc.js
app/reducers/index.js
app/reducers/login.js
app/reducers/notifications.js
app/reducers/seedService.js
app/reducers/walletLoader.js
webpack.config.js

Only fixing trivial (spacing and quotes mostly) in this commit.
Add no trailing whitespace rule.
Partially fixes #64

Start on cleaning up based on eslint.

---

README.md

Add some basic instructions to the README

---

app/package.json
package.json

Use the same license all over.

---

README.md

Make port in README.md match defaults in code.

---

app/actions/ControlActions.js
app/actions/WalletLoaderActions.js
app/components/GetStarted.js
app/containers/DiscoverAddressForm.js
app/containers/WalletOpenForm.js
app/index.js
app/reducers/walletLoader.js

Also add extra measures to wipe pub/privpass from memory as described by @dhill here: https://github.com/decred/decrediton/issues/84#issuecomment-267612706
Closed #84

Remove passphrases from redux state

---

app/actions/ClientActions.js
app/actions/ControlActions.js
app/actions/WalletLoaderActions.js
app/components/Home.js
app/containers/HomePage.js
app/containers/RescanForm.js
app/containers/WalletOpenForm.js
app/middleware/grpc/control.js
app/middleware/grpc/loader.js
app/reducers/control.js
app/reducers/grpc.js

Also rigged in triggering a rescan upon wallet creation.
As @jrick rightly pointed out: this should only happen when creating a wallet from an existing seed.  Newly generated seeds have no need for rescan.
Closes #94

Adds button on Home page to allow for users to start rescan

---

app/components/GetStarted.js

To give users some feedback that something is going on in the background

Add CircularProgress components

---

app/actions/ClientActions.js
app/actions/SeedServiceActions.js
app/actions/WalletLoaderActions.js
app/components/GetStarted.js
app/containers/CreateWalletForm.js
app/containers/GetStartedPage.js
app/index.js
app/middleware/grpc/client.js
app/reducers/walletLoader.js

With the new dcrwallet gRPC SeedService, it allows for consistent seed processing from the locally connected wallet.  
Now a user can create a wallet with an existing seed as well as use an existing seed to recreate a wallet in Decrediton
Closes #93 #96 and attends to the issue @jrick mentioned in #94

Add SeedService to allow for new seed generation and existing seed processing

---

app/actions/VersionActions.js
app/actions/WalletLoaderActions.js
app/components/GetStarted.js
app/containers/GetStartedPage.js
app/index.js
app/middleware/grpc/client.js
app/middleware/grpc/version.js
app/reducers/index.js
app/reducers/version.js

Add VersionService to ensure that decrediton is running on expected dcrwallet version

---

README.md
app/api.contents.js
app/main.development.js
app/middleware/grpc/client.js
app/middleware/grpc/loader.js
app/middleware/grpc/seeder.js
app/middleware/grpc/version.js

To allow the packaged app to find the api.proto write it to the app dir on startup.
This is a temporary measure only.
Closes #114

Allow packaged app to find api.proto.

---

README.md

Update README for mac.

---

app/middleware/grpc/client.js

Fix path to dcrd directory on macOS and windows.

---

package.json

Generate tarball for linux builds.

---

README.md
app/main.development.js
package.json

Include dcr* binaries when packaging.

---

app/main.development.js

Follows the behavior of other platforms.
Closes #128.

Close when all windows are closed on OSX.

---

app/components/GetStarted.js
app/containers/GetStartedPage.js
app/middleware/grpc/client.js
app/middleware/grpc/version.js

don't assume the certificate exists and print error if it doesn't

---

app/actions/VersionActions.js
app/components/Balance.js
app/components/ButtonTanel.js
app/components/Home.js
app/containers/RescanForm.js
app/index.js
app/middleware/grpc/client.js
app/middleware/grpc/version.js

First pass to tweak the dashboard.
Create a component to match the requested balance layout.  6 smallest atom decimals being a smaller font size.

More css\layout from designers

---

app/actions/ControlActions.js
app/containers/ConstructTxForm.js

Update the send form to allow for multiple outputs/recipients

---

app/actions/ClientActions.js
app/actions/ControlActions.js
app/actions/NotificationActions.js
app/actions/VersionActions.js
app/actions/WalletLoaderActions.js
app/components/GetStarted.js
app/components/Home.js
app/components/Receive.js
app/components/Send.js
app/containers/ConstructTxForm.js
app/containers/CreateWalletForm.js
app/containers/LoaderForm.js
app/containers/RescanForm.js
app/containers/WalletExistForm.js
app/main.development.js
app/middleware/grpc/loader.js

Cleanup to make lint happy

---

README.md

Improve packaging instructions.

---

app/components/GetStarted.js
webpack.config.js

display RPC errors

---

webpack.config.js

Fix a few lint issues that got in.

---

app/actions/ClientActions.js
app/components/Footer.js
app/components/GetStarted.js
app/components/Header.js
app/components/History.js
app/components/Home.js
app/components/Receive.js
app/components/Send.js
app/components/SideBar.js
app/containers/App.js
app/containers/WalletError.js
app/routes.js
webpack.config.js

First pass to get sidebar and header looking more like what the design spec wants.
Also add an error path when grpc Ping attempts return an error.
Currently it just lands the user on a page to tell them to reload, but will send them back through the
get started loop and have them reconnect all grpc services instead.

Sidebar/Header revamp, plus error page on wallet ping error

---

app/containers/CreateWalletForm.js
app/containers/DiscoverAddressForm.js
app/containers/WalletOpenForm.js

use password type on passwords

---

app/actions/VersionActions.js

implement proper semver check

---

app/actions/SettingsActions.js
app/components/Balance.js
app/components/ButtonTanel.js
app/components/History.js
app/components/Receive.js
app/components/Settings.js
app/components/SideBar.js
app/components/TxHistory.js
app/containers/SettingsPage.js
app/index.js
app/reducers/index.js
app/reducers/settings.js
app/routes.js

Currently just 1 setting for currency display.  Also still 
needs to be rigged into fs.Write to maintain settings across
instances
Closes #144

Add settings page and other styling improvements

---

app/components/SideBar.js

Add help links to sidebar,

---

app/components/HelpLink.js
app/components/SideBar.js

Fix up help links styling

---

app/actions/ControlActions.js
app/components/Send.js
app/containers/PublishTx.js
app/containers/SendPage.js
app/containers/SignTxForm.js
app/reducers/control.js

Remave ConstructTxForm to SignTxForm (what it is actually doing since
there already is a ConstructTxForm).
Add actions and button to clear a ConstructedTx.
Closes #195

Improvements in Send Page.

---

app/components/HelpLink.js
app/components/SideBar.js

Open help links in Default Browser.

---

app/components/History.js
app/components/TxDetails.js
app/containers/HistoryPage.js

Add links to insight testnet/mainnet in tx details

---

app/components/SideBar.js

Apparently you can't/shouldn't setState in componentWillMount functions
Fixes #220

Move to componentDidMount

---

app/components/Send.js

Make Send page honor units setting.

---

app/components/SideBar.js

Add testnet to sidebar

---

README.md

Update node version required.

---

README.md

Fix minor typo for running on OSX

---

app/components/SideBar.js

Fix sidebar account balances

---

app/components/GetStarted.js
app/config.js

Change to use mainnet as default

---

app/main.development.js

Fix bug in logging code.

---

README.md
app/main.development.js

While there, add -d shortcut for --debug and document both options.
Closes #248

Add --extrawalletargs option.

---

app/actions/NotificationActions.js
app/actions/WalletLoaderActions.js
app/components/SideBar.js
app/components/views/GetStarted.js
app/index.js
app/reducers/notifications.js

Remove fetch headers progress and move to post-startup.
Still need to add algos to properly create text for sidebar bottom.  timeSince and timeBack
Fixes #271

Fix startup of procedures

---

app/actions/SettingsActions.js
app/components/views/Settings.js
app/index.js

Add network to settings page.

---

app/components/Header.js
app/components/views/GetStarted.js

Add all possible errors to header in GetStarted

---

app/components/views/History.js

Update pagination buttons to be more clear

---

app/actions/ClientActions.js
app/components/views/WalletError.js
app/index.js
app/reducers/grpc.js

Update testnet network magic number. Formatting cleanup

---

app/actions/NotificationActions.js
app/components/SideBar.js
app/components/views/Home.js
app/components/views/HomePage.js
app/helpers/dateFormat.js
app/index.js
app/middleware/grpc/client.js
app/reducers/notifications.js

This PR also adds functionality to show a grey div on the home view to signify that the wallet isn't synced yet.
Fixes #232 
Fixes #274

Fix timeSince in lower sidebar

---

app/actions/ClientActions.js
app/components/SideBar.js
app/index.js
app/reducers/grpc.js

Move state updating to redux instead of component state.  With it only updating once every minute it should be acceptable to just update state.
Fixes #293

Another fix for timeSince in sideBar

---

app/actions/ControlActions.js
app/components/SideBar.js
app/components/views/Purchase.js
app/components/views/PurchasePage.js
app/index.js
app/reducers/control.js
app/routes.js

Purchase View.

---

app/main.development.js

Add --testnet and --mainnet flags

---

app/components/Header.js
app/components/HelpLink.js
app/components/SideBar.js
app/components/views/Help.js
app/routes.js

Also lower size of Header to remove excessive whitespace.  Rename Proof of Stake view to Purchase Tickets

Add seperate help page

---

app/components/Header.js
app/components/NewExistingSeedToggle.js
app/components/views/StakePool.js
app/components/views/StakePoolPage.js
app/components/views/TxDetails.js
app/index.js

- Fix other rendering issues with TxDetails.
- Increase txPerPage from 6 to 8 due to larger view space.

Add ticket price to purchase ticket page

---

app/actions/ClientActions.js
app/actions/StakePoolActions.js

Closes #303 
Check purchase information at any configured stake pool (that has matching network).

Check StakePool purchaseInformation on app load

---

app/actions/ControlActions.js
app/components/views/StakePool.js

Closes #270 
Also fix a bug with importScript sending through an incorrect byte array which led to wallets not properly watching for stakepool tickets

Add stakeinfo area at the top of Purchase Tickets page

---

app/index.js
app/middleware/api.proto
app/middleware/walletrpc/api_grpc_pb.js
app/middleware/walletrpc/api_pb.js

Update to the latest wallet grpc api

---

app/components/views/StakePool.js
app/components/views/ViewStyles.js

Proof of concept input validation for purchase ticket input form.
If this method is acceptable I'll work on moving these changes across all the others as well

Input validation for purchase tickets form

---

.gitignore

Ignore .DS_store files

---

app/main.development.js

Try harder for a clean shutdown of cmd line tools.
Shutdown without Ctrl-c in dev mode.
Closes #252

Shutdown fixes

---

app/actions/WalletLoaderActions.js
app/components/views/GetStarted.js
app/components/views/GetStartedPage.js
app/index.js
app/reducers/walletLoader.js

Switch version from alpha to beta

---

app/components/views/StakePool.js

Don't break if no StakePool is defined yet

---

app/components/TxRow.js

Check for undefined in tx rows

---

app/components/TxRow.js
app/components/views/Help.js

Transaction history address length with no box overflow and help page links

---

app/actions/WalletLoaderActions.js
app/components/views/GetStarted.js
app/components/views/GetStartedPage.js
app/components/views/ViewStyles.js
app/reducers/walletLoader.js

Also add a localhost attempt after 127.0.0.1 just in case the user's setup prefers that way.

Add a retry start rpc connection button

---

app/main.development.js

This should help prevent some lockups that are seem when not in debug mode.
Fixes #365

Handle output of dcrd/wallet better

---

README.md
app/config.js

Update dcrwallet args for --grpclisten.

---

app/actions/WalletLoaderActions.js

Only ask for discover addresses for existing seed creation

---

app/actions/ClientActions.js

Add rescan on any non-new wallet fetched headers

---

app/components/views/StakePool.js

Update spendlimit state on new getBalanceResponse

---

.dockerignore
.gitignore
Dockerfile
build-docker.sh
package.json

Automated build environment suitable for CI. 
```
$ ./build-docker.sh [branch|tag] [linux|darwin|win32] [amd64|arm]
```
All options are optional. 
`branch` defaults to `master`.  
`os` defaults to `linux`.  `win32` is untested.
`arch` defaults to `amd64`.
Related to #33

Dockerized build environment

---

.travis.yml
build-docker.sh

Use the docker script to do the build.
Closes #33

Enable travis.

---

.travis.yml
Dockerfile
README.md
build-docker.sh

Get branch correctly when building master on travis

---

Dockerfile
README.md
build-docker.sh

While there make script and README more consistant with other decred
docker scripts.
Closes #406

Move docker image to decred org.

---

app/actions/ClientActions.js
app/actions/NotificationActions.js
app/index.js
app/middleware/api.proto
app/middleware/walletrpc/api_pb.js
app/reducers/grpc.js

Add backend bits to understand coinbase addition to transaction grpc.
Closes #404

Update wallet api.

---

app/middleware/regen.sh
package.json

Add grpc-tools to devDependencies and use those bins for regen.sh

---

app/components/CreateWalletForm.js
app/components/views/GetStarted.js

Show decodeSeedError when applicable

---

app/components/views/StakePool.js
app/reducers/control.js

- Make sure to stop purchase ticket attempt if import script fails for any reason.
- Update numTicketError if incrementNumTicket is called.

Fix 2 minor bugs on the purchase ticket page

---

build-docker.sh

Make docker script use latest dcrd release

---

app/actions/ControlActions.js
app/components/views/History.js
app/components/views/Home.js
app/components/views/StakePool.js
app/components/views/StakePoolPage.js

Fixes #432 
- Add checks to disable button for purchasing tickets if spendlimit is below ticket price.  
- Add spendable account balance to account selection dropdown

Correctly update spendlimit on ticket purchasing

---

app/components/views/Send.js
app/components/views/SendPage.js
app/components/views/StakePool.js
app/components/views/ViewStyles.js

Add balance checks to send page

---

app/components/HelpLink.js
app/components/KeyBlueButton.js
app/components/MenuLink.js
app/components/SlateGrayButton.js

Make sure cursor is a pointer on buttons

---

app/components/TxRow.js

Add different styling for overview transactions

---

app/actions/ControlActions.js

Fix expiry not getting set properly

---

build-docker.sh

Update cli tools to v1.0.5

---

app/components/views/StakePool.js
app/components/views/ViewStyles.js

Add Immature tickets to stake info

---

app/components/views/Send.js
app/components/views/StakePool.js
app/components/views/StakePoolPage.js

Add currency type switching to dropdowns

---

app/actions/ClientActions.js
app/components/TxHistory.js
app/components/TxRow.js
app/components/views/TxDetails.js
app/components/views/ViewStyles.js

Also update some transaction details styling

Add transfer tx detection 

---

app/main.development.js

This is just a cleanup to make upcoming changes easier.
Closes #484

Break shutdown up into functions.

---

app/main.development.js

Consolidate code so any os-agnostic menu items are in one place rather
than duplicated.
Remove File->Open menu item on linux which didn't do anything and was
not supposed to do anything.
Closes #486

Clean up menus.

---

app/components/TxHistory.js
app/components/TxRow.js
app/components/views/History.js
app/components/views/TxDetails.js
app/components/views/ViewStyles.js

Closes #435 
- Now accurately shows the type of transaction.
- Shows the inputs consumed and the new (local) outputs created.

Update and fix styling on transaction details page

---

app/actions/WalletLoaderActions.js
app/index.js
app/reducers/walletLoader.js

Closes #402 
With this retry the daemon is given ample time to become ready for connection, if not the user can simply click the retry button.

Add a retry to start rpc request

---

app/actions/ClientActions.js
app/actions/ControlActions.js
app/actions/NotificationActions.js
app/actions/SeedServiceActions.js
app/actions/StakePoolActions.js
app/actions/VersionActions.js
app/actions/WalletLoaderActions.js
app/components/views/HistoryPage.js
app/components/views/ReceivePage.js
app/components/views/SendPage.js
app/index.js
app/reducers/control.js
app/reducers/grpc.js
app/reducers/notifications.js
app/reducers/seedService.js
app/reducers/stakepool.js
app/reducers/version.js
app/reducers/walletLoader.js

Mostly remove *Success and *Error and replace with more sensible direct dispatches.  Remove all storage of requests in state (unless when needed like in rescan).

Clean and refactor actions

---

app/components/views/StakePool.js
app/components/views/ViewStyles.js

Add expandable stakeinfo area and other minor design nits

---

app/components/CopyToClipboardButton.js
app/components/views/Receive.js
app/components/views/ViewStyles.js
package.json

Add a copy-to-clipboard button for the generated address on the Receive page

---

app/components/CreateWalletForm.js
app/components/SideBar.js

This PR fixes minor display issues seen in Windows on the Get Started page, which I referenced in my comment here: https://github.com/decred/decrediton/issues/247#issuecomment-318643435

Fix minor display issues on the Get Started page in Windows.

---

app/components/CreateWalletForm.js
app/components/SideBar.js
app/components/views/Receive.js
app/components/views/StakePool.js
app/components/views/TxDetails.js
app/components/views/ViewStyles.js
app/helpers/strings.js

Fix text selection bug by clearing floats where possible, and add a helper function to wrap text in spaces for all other cases.

Fix text selection bug in a couple other places

---

app/components/CreateWalletForm.js

Also make sure that users must match the private pass in the verify field.

Avoid seed confirmation when not using mainnet

---

app/actions/ControlActions.js
app/components/views/Accounts.js
app/components/views/AccountsPage.js

Immediately see account name changes and new accounts without extra click

---

app/actions/ControlActions.js

Fix issues with Start/Stop autobuyer

---

app/components/views/Send.js

Reset the default account selected to the default accountList value

---

app/components/ChangePassphraseModal/Modal.js
app/components/ImportScriptModal.js
app/components/PassphraseModal.js
app/style/ChangePassphraseModal.less
app/style/main.less

Also define in the main.less for later use when the rest of the components get used with less styling

Add box shadow to modals

---

app/components/AccountRow/Row.js
app/components/ChangePassphraseModal/Modal.js
app/components/PurchaseTicketsInfo.js
app/components/PurchaseTicketsInfoButton.js
app/components/SlateGrayButton.js
app/components/TicketsCogs.js
app/components/views/Settings.js
app/components/views/ViewStyles.js
app/style/AccountRow.less
app/style/ChangePassphraseModal.less
app/style/MiscComponents.less
app/style/PurchaseTicketsInfo.less
app/style/main.less

This is a continuation of #528.

Convert several more components from inline styles to CSS

---

app/components/react-select.global.css

Make select-menu-router have a higher zindex to avoid overlap

---

app/components/TextToggle/Toggle.js
app/components/TextToggle/index.js
app/components/views/GetStarted.js
app/components/views/StakePool.js

Continuation of: https://github.com/decred/decrediton/issues/528

Split/Rename NewExistingSeedToggle -> TextToggle

---

app/actions/ControlActions.js
app/components/views/StakePool.js
app/components/views/ViewStyles.js

- Extraneous bad console log
- Bad spacing for ApiKey
- Bad stakepool config setting for auto buyer

Shake out some remaining bugs found in release testing.

---

app/main.development.js

- More testing and warnings are needed before I feel like this is ready for public consumption.  Possibly too dangerous without proper guardrails.

Remove menu entry to allow to remove wallet file

---

app/actions/StakePoolActions.js
app/config.js
app/middleware/stakepoolapi.js
app/package.json

Fixes #604 
Also include an update to the electron-config package (now callled electron-store).

Make sure to pass poolHost as arg, because of issues with concurrency.

---

app/actions/ClientActions.js

Issue a stopAutoBuyer Request when ticket service is started

---

app/modules/win32ipc/binding.gyp
app/modules/win32ipc/module.cc
app/modules/win32ipc/moduleTest.js
app/modules/win32ipc/package.json
app/modules/win32ipc/pipe_wrapper.cc
app/modules/win32ipc/pipe_wrapper.h

This is planned to be used for signaling clean shutdown and listening
for dcrd lifetime events.

Add module to wrap anonymous pipe creation on Windows.

---

app/actions/ControlActions.js
app/components/views/SendPage/OutputRow.js
app/components/views/SendPage/Page.js
app/components/views/SendPage/index.js
app/style/SendPage.less

Now if a user wants to send everything from a given account then they can select Send All and then enter in the destination address.  It will then construct a transaction that will consume all utxos in the account and the user will then have to enter the private passphrase as with normal transactions.
Closes #603

Send all functionality

---

app/components/AgendaCard.js
app/components/AgendaClose.js
app/components/AutoBuyerSwitch.js
app/components/BalanceOverviewInfoModal.js
app/components/DecredLoading.js
app/components/ErrorScreen.js
app/components/HelpLink.js
app/components/ManagePoolsButton.js
app/components/MenuLink.js
app/components/NumTicketsInput.js
app/components/PurchaseTicketsInfoButton.js
app/components/ShowError.js
app/components/SlateGrayButton.js
app/components/StakeyBounce.js
app/components/TicketsCogs.js

Convert many smaller components to functional style

---

app/app.html
app/components/CreateWalletForm/ConfirmSeed/SeedEntry.js
app/components/CreateWalletForm/CreateWallet.js
app/index.js

Moved global css files from app.html to index.js

---

app/components/PurchaseTickets/index.js
app/components/StakePools/AddForm.js
app/components/StakePools/index.js
app/components/VotingPrefs/index.js
app/components/views/TicketsPage/index.js

This fixes multiple bugs introduced in the stake pool split

Multiple StakePool config fixes

---

app/actions/SettingsActions.js

Move setting config update into saveSettings

---

app/components/views/GetStartedPage/DaemonLoading/Form.js
app/components/views/GetStartedPage/DaemonLoading/index.js

Add note to tell warn users about delay to load daemon

---

app/components/SideBar/Bar.js
app/components/views/SendPage/index.js
app/components/views/SettingsPage/Page.js
app/components/views/SettingsPage/index.js
app/helpers/strings.js
app/style/AgendaCard.less
app/style/MiscComponents.less
app/style/ReactSelectGlobal.less
app/style/Settings.less
app/style/SideBar.less
app/style/StakePool.less
app/style/main.less

Fixes #666.
Partial work towards fixing #663.

Switch color of sidebar on testnet and other layout fixes

---

app/components/CreateWalletForm/ConfirmSeed/SeedEntry.js
app/components/CreateWalletForm/ContinueWalletCreation.js
app/components/CreateWalletForm/CreatePassPhrase/PassPhraseInputs.js
app/components/CreateWalletForm/CreatePassPhrase/index.js
app/components/views/GetStartedPage/DaemonLoading/index.js
app/components/views/GetStartedPage/DiscoverAddresses/Form.js
app/components/views/GetStartedPage/DiscoverAddresses/index.js
app/components/views/GetStartedPage/FetchBlockHeaders/index.js
app/components/views/GetStartedPage/OpenWallet/DecryptForm.js
app/components/views/GetStartedPage/OpenWallet/index.js

Add autofocus and enter key support to inputs on Get Started screens

---

app/components/TxHistoryRow/Status.js
app/style/AccountRow.less
app/style/TxHistory.less

Fix Accounts Page and Pending Indicator

---

app/components/Balance.js
app/components/CreateWalletForm/index.js
app/components/Header/index.js
app/components/SideBar/index.js
app/components/views/AccountsPage/Accounts/index.js
app/components/views/AccountsPage/AddAccount/index.js
app/components/views/AccountsPage/index.js
app/components/views/WalletError.js
app/connectors/accountsPage.js
app/connectors/accountsPageAccounts.js
app/connectors/accountsPageAddAccount.js
app/connectors/balance.js
app/connectors/createWallet.js
app/connectors/header.js
app/connectors/home.js
app/connectors/purchaseTickets.js
app/connectors/receive.js
app/connectors/rescan.js
app/connectors/send.js
app/connectors/service.js
app/connectors/settings.js
app/connectors/sideBar.js
app/connectors/stakeInfo.js
app/connectors/ticketAutoBuyer.js
app/connectors/ticketsPage.js
app/connectors/transactionDetails.js
app/connectors/votingPrefs.js
app/connectors/walletError.js
app/connectors/walletStartup.js
app/selectors.js

With this PR, no redux connector logic remains in components

Move remaining redux connectors out of components

---

app/actions/ControlActions.js
app/components/RescanProgress.js
app/components/SideBar/Bar.js
app/components/SideBar/index.js
app/components/views/HomePage/Page.js
app/components/views/TicketsPage/index.js
app/style/HomePage.less
app/style/MiscComponents.less

Also add explicit rescan request to import script request. This now allows us to capture rescan progress updates and give feedback to the user.
Fixes #681

Add rescan progress to sidebar

---

app/components/TxHistory.js
app/components/views/HistoryPage/Page.js
app/components/views/HomePage/Page.js
app/connectors/home.js
app/selectors.js
app/style/HistoryPage.less
app/style/HomePage.less
app/style/TxHistory.less

Show pending transactions on history page

---

app/style/MiscComponents.less
app/style/StakePool.less

Fix configured stakepool page

---

app/main.development.js

Add --version and --help CLI arguments

---

app/components/views/Help.js

Fix "Stakepools Overview" link

---

app/components/views/GetStartedPage/DaemonLoading/Form.js
app/style/GetStarted.less

Add padding to block download progress on get started page

---

app/components/StakeInfo/Display.js
app/connectors/stakeInfo.js
app/selectors.js

Add total subsidy on ticket page

---

app/components/KeyBlueButton.js
app/components/PurchaseTickets/Form.js
app/components/views/HomePage/Page.js
app/connectors/purchaseTickets.js

Disable rescan button

---

README.md

The documentation is not up to date according to https://github.com/decred/dcrwallet#installation-and-updating

Change `glide i` to `dep ensure` in the README.md

---

app/actions/DaemonActions.js
app/wallet/daemon.js

Splits RPC communication to wallet/

Refactor daemon actions

---

app/components/AccountsSelect.js
app/components/PurchaseTickets/Form.js
app/components/views/HistoryPage/Page.js
app/components/views/ReceivePage/Page.js
app/components/views/SendPage/Page.js
app/connectors/accountsSelect.js
app/connectors/send.js
app/selectors.js
app/style/CreateWalletForm.less
app/style/HistoryPage.less
app/style/ReactSelectGlobal.less
app/style/SendPage.less
app/style/StakePool.less
app/style/main.less

Part of #663.
This consolidates the style of all select components throughout the app and adds a component for all instances where an account needs to be selected.

Consolidate select styles

---

app/actions/SettingsActions.js
app/actions/VersionActions.js
app/wallet/version.js

Splits RPC communication to wallet/

 Refactor SettingsActions/VersionActions

---

app/actions/ClientActions.js
app/middleware/grpc/client.js
app/reducers/grpc.js
app/selectors.js

According to https://github.com/decred/dcrwallet/blob/master/rpc/documentation/api.md#verifymessage and for the issue #331, I need to add the `MessageVerificationService` in decrediton

Add MessageVerificationService

---

app/components/views/AccountsPage/Accounts/AccountRow/Row.js

React tool tip

---

app/components/StakePools/List.js
app/connectors/stakePools.js

Add rescanRequest check to Add Stakepool Button

---

app/actions/ControlActions.js
app/components/PurchaseTickets/Form.js
app/components/views/HomePage/Page.js
app/components/views/HomePage/index.js
app/connectors/home.js
app/connectors/purchaseTickets.js
app/selectors.js
app/style/HomePage.less
package.json

PR for solving issue https://github.com/decred/decrediton/issues/719

Revoke ticket notification

---

README.md

these were the updated instructions I got in the decred slack

update development instructions in README

---

app/config.js
app/main.development.js

writeCfgs only if there are no configs located in the decrediton appdata dir

---

app/actions/WalletLoaderActions.js
app/wallet/config.js
app/wallet/loader.js

Splits off rpc communication to code in wallet

Refactor wallet loader actions

---

app/components/views/TransactionsPage/SendTab/Page.js

Fix icon and tooltip as pointed out by @alexlyp

Fix icon and tooltip

---

README.md
app/actions/DaemonActions.js
app/actions/WalletLoaderActions.js
app/components/views/GetStartedPage/DaemonLoading/index.js
app/components/views/GetStartedPage/index.js
app/connectors/walletStartup.js
app/main.development.js
app/reducers/walletLoader.js

Run executables from /bin instead of /app/bin on development

---

app/actions/VersionActions.js
app/components/views/GetStartedPage/index.js
app/components/views/InvalidRPCVersion.js
app/connectors/invalidRPCVersion.js
app/connectors/walletStartup.js
app/main.development.js
app/routes.js
app/selectors.js
app/style/Layout.less
app/version/version.html
app/version/version.js

Add rpc version mismatch alert

---

app/components/PurchaseTickets/Form.js
app/i18n/po/decrediton.pt.po
app/i18n/pot/decrediton.pot

Purchase tickets

---

app/components/CreateWalletForm/ConfirmSeed/SeedEntry.js

Select seed word when typing space key

---

app/actions/DaemonActions.js
app/components/views/GetStartedPage/DaemonLoading/Form.js
app/components/views/GetStartedPage/index.js
app/connectors/walletStartup.js

removes skip sync button

---

app/components/PurchaseTickets/Form.js
app/components/PurchaseTicketsInfoButton.js
app/components/shared/Tooltip.js
app/components/views/AccountsPage/Accounts/List.js
app/components/views/TransactionsPage/SendTab/Page.js

- Send functionality toggles
- PurchaseInfoButtons

Add new tooltip impl to more places

---

app/style/ReactSelectGlobal.less
app/style/TxHistory.less

Add styling to handle long account names

---

app/actions/DaemonActions.js
app/actions/WalletLoaderActions.js
app/components/views/GetStartedPage/AdvancedStartup/Error.js
app/components/views/GetStartedPage/AdvancedStartup/RemoteDaemonForm.js
app/components/views/GetStartedPage/AdvancedStartup/index.js
app/components/views/GetStartedPage/index.js
app/config.js
app/connectors/walletStartup.js
app/index.js
app/main.development.js
app/reducers/daemon.js
app/selectors.js

fixes on #862 
case 1 working. 
I created a must_open_form which I set for true when daemon is synced.

Advanced daemon reload

---

app/components/PurchaseTickets/Form.js
app/style/TxDetails.less

- Remove LinkToAccounts in favor of the AccountSelect prop.
- Add account name shortener to transaction details page.

Various clean up issues

---

app/actions/ClientActions.js
app/actions/DaemonActions.js
app/actions/DecodeMessageActions.js
app/actions/NotificationActions.js
app/actions/SignMessageActions.js
app/actions/StakePoolActions.js
app/actions/VerifyMessageActions.js
app/actions/VersionActions.js
app/actions/WalletLoaderActions.js
app/wallet/index.js
app/wallet/message.js
app/wallet/notifications.js
app/wallet/service.js

Continuation of #528
Splits off rpc communication to code in wallet

Refactor notification and sign/verify message actions

---

app/components/Form/InputField.js
app/components/TicketAutoBuyerInfo.js
app/components/views/AccountsPage/Accounts/List.js
app/components/views/TxDetails.js
app/messages.js
app/style/ImportScriptModal.less
app/style/Layout.less
app/style/PassphraseModal.less
app/style/PurchaseTicketsInfo.less
app/style/SideBar.less
app/style/StakePool.less

- Fix overflow-x scroll in sidebar
- Help description text
- Add check to show/hide transaction fee depending on if transaction is a vote or receiving funds
- Use Input in InputField to make Sign/Verify form have consistent styling.
- Fix Account Info Modal
- Slight tweak to clean up modal overlays for info and passphrases

Various cleanup issues for release

---

app/actions/ClientActions.js
app/selectors.js
app/wallet/app.js
app/wallet/client.js
app/wallet/index.js
app/wallet/service.js

Continuation of #528
Splits off rpc communication to code in wallet

ClientActions refactor

---

app/components/ImportScriptModal/Modal.js
app/components/PassphraseModal/Modal.js
app/components/views/SettingsPage/Page.js
app/style/ChangePassphraseModal.less

- ChangePassphraseModal now being shown with minimal visual disruption.
- Change from Save to Confirm on other passphrase modal buttons.

More modal cleanup

---

app/components/Balance.js
app/components/views/AccountsPage/Accounts/List.js
app/components/views/TransactionsPage/SendTab/OutputAccountRow.js

Currency display label and account page scrolling

---

app/actions/DecodeMessageActions.js
app/components/views/TransactionPage/Page.js
app/components/views/TransactionPage/index.js
app/components/views/TxDetails.js
app/connectors/transactionPage.js
app/reducers/snackbar.js
app/selectors.js

Fix #870 
Transaction decoding is requested on demand, only when the transaction details are viewed.

Show full tx details in transaction details page

---

app/components/SideBar/Bar.js
app/components/SideBar/MenuLinks/MenuLink.js
app/components/SideBar/MenuLinks/index.js
app/components/shared/RouteTransition.js
app/messages.js

Fix sidebar animation

---

app/components/AgendaClose.js
app/components/AgendaOverview/Overview.js
app/components/ManagePoolsButton.js
app/components/PurchaseTickets/Form.js

-ManagePoolsButton
-AgendaClose
There are others that may be added here.

Clean up components that don't offer extra usage

---

app/actions/ControlActions.js
app/components/TransitionMotionWrapper.js
app/components/inputs/ReceiveAccountsSelect.js
app/components/views/TransactionsPage/SendTab/OutputAccountRow.js
app/components/views/TransactionsPage/SendTab/OutputRow.js
app/components/views/TransactionsPage/SendTab/Page.js
app/components/views/TransactionsPage/SendTab/index.js

hide/show divs more gracefully 

---

app/components/views/TxDetails.js

Also for transfers show receiving account instead of address.
Close #935

For sent transactions, show "change" instead of address

---

app/components/StakeyBounce.js
app/components/indicators/LoadingMoreTransactions.js
app/components/indicators/NoMoreTransactions.js
app/components/indicators/StakeyBounce.js
app/components/indicators/StakeyBounceExtraSmall.js
app/components/indicators/index.js
app/components/views/TicketsPage/PurchaseTab/Page.js
app/components/views/TransactionsPage/HistoryTab/Page.js
app/style/Loading.less
app/style/Stakey.less
package.json
yarn.lock

This implements infinite scrolling of the transaction list page using the https://github.com/CassetteRocks/react-infinite-scroller component.
I've used a small stakey bouncing as indicator during transaction loading. That indicator (or a more generic version) may be used as basis for #920.
Fix #930.

Add infinite scroll on transaction list

---

app/components/views/AccountsPage/Accounts/List.js
app/style/AccountsPage.less

Remove extra padding on accounts page

---

app/style/Settings.less

Fix settings page styling

---

app/components/views/TransactionsPage/SendTab/OutputRow.js
app/style/SendPage.less

Also checks to only display "To:" on the first output row to match "Amount:"
Fixes #949

Fix send page styling

---

app/components/views/TxDetails.js
app/style/TxDetails.less

Show full raw transaction hex on transaction details page

---

app/style/Header.less

Fix margins for header tabs

---

app/components/PurchaseTickets/Form.js
app/style/Input.less
app/style/ReactSelectGlobal.less
app/style/SendPage.less
app/style/StakePool.less

Fix #960 
Had to tweak the styling of other pages as the changes in the select affect them as well.

Fix height of selects and inputs

---

app/components/KeyBlueButton.js
app/components/PassphraseModalButton.js
app/components/indicators/SimpleLoading.js
app/components/indicators/index.js
app/components/views/TransactionsPage/SendTab/Page.js
app/style/SimpleLoading.less

PoC for closing #920 
Now KeyBlueButton takes a loading prop to show the indicator while a request is in flight.  Currently I've added it to just the Send button.  If we like the look/feel I can add it to other places we feel are more appropriate than the DecredLoading indicator covering the whole screen.

Add a simple loading indicator to Send Button

---

app/components/modals/BalanceOverviewModalContent.js
app/components/modals/PassphraseInfoModalContent.js
app/components/modals/PurchaseTicketsInfoModalContent.js
app/components/modals/SeedInfoModalContent.js
app/components/modals/SignMessageInfoModalContent.js
app/components/modals/TicketAutoBuyerInfoModalContent.js
app/components/modals/VerifyMessageInfoModalContent.js
app/style/Modals.less
app/style/StakePool.less

Apply consistent styling to information modals

---

app/components/PurchaseTickets/Form.js
app/components/inputs/PercentInput.js
app/components/inputs/index.js

Pool fee was previously listed as DCR/KB which is incorrect.

Add new input type for percentages

---

app/actions/ControlActions.js
app/components/SideBar/Bar.js
app/components/buttons/RescanCancelButton.js
app/components/buttons/index.js
app/components/indicators/RescanProgress.js
app/connectors/rescan.js
app/index.js
app/reducers/control.js
app/style/MiscComponents.less

Rescan cancel and final styling updates

---

.eslintrc.js

These has many es6 codes like Set/Map,but does'nt have eslint env for es6.

add eslint env for es6

---

app/components/views/AccountsPage/Accounts/AccountRow/AccountDetails.js

Switch account keys to a single translated message

---

app/selectors.js

Sort voted/revoked tickets correctly

---

app/components/inputs/Input.js
app/components/modals/AddAccountModalContent/Modal.js
app/components/modals/ChangePassphraseModalContent/Modal.js
app/components/modals/ImportScriptModalContent/Modal.js
app/components/modals/PassphraseModalContent/Modal.js
app/components/views/AccountsPage/Accounts/AccountRow/RenameAccount.js
app/components/views/TransactionsPage/SendTab/OutputRow.js

This required changing Input from a stateless functional component to be able to use the DOM `ref` and `componentDidMount()`.
Close #823

Autofocus top field in passphrase modals

---

app/components/views/TxDetails.js

Add Unconfirmed subtitle

---

app/actions/ControlActions.js

Make sure to dispatch ImportScript_Failed whenever an error is received

---

app/components/inputs/Input.js

Fixes bug of closing app when hitting enter on GetStarted pages.

Add onKeyDown to inputs

---

app/actions/ControlActions.js
app/components/views/TicketsPage/PurchaseTab/index.js
app/reducers/snackbar.js

Fix #965 
Also fix an undocomented bug that prevented purchasing a ticket immediately after importing the stakepool api.

Double stakepool script

---

app/config.js

I'm confused about `require("electron-store")` twice here,It's not necessary.By the way the code include Node require style and ES6 import style,It looks like not clean.

sort out the `import` declare

---

app/selectors.js

Fix transactions not on tx filter not being shown bug

---

app/actions/SettingsActions.js
app/components/views/GetStartedPage/Settings/Form.js
app/components/views/SettingsPage/GeneralSettings.js
app/index.js
app/style/GetStarted.less
app/style/Settings.less

This adds the ability to change the `daemon_start_advanced` setting from the settings page.

Add start daemon advanced setting to page

---

app/components/inputs/Input.js
app/components/modals/AddAccountModalContent/Modal.js
app/components/modals/ChangePassphraseModalContent/Modal.js
app/components/modals/ImportScriptModalContent/Modal.js
app/components/modals/PassphraseModalContent/Modal.js
app/reducers/snackbar.js

Fix #701 
Also fix a small bug of the snackbar notification not being shown on password change.

Submit passphrase modals on enter keyDown

---

app/components/views/TransactionsPage/SendTab/Page.js

Fix send amount validation on send to self

---

app/components/buttons/TextToggle/Toggle.js
app/components/buttons/TextToggle/index.js
app/components/views/GetStartedPage/OpenWallet/CreateWalletForm/ConfirmSeed/Form.js
app/components/views/GetStartedPage/OpenWallet/CreateWalletForm/ConfirmSeed/SeedEntry.js
app/components/views/GetStartedPage/OpenWallet/CreateWalletForm/ConfirmSeed/index.js
app/components/views/GetStartedPage/OpenWallet/CreateWalletForm/ContinueWalletCreation.js
app/components/views/GetStartedPage/OpenWallet/CreateWalletForm/index.js
app/reducers/walletLoader.js
app/style/CreateWalletForm.less
app/style/TextToggle.less
app/wallet/seed.js

Adding hex seed import 

---

app/app.html
app/main.development.js
app/staticPages/secondInstance.html

Fix #1071 
It will show the wrong version on development due to electron mungling up `app.getVersion`, but works on the packaged version.

Add version to title menu

---

app/main.development.js

Properly load context-menu to allow copy/pasting

---

app/components/views/SettingsPage/GeneralSettings.js
app/components/views/SettingsPage/Page.js
app/style/Settings.less

A small fix, but something to get my feet wet with.  Found while browsing the code.

replaced 'colunm' with 'column'

---

app/logging.js
app/wallet/app.js
app/wallet/client.js
app/wallet/loader.js
app/wallet/message.js

[poc] Logging with higher order function

---

app/style/CreateWalletForm.less

Before the change:
After the change:

Add margin to for better vertical alignment

---

app/style/MyTickets.less

See https://github.com/decred/decrediton/issues/1038 and if interested also old PR https://github.com/decred/decrediton/pull/444/files

Incorrect Mouse Cursor Type on Buttons in Ticket View on MacOS

---

app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/index.js

Fix issue when account is undefined

---

app/helpers/addresses.js
app/package.json
app/yarn.lock
test/unit/helpers/addresses.spec.js

Add client-side base58 address validation

---

app/components/views/AccountsPage/Accounts/AccountRow/Row.js
app/style/AccountRow.less
app/style/ReactSelectGlobal.less

Fixing layout

---

app/reducers/walletLoader.js

Meant to add this to the previous PR for new wallet/daemon loading order.

Add forgotten state update

---

app/components/buttons/InvisibleButton.js
app/components/buttons/index.js
app/components/modals/ConfirmModal/index.js
app/components/modals/SeedCopyConfirmModal/Modal.js
app/components/views/GetStartedPage/TutorialPage/Page.js
app/components/views/GetStartedPage/WalletSelection/SelectAvailableWalletsForm.js
app/style/MiscComponents.less
app/style/Modals.less
app/style/Tutorial.less
app/style/main.less

Also add a new "Invisible Button" type that will be used in place of the SlateGrayButton in most places

[launcher] Update confirm modals to match design doc

---

app/actions/ClientActions.js
app/actions/StatisticsActions.js
app/components/inputs/InlineField.js
app/components/inputs/PathBrowseInput.js
app/components/inputs/PathInput.js
app/components/inputs/index.js
app/components/views/TransactionsPage/ExportTab/Page.js
app/components/views/TransactionsPage/ExportTab/index.js
app/components/views/TransactionsPage/ExportTab/messages.js
app/connectors/exportPage.js
app/helpers/byteActions.js
app/helpers/dateFormat.js
app/helpers/index.js
app/index.js
app/messages.js
app/reducers/control.js
app/reducers/snackbar.js
app/routes.js
app/selectors.js
app/style/ExportPage.less
app/style/MiscComponents.less
app/wallet/service.js

Fix #912 
POC for the moment. No fancy ui yet, only the export function on the "transactions" tab. Will create a local "test.csv" file.

Export Transactions as CSV

---

app/actions/ClientActions.js

fixing sidebar not showing if does not skip tutorial

---

app/selectors.js

Adding homeHistoryTickets to viewableTransactions

---

app/main.development.js

First attempt at allowing multiple simultaneously running decrediton instances.
To test, run `yarn build`, then `yarn start` twice (`yarn dev` fails due to hot-reloading trying to always bind to port 3000, so you can't run two instances using that command).
Running with advanced_daemon = true works as intended. Running with advanced_daemon = false works (the second instance uses the already running dcrd node) **but** if you close the first instance it will shutdown dcrd.
Also you need to start both instances of the app before selecting a wallet to open, otherwise there are config issues.
Sending early for discussion if we will allow this, if we should only allow on development (for the moment) or only if advanced_daemon = true, if we'll address the issues I pointed out or not.

Allow multiple concurrent instances

---

app/actions/StatisticsActions.js
app/components/charts/BalanceChart.js
app/components/charts/Styles.js
app/components/charts/TicketChart.js
app/components/charts/TransactionChart.js

- 0 value bars were rendering fully instead of empty bars
- Tweaks to stacked bar radiuses
- Change sent to be debits and so it shows the stacked +/- chart correctly

Chart styling clean up

---

app/main.development.js
app/wallet/daemon.js

fix closing decrediton error

---

app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ContinueWalletCreation.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/CreateWallet.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/index.js
app/components/views/GetStartedPage/OpenWallet/DecryptForm.js
app/components/views/GetStartedPage/OpenWallet/index.js
app/connectors/createWallet.js
app/connectors/walletStartup.js
app/reducers/walletLoader.js
app/selectors.js

[launcher] Add loading indicators to Open/Create Wallet buttons

---

app/components/buttons/DangerButton.js
app/components/buttons/KeyBlueButton.js
app/style/GetStarted.less

Added spacing between multiple buttons - closes #1215

Button spacing fix on Get started screen

---

app/selectors.js

Fix occasional `ticket is undefined` errors in selector.
The problem was the reference to the `allTickets` list by index when there was no relationship between `recentStakeActivity` and `allTickets`. `allTickets` stores ticket+spender and `recentStakeActivity` is a list of transactions, so to find the full ticket information based on an arbitrary stake transaction (which could be the ticket purchase itself, a vote or a revoke) we need to search by hash to find if we have the information.
Ordinarily, we should have that information (as it is returned by `dcrwallet.GetTickets()`) but on a few wallets I've hit a situation where the recent transactions list has a transaction *not* returned by `GetTickets` (still looking into it, but it's related to my ticket splitting tests - dcrwallet …

Fix indexing bug on selector

---

app/main.development.js

We won't have time before 1.2.0 to implement all requirements for simultaneous multiple wallets on non-advanced mode, so I'm returning the code to alert and prevent running multiple instances on that situation.

Prevent second app instance on non-advanced mode

---

app/style/GetStarted.less
app/style/Help.less

Fix mouse hover on macOS. Similar as #1153, #1038 and #436.

Added cursor pointers

---

app/main.development.js
app/wallet/daemon.js

Change getBlockCount() to async

---

app/components/views/HelpPage/LogsTab/Page.js
app/components/views/HelpPage/LogsTab/index.js
app/connectors/logging.js
app/index.js
app/reducers/daemon.js
app/selectors.js

Fixes #1238 
Also adds proper rows for daemon logs textarea.

Properly show logs for daemon

---

app/components/views/GetStartedPage/WalletSelection/Form.js
app/main.development.js
app/selectors.js
app/style/GetStarted.less

Close #1229 
Now user is shown incomplete wallet set ups and which will allow them to continue set up or remove on future decrediton loads.

Identify incomplete wallets

---

app/style/AgendaCard.less
app/style/MyTickets.less

Remove shadows

---

app/style/Chart.less
app/style/TextToggle.less
app/style/Tooltip.less
app/style/TxHistory.less
app/style/main.less

Update background-container color

---

app/components/buttons/CloseButton.js
app/components/buttons/index.js
app/components/modals/InfoConfirmModal/index.js
app/components/modals/index.js
app/components/views/TicketsPage/PurchaseTab/StakePools/AddForm.js
app/style/MiscComponents.less
app/style/Modals.less
app/style/StakePool.less

[stakepool] New add stakepool design

---

app/components/views/TransactionsPage/SendTab/Page.js
app/style/Modals.less

Add addresses to confirmation modal.  Requested from `adreny` on slack.

Improve send confirmation modal

---

app/components/views/SecurityPage/ValidateAddress/index.js

Clean store when Validate Address component mounting

---

app/components/views/SecurityPage/SignMessage/Form.js
app/components/views/SecurityPage/VerifyMessage/Form.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/index.js
app/components/views/TicketsPage/PurchaseTab/TicketAutoBuyer/Details.js
app/components/views/TicketsPage/PurchaseTab/TicketAutoBuyer/index.js
app/style/Help.less
app/style/HomePage.less
app/style/Layout.less
app/style/Modals.less
app/style/SecurityCenterMessagePage.less
app/style/Settings.less
app/style/StakePool.less
app/style/main.less

- Fix security page passphrase spacing
- Help page icons flex spacing for expanded view
- Make security center forms more consistent with other pages
- Clean up advanced ticket purchase expanding
- Clean up auto-buyer expanding
- Use consistent scrollbar styling throughout

Various styling clean up

---

app/actions/ControlActions.js

Avoid erroring on rescan cancel

---

app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ExistingSeed/index.js

Add additional sanity checking for restore wallet from seed 

---

app/components/views/TransactionsPage/HistoryTab/Page.js
app/components/views/TransactionsPage/HistoryTab/index.js
app/style/HistoryPage.less

Move no transactions indicator below filters

---

app/actions/DaemonActions.js
app/actions/SettingsActions.js
app/components/modals/GapLimitInfoModalContent.js
app/components/modals/index.js
app/components/views/SettingsPage/GeneralSettings.js
app/config.js
app/main.development.js
app/reducers/settings.js

Close #1306 
Note: Still need to add a warning message/modal for this change.  Debating about where to add that.
This allows the user to change the dcrwallet option for addridxscanlen.  Default of 20 will be used

[config] Allow users to change their gap limit

---

app/wallet/daemon.js

This was causing erroneous logs which caused some unneeded clutter.

[logging] Remove logging from clean shutdown request

---

app/components/views/TicketsPage/PurchaseTab/StakePools/AddForm.js

The url wasn't being shown on the message.

Show stakepool link

---

app/components/views/TicketsPage/StatisticsTab/charts/VoteTime.js
app/connectors/myTicketsCharts.js
app/selectors.js

This adds the average vote time calculation and label into the voting time statistics.

Add average vote time calculation

---

app/actions/ClientActions.js
app/main.development.js

Fix #1334 
Problem was that the update call triggered on maturing heights was not passing the correct object after refactorings and bug fixes of the account balance procedure.

Fix blank balance after ticket/vote matures

---

app/main.development.js

Increase height of About window

---

app/actions/DaemonActions.js
app/actions/WalletLoaderActions.js
app/components/views/GetStartedPage/index.js

Fix possible race on wallet open and daemon synced

---

app/components/views/GetStartedPage/LanguageSelectPage/index.js

Correctly initialize english language

---

app/main.development.js
app/main_dev/launch.js
app/main_dev/logging.js
app/main_dev/paths.js

This PR refactors dcrd and dcrwallet launch and shutdown and fixes #1365.
~~I am having trouble showing dcrwallet and dcrd logs right now and I need to find a solution for that.~~
~~As our log variables are at main.development and launch is an async method I can not buffer them, even when passing by reference with objects, and they stay empty buffers.~~
Thanks for your help @matheusd , I made as you said and logs are working now.

Refactor main.development.js launch and shutdown

---

README.md

add Correct name of Ubuntu and version kernel like-debian

Update ubuk README.md

---

app/components/charts/BalanceChart.js
app/components/charts/StakeROIChart.js
app/components/charts/Styles.js
app/components/charts/TicketChart.js
app/components/charts/TransactionChart.js
app/components/charts/VoteTimeChart.js
app/components/views/HomePage/tables/RecentTransactions.js
app/components/views/HomePage/tables/TicketActivity.js
app/components/views/HomePage/tabs/Balance.js
app/components/views/HomePage/tabs/Tickets.js
app/components/views/HomePage/tabs/Transactions.js
app/style/Chart.less
app/style/HomePage.less
app/style/MiscComponents.less

Closes #1363 
There are some lingering issues in #1362 that will require extra work.  Due to the usage of recharts the stacked charts aren't able to nicely have rounded tops and bottoms that lay on top of eachother.

[overview] Various styling issues on overview

---

app/config.js
app/main.development.js
app/main_dev/ipc.js
app/main_dev/logging.js
app/main_dev/templates.js

This PR refactors electron templates on main.development.
I believe it closes #1137, what do you guys think? Any other improvements we can have about it?

Refactor main.development electron templates

---

app/containers/App.js

Prevent shutdown on empty link

---

app/app.html
app/containers/App.js
app/index.js
app/main.development.js
app/main_dev/externalRequests.js

Attempt at identifying #1387 
This adds a few log lines into the main react app startup procedure to try and zero in on where the process breaks.
I'm also fixing a wrong url for the block height api on mainnet.

Add logs to main app startup

---

app/components/views/HomePage/tables/NoTransactionsLinks.js

Relink "buy from exchanges" destination

---

app/actions/DaemonActions.js
app/components/buttons/index.js
app/components/views/FatalErrorPage.js
app/connectors/fatalErrorPage.js
app/main.development.js
app/main_dev/ipc.js
app/style/Layout.less
app/wallet/daemon.js

[daemon] Add corrupted error and give user option to delete blockchain data to fix

---

app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ExistingSeed/Form.js
app/style/CreateWalletForm.less

Fix errored seed words from shifting due to style overwrite

---

app/actions/StatisticsActions.js
app/selectors.js

Fix #1386 
This accounts for the vote maturity period when generating statistics. It also changes the overview chart to show immature balance as locked, since the immature balance has been moved from the Balance to the Tickets chart.

Immature vote balances

---

app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ExistingSeed/Form.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/SingleSeedWordEntry.js
app/style/CreateWalletForm.less

closes #1407 and closes #1342.
I think would be nice having a tooltip or some kind of notification warning about the possibility of pasting with the middle click. What do you guys think?

Add paste with middle click on seed restore

---

app/components/views/FatalErrorPage.js

fix resource unavailable error message

---

app/components/layout/TitleHeader.js
app/components/views/HelpPage/LinksTab/index.js
app/components/views/HelpPage/LogsTab/Page.js
app/components/views/HelpPage/TutorialsTab/index.js
app/components/views/TicketsPage/MyTicketsTab/TicketListPage.js
app/components/views/TicketsPage/MyTicketsTab/TicketsCardList.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/Form.js
app/components/views/TicketsPage/PurchaseTab/Tickets.js
app/components/views/TicketsPage/StatisticsTab/Page.js
app/components/views/TransactionsPage/ExportTab/Page.js
app/components/views/TransactionsPage/HistoryTab/Page.js
app/components/views/TransactionsPage/ReceiveTab/Page.js
app/components/views/TransactionsPage/SendTab/Page.js
app/style/Help.less
app/style/HistoryPage.less
app/style/Layout.less
app/style/MiscComponents.less
app/style/MyTickets.less
app/style/Paginator.less
app/style/StakePool.less
app/style/TxHistory.less

Close #1395 
- Adds subtitles to tabbed pages as requested.
- Update various styling on my tickets and help page.

Add subtitles and fix various styling issues

---

app/style/AccountRow.less
app/style/AgendaCard.less
app/style/AgendaOverview.less
app/style/CreateWalletForm.less
app/style/GetStarted.less
app/style/Header.less
app/style/Help.less
app/style/HomePage.less
app/style/Layout.less
app/style/MiscComponents.less
app/style/NumTicketsInput.less
app/style/ReceivePage.less
app/style/SecurityCenterMessagePage.less
app/style/SendPage.less
app/style/SideBar.less
app/style/StakePool.less
app/style/Tutorial.less
app/style/TxHistory.less
app/style/main.less

[styling] Use consistent dark blues

---

app/components/views/AccountsPage/Accounts/AccountRow/RenameAccount.js
app/components/views/AccountsPage/Accounts/AccountRow/index.js
app/style/AccountRow.less
app/style/AccountsPage.less

Close #1431 
Also tweak some styling to accommodate new form error.

[accounts] Fix rename account form

---

app/components/modals/ConfirmModal/index.js
app/components/modals/ConstitutionModalContent.js
app/components/modals/InfoConfirmModal/index.js
app/components/modals/InfoModal/Modal.js
app/components/modals/Modal.js
app/components/modals/PassphraseModal/Modal.js
app/components/views/AccountsPage/Accounts/List.js
app/components/views/HelpPage/LinksTab/index.js
app/components/views/SettingsPage/GeneralSettings.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/Form.js
app/components/views/TicketsPage/PurchaseTab/TicketAutoBuyer/Form.js
app/connectors/modal.js
app/containers/GetStarted.js
app/containers/Wallet.js
app/i18n/docs/en/InfoModals/BalanceOverview.md
app/i18n/docs/en/InfoModals/GapLimit.md
app/i18n/docs/en/InfoModals/Passphrase.md
app/i18n/docs/en/InfoModals/PurchaseTickets.md
app/i18n/docs/en/InfoModals/Seed.md
app/i18n/docs/en/InfoModals/SignMessage.md
app/i18n/docs/en/InfoModals/TicketAutoBuyer.md
app/i18n/docs/en/InfoModals/VerifyMessage.md
app/style/Layout.less
app/style/Modals.less

Close #1422 
Currently seeing an oddity with modals not closing immediately on page change. When animations are turned off it happens immediately.

[modals] Final styling of info modals

---

app/components/views/GetStartedPage/Settings/Form.js
app/components/views/SettingsPage/Page.js
app/components/views/SettingsPage/PrivacySettings.js
app/style/GetStarted.less
app/style/Icons.less
app/style/Settings.less
app/style/icons/checkmarkBlue.svg
app/style/icons/checkmarkGrey.svg

Close #1417 
Also, fixed any lingering issues with the getstarted settings view as well.

[settings] Update setting styling

---

app/main_dev/launch.js

[Launch] Add --nolisten flag on dcrd launch

---

app/components/Paginator/ActionButton.js
app/components/Paginator/PageButton.js
app/style/Paginator.less

Part of #1406 
This replaces the material ui buttons being used with InvisibleButtons.

Drop material ui buttons

---

app/components/views/GetStartedPage/DaemonLoading/Form.js
app/components/views/GetStartedPage/Logs/Form.js
app/components/views/GetStartedPage/index.js
app/connectors/walletStartup.js

[logs] Show logs after non-remote daemon has been started

---

app/components/views/GetStartedPage/CreateWallet/CreateForm.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ContinueWalletCreation.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/CreateWallet.js
app/components/views/GetStartedPage/WalletSelection/CreateWalletForm.js
app/components/views/GetStartedPage/WalletSelection/Form.js
app/components/views/GetStartedPage/WalletSelection/index.js
app/style/Tutorial.less

- Create new wallet was going to intermediate page again.
- Change create wallet form depending on restore of create new.
- Tutorial buttons were padded incorrectly.

[launcher] Fix various launcher issues

---

app/style/Modals.less

Close #1451 
This also fixes some other modals that were being used on the get started screen.

[launcher] Fix confirm seed copy modal layout

---

.dockerignore
README.md

Remove .dockerignore and Docker section of README.md.

---

app/i18n/locales/index.js
app/style/Icons.less
app/style/LanguageSelect.less
app/style/icons/gb-flag.svg

Add English(UK) to language selection.

---

app/components/buttons/index.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ConfirmSeed/Form.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/CreatePassPhrase/PassPhraseInputs.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/CreatePassPhrase/index.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/CreateWallet.js
app/components/views/GetStartedPage/Logs/Form.js
app/components/views/GetStartedPage/ReleaseNotes/Form.js
app/components/views/GetStartedPage/Settings/Form.js
app/components/views/GetStartedPage/index.js
app/components/views/SettingsPage/GeneralSettings.js
app/style/CreateWalletForm.less
app/style/GetStarted.less
app/style/MiscComponents.less

[launcher] Seed entry visual fixes

---

app/components/views/TransactionsPage/ExportTab/Page.js
app/components/views/TransactionsPage/ExportTab/index.js
app/style/ExportPage.less

[export] Export information form styling

---

app/style/SideBar.less

[sidebar] Add box-shadow to sidebar

---

app/components/views/TransactionsPage/ReceiveTab/Page.js
app/style/ReceivePage.less

[receive] Receive page styling final tweaks

---

app/components/buttons/EyeFilterMenu/index.js
app/components/inputs/AccountsSelect.js
app/components/shared/Balance.js
app/style/EyeFilterMenu.less
app/style/Icons.less
app/style/Input.less
app/style/ReactSelectGlobal.less
app/style/icons/checkMarkContextMenu.svg

Closes #1504  (except for Input B issue which is getting it's own issue)

[inputs] Various input design issues

---

app/components/views/HomePage/tables/RecentTransactions.js

[overview] Fix recent transactions on overview when no tickets

---

app/components/views/GetStartedPage/WalletSelection/CreateWalletForm.js
app/components/views/GetStartedPage/WalletSelection/index.js

[launcher] Show error on duplicate wallet name attempts

---

app/components/views/TransactionsPage/SendTab/OutputRow.js
app/components/views/TransactionsPage/SendTab/Page.js
app/components/views/TransactionsPage/SendTab/index.js
app/style/ReactSelectGlobal.less
app/style/SendPage.less

Closes #1505 
There are some lingering input issues that will be addressed in another PR that will handle all of #1504

[send] Styling updates to Send page

---

app/components/inputs/NumTicketsInput.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/Form.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseTicketsAdvanced.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/index.js
app/style/MiscComponents.less
app/style/NumTicketsInput.less
app/style/StakePool.less

Various fixes included in this PR:
- Properly show field errors for ticket/tx fee and expiry
- Show Not enough funds error for num tickets
- Use onKeyPress handler for NumTicketsInput for up and down key
- parseInt for NumTicketsInput changes
- Remove transaparent border for key blue button, since it was causing position change on error
- Disable purchase button when there are errors/issues.

[tickets] Field/form fixes on Purchase Tickets

---

app/components/inputs/PathBrowseInput.js
app/components/inputs/PathInput.js
app/components/views/GetStartedPage/AdvancedStartup/AppDataForm.js
app/components/views/GetStartedPage/AdvancedStartup/Form.js
app/components/views/GetStartedPage/AdvancedStartup/RemoteDaemonForm.js
app/components/views/GetStartedPage/AdvancedStartup/index.js
app/style/MiscComponents.less

[launcher] Make path entries required

---

app/components/shared/ShowWarning.js
app/components/shared/index.js
app/components/views/TicketsPage/GovernanceTab/Page.js
app/components/views/TicketsPage/PurchaseTab/Tickets.js
app/config.js
app/connectors/index.js
app/connectors/spv.js
app/index.js
app/selectors.js
app/style/main.less
app/wallet/constants.js

This PR starts #1243. 
It adds SPV to config and remove the following functionalities when in spv.
- purchase ticket 
- ticket auto buyer
- vote

Start spv mode

---

app/actions/StakePoolActions.js
app/middleware/stakepoolapi.js
app/wallet/config.js
app/wallet/index.js
app/wallet/stakePool.js

I started promisifying the stakePoolApi.
As axios is already promisified, I am not sure the need to promisify the requests as well.
I like the way it is because the requests are centralized at the middleware,
what do you guys @matheusd and @alexlyp think?
Thanks.

promisify stakePoolApi

---

app/components/shared/VerticalAccordion.js
app/components/views/AccountsPage/Accounts/AccountRow/Row.js
app/components/views/AccountsPage/Accounts/AccountRow/index.js

This makes the individual account rows expand and contract as group, fixing a small ui regression.

[accounts] group vertical accordions

---

app/components/Snackbar/index.js

Fixes #1534 
Right now I am Removing messages that are the same or messages that have the same `txHash` so them only show once.

Agrouping messages so it only shows once

---

app/components/views/TransactionsPage/SendTab/OutputRow.js
app/components/views/TransactionsPage/SendTab/index.js

this displays the right amount to be sent when the send all button on the send transaction tab is clicked.
fixes #1556

Show send amount when send all button is clicked

---

app/actions/WalletLoaderActions.js
app/config.js
app/index.js
app/middleware/api.proto
app/middleware/walletrpc/api_pb.js

Missed an update to use `repeated string spv_connect`

Update to proper api.proto and bump required version

---

app/style/CreateWalletForm.less

Fix confirm seed page messing when width is too large

---

app/middleware/stakepoolapi.js

[stakepools] add Host attribute to stakepool stats response

---

app/components/TxHistory/TxHistoryRow/StakeTxRow.js
app/components/views/AccountsPage/Accounts/AccountRow/AccountDetails.js
app/components/views/AccountsPage/Accounts/AccountRow/Row.js
app/components/views/TransactionsPage/ExportTab/Page.js
app/components/views/TxDetails.js
app/selectors.js
app/style/AccountRow.less
app/style/ExportPage.less
app/style/GetStarted.less
app/style/Header.less
app/style/Layout.less
app/style/MiscComponents.less
app/style/MyTickets.less
app/style/TxHistory.less

[multi] Fix minors visual bugs

---

app/components/SideBar/Bar.js
app/components/SideBar/Logo.js
app/components/SideBar/index.js
app/connectors/sideBar.js
app/style/main.less

[sidebar] fix sidebar watch only wallet icon always showing

---

app/components/indicators/NoTransactions.js
app/components/views/TransactionsPage/HistoryTab/Page.js
app/style/MiscComponents.less

Darkened the grey to a close black for the _No Transactions Found_ label.
Fixes #1591

Low contrast label fix

---

app/components/views/GetStartedPage/index.js

Properly display version in Release Notes

---

app/components/views/GetStartedPage/WalletSelection/CreateWalletForm.js
app/components/views/GetStartedPage/WalletSelection/index.js

[launcher] Ensure that the pubkey as been attempted before throwing error

---

app/components/views/GovernancePage/Proposals/Details/UpdateVoteChoiceModalButton.js
app/components/views/GovernancePage/Proposals/Details/helpers.js
app/components/views/GovernancePage/Proposals/ProposalList.js
app/style/Governance.less
app/style/Settings.less

A couple of small fixes for small regressions introduced in some of the last UI refactorings.

[politeia] fix listing and voting UI

---

package.json
yarn.lock

[libs] update react-dom to 16.0.1

---

app/actions/GovernanceActions.js
app/components/views/GovernancePage/Proposals/Details/Page.js
app/components/views/GovernancePage/Proposals/Details/helpers.js
app/components/views/GovernancePage/Proposals/ProposalList.js
app/style/Governance.less

[politeia] show version and last updated time

---

app/components/modals/AboutModal/Modal.js

Fix link to release notes

---

app/actions/WalletLoaderActions.js

This was causing syncing to hang while in SPV mode.

[launch] Fix typo for SPV syncing

---

app/components/views/SettingsPage/Page.js
app/connectors/settings.js
app/selectors.js
app/style/Settings.less
app/wallet/control.js

Fix #1680 
This also disables changing the password while the request is executing.

[settings] Fix change password request

---

app/actions/ClientActions.js
app/actions/ControlActions.js
app/components/views/AccountsPage/Accounts/AccountRow/AccountDetails.js
app/style/AccountRow.less

Fix #1687 
Also slightly tweaks the design of the accounts page to account for languages where the labels in details was breaking the width of the line.

[accounts] Fix balances after acccount creation

---

app/actions/DaemonActions.js
app/actions/SettingsActions.js
app/actions/WalletLoaderActions.js
app/components/buttons/index.js
app/components/views/GetStartedPage/index.js
app/components/views/SettingsPage/GeneralSettings.js
app/components/views/SettingsPage/Page.js
app/connectors/settings.js
app/index.js
app/main.development.js
app/main_dev/ipc.js
app/main_dev/launch.js
app/reducers/daemon.js
app/reducers/settings.js
app/reducers/walletLoader.js
app/selectors.js
app/wallet/daemon.js

~This still requires pipe work to be merged for it to properly work on Windows.~
Currently there are 2 settings changes that will cause a reset to occur: SPV mode and Advanced Daemon.  We will be adding Network (mainnet/testnet) toggle once this PR has settled and has been shown to work.
Currently I am testing these possible paths:
I'll also be exposing the SPV Connect configuration option, but the above paths will be tested with this option turned off.  I will be probably adding SPV Connect setting to the options that cause reset.  But like network change we'll leave it for another PR.

[settings] Clean teardown upon certain setting changes

---

app/components/SideBar/MenuLinks/index.js
app/components/views/SettingsPage/PrivacySettings.js
app/config.js
app/connectors/routing.js
app/index.js
app/selectors.js

Also remove unneeded config checks.

[politeia] Enable politeia page by default

---

app/actions/ControlActions.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/index.js
app/connectors/ticketsPage.js
app/index.js
app/reducers/control.js
app/selectors.js

[tickets] Retain number of tickets attempted

---

app/components/modals/AboutModal/Modal.js

This should make it future proof as well.

[about] Fix version link in About Modal

---

app/components/views/TransactionsPage/HistoryTab/Page.js

[history] Show filter when no transactions are present

---

app/style/Governance.less

[politeia] Add mouseover cursors to a few links

---

app/actions/DaemonActions.js
app/components/views/GetStartedPage/WalletSelection/index.js

[launcher] Set lastaccess on startWallet

---

app/actions/StakePoolActions.js
app/components/views/TicketsPage/PurchaseTab/index.js

ImportScript and Add Stakepool are failing without this in master

[actions] Fix calls of importScriptAttempt

---

app/components/views/GovernancePage/Proposals/Details/helpers.js
package.json
test/data/FullProposalMarkdown.js
test/unit/components/views/GovernancePage/Proposals/Details/ProposalText.spec.js

**Requires #1737**
Fixes an issue with image references used in proposal texts not rendering and adds unit tests to verify that the full markdown example and specific protected cases are maintained.

[politeia] Fix and add test to ProposalText

---

app/components/SideBar/Bar.js
app/components/SideBar/LastBlockTime.js
app/components/SideBar/index.js
app/helpers/dateFormat.js
package.json
test/setup.js
test/unit/components/SideBar/LastBlockTime.spec.js
test/unit/helpers/date.spec.js
yarn.lock

Fixes the bug that was preventing the latest block time from updating in the sidebar.
I added unit tests to the relevant date functions, refactored and added tests to the component responsible for updating the block time.

[sidebar] Fix last block mined timestamp

---

app/components/views/GetStartedPage/SpvSync/index.js

Looks like a typo on the proper function to use for SpvSyncing was used.

[launcher] Fix restore wallet with SPV

---

app/components/modals/Modal.js
app/components/modals/PassphraseModal/PassphraseModal.js

Resolves https://github.com/decred/decrediton/issues/1736

Close passphrase modal on ESC keypress

---

app/components/buttons/index.js
app/components/views/SettingsPage/Page.js
app/connectors/settings.js
app/style/Icons.less
app/style/Settings.less
app/style/icons/closeWallet.svg

closes https://github.com/decred/decrediton/issues/1743
As I needed to rebase, I changed the toggle theme button place, this is how it looks right now:

Add close wallet button style

---

.travis.yml

Build with nodejs 10.13.0 LTS.

---

app/actions/DaemonActions.js
app/components/views/FatalErrorPage.js
app/main.development.js
app/main_dev/constants.js
app/main_dev/ipc.js
app/reducers/daemon.js
app/wallet/daemon.js

[launcher] Add get info

---

app/components/views/TicketsPage/PurchaseTab/StakeInfo/Display.js
app/components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfoDetailsSPV.js
app/components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfoRow.js
app/components/views/TicketsPage/PurchaseTab/StakeInfo/index.js
app/connectors/stakeInfo.js
app/index.js
app/middleware/api.proto
app/middleware/walletrpc/api_pb.js
app/selectors.js

[spv] Update stakeinfo display for SPV

---

app/actions/ClientActions.js
app/components/views/GovernancePage/Blockchain/Page.js
app/components/views/GovernancePage/Blockchain/index.js
app/style/Governance.less
app/style/StakePool.less

Close #1758 
This also changes how we update votes to multiple set up stakepools.  Instead of selecting a different stakepool and doing it individually, it will update all configured stakepools to the given selection.

[governance] Update consensus change voting page

---

app/components/views/TransactionsPage/ReceiveTab/Page.js

[Receive] Change span to div in address

---

app/components/views/GetStartedPage/DaemonLoading/Form.js
app/components/views/GetStartedPage/Logs/Form.js
app/components/views/GetStartedPage/PrivacyPage/CustomPrivacyOptions.js
app/components/views/GetStartedPage/Settings/Form.js
app/components/views/TxDetails.js
app/style/GetStarted.less
app/style/Layout.less
app/style/Settings.less
app/style/TxDetails.less

Close #1756 
This PR addresses the following:
- Custom Privacy Settings (buttons and alignment)
- Get Started Logs (scroll bars and alignment)
- Tx Details (Unconfirmed on Tickets and Non-Wallet Output alignment)

[style]  Fix minor 1.3.1 styling issues

---

app/components/views/GovernancePage/Proposals/Page.js
app/style/Governance.less

This PR is a clean up at governance page to also use tabbedpage

[Governance] Use tabbedPage at proposals

---

app/style/HomePage.less
app/style/TxHistory.less

[overview] Fix overview transactions spacing

---

app/components/views/HelpPage/LogsTab/Page.js
app/components/views/HelpPage/LogsTab/index.js
app/helpers/byteActions.js
app/main.development.js
app/main_dev/logging.js
app/wallet/daemon.js

This PR closes #1050 .
I changed the timeout which makes the logs auto update themselves, to update when clicking to show the log.
The way it was before, when opening the decrediton logs, it would spam the `getLogs` message on the decrediton log every 2 seconds.

[logs] Show decrediton logs at logs tab

---

app/components/SideBar/MenuLinks/index.js
app/components/views/GovernancePage/index.js
app/components/views/HomePage/tabs/Balance.js
app/components/views/HomePage/tabs/Tickets.js
app/components/views/HomePage/tabs/Transactions.js
app/style/Header.less
app/style/HomePage.less
app/style/Icons.less
app/style/icons/activeLegend.svg
app/style/icons/availLegend.svg
app/style/icons/lockedLegend.svg
app/style/icons/receivedLegend.svg
app/style/icons/sentLegend.svg
app/style/icons/votedLegend.svg

Close #1818 
Close #1819 
Also includes an ordering change to the sidebar menu.

[overview] Update legend for overview charts

---

app/components/inputs/StakePoolSelect.js

Something broke manual addition of stakepools in master (possibly one of the package upgrades we did since the last release).
This is to return that.

[stakepools] Return manual addition

---

app/components/views/InvalidRPCVersion.js

[error] Fix message about invalid RPC version

---

app/style/TxHistory.less

[overview] Fix pending overview transactions

---

app/reducers/snackbar.js
app/style/Snackbar.less

A few small code and ui improvements for the snackbar.
I was going to solve the text overflow issue in one way which I thought would be a larger bit of code, but ended up finding a simpler solution.

[snackbar] Small improvements

---

app/components/layout/TabbedPage.js
app/components/shared/RoutedTabsHeader.js
app/components/views/GovernancePage/Proposals/Page.js
app/components/views/GovernancePage/index.js
app/style/Governance.less
app/style/Layout.less
app/style/Themes.less

[governance] Various updates to proposal page styling

---

app/components/Snackbar/Notification/Message.js
app/components/Snackbar/Notification/Transaction.js
app/components/indicators/ProgressRing.js
app/style/Snackbar.less

Add a dashed line style (ticks) to ProgressRing

---

app/components/views/FatalErrorPage.js
app/style/MiscComponents.less

This will hopefully help users copy and paste their panics to share with devs for further assistance.

[logging] Add clipboard button and tweak fatal page styling

---

app/components/views/GetStartedPage/WalletSelection/Form.js

[launcher] Show the Create/Restore when no available wallets

---

app/actions/DaemonActions.js
app/components/views/GetStartedPage/DaemonLoading/Form.js
app/connectors/walletStartup.js
app/main_dev/launch.js
app/main_dev/logging.js
app/reducers/daemon.js
app/selectors.js

[launcher] Add log check for 1.4.0 dcrd reindexing

---

app/components/views/GetStartedPage/SpvChoicePage/TopLevelOptions.js

[launcher] Add link for indepth SPV information

---

app/components/indicators/LoaderBarBottom.js
app/components/views/GetStartedPage/DaemonLoading/Form.js

[ui] Fix estimation labels

---

app/i18n/docs/pt/ReleaseNotes/v1.4.0.md
app/i18n/docs/pt/index.js

Only makes sense when applied after #1897, otherwise it's unreachable.

[i18n] Add ptbr 1.4.0 release notes

---

app/components/modals/SeedCopyConfirmModal/Modal.js

[launcher] Confirm seed copy with enter

---

app/components/views/TicketsPage/index.js
app/components/views/TransactionsPage/HistoryTab/index.js

Changes the balances sizes for the tickets and transaction pages to
follow the convention for balances of < 13px font-sizes.
Close #1908

[multi] Change balance sizes

---

app/components/views/AccountsPage/Accounts/AccountRow/Row.js
app/style/AccountRow.less

[accounts] Improve revealed xpub design

---

app/components/views/SecurityPage/SignMessage/index.js
app/components/views/SecurityPage/VerifyMessage/index.js
app/style/SecurityCenterMessagePage.less

Slightly tweaks the color and simplifies the dom/css for implementing
it.
Fix #1910

[securitycenter] Fix message verify result colors

---

app/style/Governance.less
app/style/Layout.less

Closes https://github.com/decred/decred-binaries/issues/98

[governance] Fix long proposal scrolling

---

app/style/GetStarted.less
app/style/Loading.less
app/style/Logs.less
app/style/MiscComponents.less
app/style/ReceivePage.less
app/style/SideBar.less
app/style/Themes.less

Closer to a release-ready dark mode theme.  
Everything seems to be at least readable somewhat consistent now.

[themes] Various tweaks for cleaner dark-mode

---

app/components/inputs/StakePoolSelect.js
app/reducers/snackbar.js

Resolves https://github.com/decred/decrediton/issues/1929
While at it, I also fixed the snackbar message (it said "successfully added {host}" instead of the actual host).

New stakepool trailing slash

---

app/style/MyTickets.less

Fixes #1961 and also the card touching the number of days:

[myTickets] Fix text overlaps

---

app/actions/SettingsActions.js
app/actions/WalletLoaderActions.js
app/components/views/GetStartedPage/DaemonLoading/Form.js
app/components/views/GetStartedPage/Settings/Form.js
app/components/views/GetStartedPage/SpvSync/Form.js
app/components/views/GetStartedPage/index.js
app/components/views/SettingsPage/GeneralSettings.js
app/components/views/SettingsPage/Page.js
app/connectors/settings.js

This will show settings on the launcher all the time now.  It will hide any wallet related settings if there is no wallet yet loaded.

[launcher] Show settings on launcher

---

app/components/views/TicketsPage/MyTicketsTab/TicketCard.js
app/components/views/TicketsPage/MyTicketsTab/TicketInfoCard.js
app/style/MyTickets.less

[myTickets] Fix my tickets card not clickable in some areas

---

app/style/Modals.less

Fixed modal misalignment when menu is collapsed

---

app/containers/App.js
app/main_dev/launch.js
app/main_dev/templates.js

Resolves https://github.com/decred/decrediton/issues/1761

Properly shutdown on macOS Cmd-Q

---

app/connectors/spv.js
app/selectors.js

Solving #1974 
Removed all usages of spvMode and let isSPV stay in the app + overwritten spvMode values to use isSPV from now on

spvMode removed, isSPV stays (no duplicate)

---

app/style/Settings.less

Solving #1912 , took heavy inspiration from #1913

Settings option description alignment fixed

---

scripts/aliasDefaultMessage.js

Fix aliasDefaultMessage description

---

app/components/views/GetStartedPage/DaemonLoading/Form.js

[launcher] Fix last log line showing on wallets

---

app/components/views/GovernancePage/Proposals/Page.js

Fixes https://github.com/decred/decrediton/issues/2018

Fix inconsistent caps

---

app/selectors.js

[send] Update estimated fee to current network min relay fee (0.0001)

---

app/components/views/GetStartedPage/WalletSelection/Form.js
app/style/GetStarted.less
app/style/LanguageSelect.less

Get started page styling is off with small window sizes

---

app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ExistingSeed/Form.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ExistingSeed/index.js

fixes #1980
I removed the logic from the `ExistingSeed` form, to keep only `JSX`.
I also did some refactor because we have some repeated code.
When testing, I noticed the hex seed was not working, as described at #2011. I will work on this next.

[Restore Seed] Remove error message

---

app/actions/DaemonActions.js

Resolves https://github.com/decred/decrediton/issues/2016

Start daemon when finishing SPV selection

---

app/actions/SettingsActions.js

Fix daemon not starting after switching network

---

app/components/modals/AboutModal/AboutModal.js

The About modal still has 'Copyright 2018'. Updates to 2019.

Updates Copyright in About modal to 2019

---

app/actions/DaemonActions.js
app/components/views/GetStartedPage/index.js
app/config.js
app/main_dev/ipc.js
app/main_dev/launch.js
app/reducers/daemon.js

This PR closes #1228.
It stills a work in progress, because I noticed dcrd logs are not showing when starting the app with a different appdata, and I believe it can be ok to fix on this PR. 
If I notice it is getting too big, I'll open a new one and let you all know.

Fix advanced mode with empty appdata directory not starting

---

app/actions/StatisticsActions.js

[export] fix wrong total on daily balance export

---

app/main_dev/ipc.js
app/main_dev/launch.js

This PR fixes a bug I noticed when switching network at the settings page after commit https://github.com/decred/decrediton/commit/b4125648364222a1cd6968277141a38779f6643e

Fix trying to close remote dcrd

---

app/components/views/HelpPage/LinksTab/index.js

[help] Update ordering and remove old comms

---

app/components/inputs/Input.js
app/components/inputs/NumTicketsInput.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/Form.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/index.js
app/style/Input.less
app/style/PurchaseTickets.less

After commit 9a5048111fbf21c97be3629cbeeaad02c84bebbb the input error is showing wrongly. 

fix ticket numeric input showing error at wrong place

---

app/components/views/GetStartedPage/index.js

Enable access to logs page during initial sync

---

app/components/views/GetStartedPage/PrivacyPage/TopLevelOptions.js
app/components/views/GetStartedPage/SpvChoicePage/TopLevelOptions.js
app/style/GetStarted.less
app/style/LanguageSelect.less
app/style/icons/logo.svg
app/style/icons/logoDark.svg

Closes:
Responsive views: Language selection (#2052)
Responsive views: SVP selection (#2053)
Responsive views: Privacy selection (#2054)
Responsive views: What's new (#2055)

Responsive views: svp, privacy, language, release notes

---

app/components/views/GetStartedPage/TutorialPage/Page.js
app/style/Themes.less
app/style/Tutorial.less

Responsive views: Onboarding slides

---

app/components/views/TicketsPage/PurchaseTab/StakePools/AddForm.js
app/style/Layout.less
app/style/StakePool.less

Responsive views: Add a stakepool

---

package.json

Set artifactName

---

app/selectors.js
app/style/TxHistory.less

Fix recent transactions icons

---

app/components/views/TransactionsPage/SendTab/OutputRow.js
app/components/views/TransactionsPage/SendTab/Page.js
app/components/views/TransactionsPage/SendTab/index.js
app/style/Input.less
app/style/SendPage.less

This PR closes https://github.com/decred/decrediton/issues/1947 and https://github.com/decred/decrediton/issues/2214

[Responsive] Send Transaction view

---

app/components/SideBar/Bar.js
app/style/MiscComponents.less
app/style/SideBar.less

Fix cancel rescan button alignment

---

app/main_dev/launch.js

This adds a wait for the dcrd.cert file to be generated, since on the very
first run (or when the file doesn't exist) the connection attempt to the node
cannot proceed.
Previously this was throwing a fatal exception.
You can test the current master is broken by removing the standard dcrd's `rpc.cert`/`rpc.key` files.

[maindev] Wait for dcrd's rpc.cert to be generated

---

app/style/GetStarted.less

Show missing log headers on smaller screens

---

app/components/views/TransactionsPage/SendTab/index.js

Fix AccountsSelect on SendTab

---

app/style/Layout.less
app/style/PurchaseTickets.less
app/style/SendPage.less

This PR fix some minor tweaks. It fixes:
- Purchase ticket input with 2 borders when it has error
- Fixed send button on small screens. Fixes https://github.com/decred/decrediton/issues/2222
- Fix subtitle with width bigger then content

[Multi] Fix views tweaks

---

app/components/views/GetStartedPage/CreateWallet/index.js
app/components/views/GetStartedPage/DaemonLoading/Form.js
app/components/views/GetStartedPage/LanguageSelectPage/Page.js
app/components/views/GetStartedPage/LanguageSelectPage/index.js
app/components/views/GetStartedPage/Logs/Form.js
app/components/views/GetStartedPage/PrivacyPage/Page.js
app/components/views/GetStartedPage/ReleaseNotes/Form.js
app/components/views/GetStartedPage/Settings/Form.js
app/components/views/GetStartedPage/SpvChoicePage/Page.js
app/components/views/GetStartedPage/SpvSync/Form.js
app/components/views/GetStartedPage/TrezorConfig/Page.js
app/style/GetStarted.less

Testnet Logo in Launcher

---

app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ConfirmSeed/Form.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/CreateWallet.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ExistingSeed/Form.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/SingleSeedWordEntry.js
app/i18n/docs/en/Warnings/WalletCreation.md
app/style/CreateWalletForm.less
app/style/GetStarted.less
app/style/ReactSelectGlobal.less
app/style/Themes.less
app/style/icons/select-arrow-up.svg
app/style/icons/selectArrowUpDark.svg

This closes #2209, closes #2210, and closes #2235

Seedword Field improvements

---

app/components/views/GetStartedPage/AdvancedStartup/AppDataForm.js
app/components/views/GetStartedPage/AdvancedStartup/Form.js
app/components/views/GetStartedPage/AdvancedStartup/RemoteDaemonForm.js
app/style/CreateWalletForm.less
app/style/GetStarted.less
app/style/Input.less
app/style/MiscComponents.less
app/style/TextToggle.less
app/style/Themes.less

Responsive `Advanced Daemon` view

---

app/actions/GovernanceActions.js
app/actions/WalletLoaderActions.js
app/components/views/GovernancePage/Proposals/Details/Page.js
app/components/views/GovernancePage/Proposals/Details/index.js
app/main_dev/paths.js
app/middleware/politeiaapi.js
app/style/Governance.less

requires #2203 
This PR closes #2244 and cache cast votes when user open proposal details

[Governance] Show finished votes and wallet eligible tickets

---

app/actions/SettingsActions.js
app/components/views/AccountsPage/Page.js
app/components/views/GetStartedPage/Logs/Form.js
app/components/views/GetStartedPage/Settings/index.js
app/components/views/TicketsPage/PurchaseTab/TicketAutoBuyer/Form.js
app/style/AccountsPage.less

closes #2267, closes #2268, closes #2271, closes #2272

[Multi] Release fixes

---

app/components/views/GetStartedPage/index.js

Fix settings link on the launcher

---

app/style/AccountRow.less
app/style/icons/account-rename.svg

Change the "rename" icon on Accounts view

---

app/components/views/TransactionsPage/ExportTab/Page.js
app/style/AccountsPage.less
app/style/ExportPage.less
app/style/Governance.less
app/style/Help.less
app/style/HistoryPage.less
app/style/HomePage.less
app/style/Layout.less
app/style/Logs.less
app/style/MiscComponents.less
app/style/MyTickets.less
app/style/PurchaseTickets.less
app/style/ReceivePage.less
app/style/SecurityCenterMessagePage.less
app/style/StakePool.less

Content area alignment simplification

---

app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ConfirmSeed/Form.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/createWalletHeader.js
app/style/CreateWalletForm.less
app/style/GetStarted.less

Fix misaligned password fields on the `Create a New Wallet` view

---

app/style/StakePool.less

Fix misaligned continue button on "Add a VSP" view

---

app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ConfirmSeed/Form.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ExistingSeed/Form.js
app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/SingleSeedWordEntry.js
app/style/ReactSelectGlobal.less

Revert dropdown skin everywhere but in seedword dropdowns

---

app/components/views/HomePage/Page.js
app/style/HomePage.less

Fix overview chart buttons misalignments 

---

app/actions/TrezorActions.js
app/actions/WalletLoaderActions.js
app/components/shared/VerticalAccordion.js
app/components/views/TransactionsPage/SendTab/Page.js
app/constants/config.js
app/helpers/trezor.js
package.json
yarn.lock

[trezor] RC tweaks

---

app/components/views/SecurityPage/ValidateAddress/Form.js
app/style/CreateWalletForm.less
app/style/Layout.less
app/style/SecurityCenterMessagePage.less
app/style/TextToggle.less

Responsive Security Center

---

app/style/ExportPage.less

Responsive Transaction Export

---

app/components/views/TransactionsPage/ReceiveTab/Page.js
app/style/MiscComponents.less
app/style/ReceivePage.less

Responsive Transaction Receive

---

app/components/views/HelpPage/LogsTab/Page.js
app/components/views/LNPage/ChannelsTab/Page.js
app/components/views/LNPage/ChannelsTab/index.js
app/components/views/LNPage/ConnectPage.js
app/connectors/lnPage.js
app/connectors/logging.js
app/index.js
app/main_dev/launch.js
app/middleware/ln/client.js
app/reducers/ln.js
app/selectors.js
app/style/LN.less
app/wallet/ln/index.js

close #2293 
close #2291 
close #2283 
Also fixes an issue starting dcrlnd on mainnet and disables the `Push Amount` option on mainnet due to possible misuse by users.

[ln] Fixes for RC issues

---

app/style/Governance.less
app/style/Header.less
app/style/HistoryPage.less
app/style/HomePage.less
app/style/Input.less
app/style/Layout.less
app/style/Loading.less
app/style/Logs.less
app/style/MiscComponents.less
app/style/MyTickets.less
app/style/Paginator.less
app/style/PurchaseTickets.less
app/style/ReactSelectGlobal.less
app/style/SecurityCenterMessagePage.less
app/style/SideBar.less
app/style/Snackbar.less
app/style/StakePool.less
app/style/Trezor.less
app/style/TxHistory.less
app/style/main.less

Expected space before "-" operator   function-calc-no-invalid
Expected space after "-" operator    function-calc-no-invalid
Expected space before "-" operator   function-calc-no-invalid
Expected space after "-" operator    function-calc-no-invalid
Expected space before "-" operator   function-calc-no-invalid
Expected space after "-" operator    function-calc-no-invalid

layout: fix linter warnings

---

app/components/buttons/index.js
app/components/views/GovernancePage/Proposals/Details/helpers.js
app/style/Governance.less

fixes https://github.com/decred/decrediton/issues/2270

Add modal to open proposal link

---

app/components/views/GetStartedPage/AdvancedStartup/Form.js
app/components/views/GetStartedPage/DaemonLoading/Form.js
app/components/views/GetStartedPage/SpvSync/Form.js
app/components/views/GetStartedPage/WalletSelection/Form.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseTicketsAdvanced.js
app/components/views/TicketsPage/PurchaseTab/Tickets.js
app/main.development.js

An upcoming update to babel-loader complains about the 
last commas with the spreader argument.

[lint] New version of babel-loader spreader fixes

---

yarn.lock

Fixes:
https://www.npmjs.com/advisories/1300
https://www.npmjs.com/advisories/1316
https://www.npmjs.com/advisories/1324
https://www.npmjs.com/advisories/1325

upgrade jest:

---

app/components/modals/InfoModal/Modal.js
app/components/modals/Modal.js
app/components/views/AccountsPage/Page.js
app/components/views/SecurityPage/SignMessage/Form.js
app/components/views/SettingsPage/GeneralSettings.js
app/components/views/TicketsPage/PurchaseTab/Tickets.js
app/style/Layout.less
app/style/Modals.less
package.json
yarn.lock

Info modals enhancements

---

app/actions/GovernanceActions.js

Fix duplicate proposals

---

app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/Form.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseTicketsAdvanced.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseTicketsQuickBar.js
app/components/views/TicketsPage/PurchaseTab/StakeInfo/Display.js
app/components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfoDetails.js
app/style/Input.less
app/style/MiscComponents.less
app/style/PurchaseTickets.less

[MULTI] Fix Purchase Tickets visual design issues

---

app/components/layout/TitleHeader.js
app/style/Layout.less
app/style/Settings.less

I noticed the close wallet button at settings gets missed on smaller screens.

Fix close wallet button missin in smaller screens

---

app/style/GetStarted.less
app/style/Governance.less
app/style/Themes.less

Multi fixes

---

app/components/SideBar/Bar.js
app/components/shared/Balance.js
app/style/SideBar.less
app/style/Themes.less

Accounts quick preview enhancements

---

app/style/ReceivePage.less
app/style/Themes.less

Fix background color on Receive DCR view

---

app/components/shared/PoliteiaLink.js
app/components/views/GovernancePage/Blockchain/Page.js
app/components/views/GovernancePage/Proposals/Details/Page.js
app/components/views/GovernancePage/Proposals/ProposalList/Page.js
app/components/views/GovernancePage/Proposals/ProposalList/index.js
app/style/AgendaCard.less
app/style/Governance.less
app/style/Layout.less
app/style/MiscComponents.less

This PR closes #2046 and closes #1952, and we are close to finish https://github.com/decred/decrediton/issues/1945, still remain some tweaks at the consensus view to finish, which I believe will be better to finish after #1316 is done.

Responsive governance

---

app/actions/SettingsActions.js

This fixes the save settings action which was failing.

[actions] Fix save settings

---

app/components/views/GetStartedPage/SpvChoicePage/TopLevelOptions.js
app/reducers/snackbar.js

[multi] Fix spv link spacing and repeated VSP notification

---

app/components/inputs/NumTicketsInput.js
app/components/views/TransactionsPage/SendTab/OutputRow.js
app/style/PurchaseTickets.less
app/style/SendPage.less

NumTicketsInput enhancements

---

app/components/views/TransactionsPage/SendTab/OutputRow.js
app/components/views/TransactionsPage/SendTab/Page.js
app/style/PurchaseTickets.less
app/style/SendPage.less
app/style/Themes.less

[send] Fix misalignament and shadow

---

app/components/buttons/VerticalExpand.js
app/components/buttons/index.js
app/components/views/TicketsPage/PurchaseTab/StakeInfo/Display.js
app/components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfoDetails.js
app/components/views/TicketsPage/PurchaseTab/StakeInfo/index.js
app/style/PurchaseTickets.less

Fix Stake info details error and clean up

---

app/components/views/AccountsPage/AccountRow/Row.js

Fix imported account showing 0

---

app/components/inputs/DcrInput.js
package.json
test/unit/components/inputs/DcrInput.spec.js
yarn.lock

The latest chage to DcrInput broke some input combinations. This fixes them and
adds a set of unit tests to ensure the proper behavior of DcrInput in DCR mode.

[inputs] Fix some DcrInput instances

---

yarn.lock

https://www.npmjs.com/advisories/1426

deps: upgrade terser-webpack-plugin

---

package.json

Capitalize "Decrediton" on macOS

---

app/reducers/snackbar.js

Remove double notification when sending tx

---

app/components/views/GetStartedPage/PrivacyPage/TopLevelOptions.js
app/style/GetStarted.less
app/style/MiscComponents.less

[startup] Fix tutorial pointer and icon background

---

app/main.development.js

The second instance message window pops up but cannot be closed, so I added instruction for quitting. 
closes #2381

fix closing second instance

---

app/style/main.less

This fixes an annoying behaviour where text is draggable. Also makes the app feel more "solid"
**Before:**
**After:**
Based on https://gist.github.com/msuchodolski/41c9338f3a732379dc570142826ed76e

Disable element selection

---

app/components/views/GovernancePage/Proposals/PoliteiaDisabled.js
app/style/Governance.less

Fix margin on governance tab

---

app/main_dev/launch.js

dcrlnd: remove namespacing from lauch opts

---

app/components/views/FatalErrorPage.js
app/style/Layout.less

Fix misspelling at Fatal error Page

---

app/components/views/GetStartedPage/Settings/Form.js
app/components/views/SettingsPage/PrivacySettings.js
app/connectors/settings.js
app/selectors.js

This PR fixes conflicts after rebase of latest refactor_startup.
I also noticed a couple of wallet configs at startup config and removed them.

[Refactor_startup] fix conflicts after rebase

---

app/constants/Messages.js
app/constants/config.js
app/main.development.js
app/main_dev/externalRequests.js
app/main_dev/launch.js
app/main_dev/proxy.js
app/package.json
app/yarn.lock
package.json
webpack.config.electron.js
yarn.lock

Upgrade to electron 8

---

package.json

After d3e18e5313b25941574a8cd541a69b6ab885dae2, I hitted an error complaning about sandbox, so this PR deactivate it in dev mode.
Related: https://github.com/electron/electron/issues/17972

Disable sandbox

---

app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/Form.js
app/selectors.js

We've received various support issues with people not being able to properly see the revoke button.
There really isn't any harm in people attempting to revoke their tickets, so I figured it we can show it and maybe just add a note to say this will only revoke tickets if unspent missed/expired tickets are available.

[tickets] Show revoke button all the time

---

app/components/views/GetStartedPage/index.js
app/style/Loading.less

Fix loading bar animations 

---

app/components/views/GovernancePage/Proposals/Details/Page.js
app/style/Governance.less

Single proposal view responsive

---

app/components/inputs/StakePoolSelect.js

Closes https://github.com/decred/decrediton/issues/2396

Improve new VSP UX

---

app/components/views/GovernancePage/Proposals/ProposalsList/ProposalsList.jsx
app/components/views/GovernancePage/Proposals/ProposalsList/ProposalsList.module.css
app/components/views/GovernancePage/Proposals/hooks.js

Closes https://github.com/decred/decrediton/issues/2499. This PR prevents the full proposal list re-rendering. After that, it'll be necessary to rewrite some code at https://github.com/decred/decrediton/pull/2473, including maybe the ``switch`` ``case`` statement.

Fix scrollbar returning to top after loading proposals

---

app/components/views/GetStartedPage/CreateWallet/hooks.js
app/components/views/GetStartedPage/CreateWallet/index.js
app/components/views/ProposalDetailsPage/ProposalDetails.module.css
app/components/views/ProposalDetailsPage/helpers/ChooseOptions.jsx
app/style/main.less
yarn.lock

Integrates pi-ui's `RadioButtonGroup` to display vote preferences in proposal details page.
Waiting on: https://github.com/decred/pi-ui/pull/266
Closes #2505

[pi-ui] Integrate RadioButtonGroup to display vote preferences

---

app/actions/ControlActions.js

Closes https://github.com/decred/decrediton/issues/2484.

Check stakepool stats before purchasing a ticket

---

app/actions/SidebarActions.js

Reduce sidebar redux actions

---

.prettierignore

These are automatically generated so it doesn't make sense to prettify them.

[prettify] Ignore generated protobuf files

---

app/components/shared/TxHistory/Row.jsx
app/style/themes/lightTheme.js

Sidebar: fix active security icon

---

app/actions/GovernanceActions.js
app/middleware/politeiaapi.js
app/wallet/index.js
app/wallet/politeia.js

Closes https://github.com/decred/decrediton/issues/2519.

Promisify politeia API requests

---

app/actions/ClientActions.js
app/actions/GovernanceActions.js
app/components/views/GovernancePage/Proposals/ProposalsList/ProposalsList.jsx
app/components/views/GovernancePage/Proposals/hooks.js
app/reducers/governance.js
app/selectors.js

This diff fixes politeia infinite loading when tokeninventory request
fails. Now, when the request fails, an error message is displayed to the
user.
before:
after:

[governance] fix: improve politeia fail

---

app/components/shared/Balance.js

This PR fixes https://github.com/decred/decrediton/issues/2590

Fix double negative

---

app/components/Snackbar/Notification/Transaction.js

fix tx going to wrong place

---

yarn.lock

Bumps pi-ui version from commit `4565e4d8b5dca32d3a2d54107f358183b3f57df1` to commit `51e574b5744fd680fb95033aebb718677efc6c86`.

Bump pi-ui version

---

app/components/views/GovernancePage/Proposals/ProposalsListItem/ProposalsListItem.jsx

This diff adds short tokens to the proposals list which was left out in #2602

[governance] Show short token in proposals list

---

app/components/shared/TxHistory/StakeTxRow.jsx
app/components/shared/TxHistory/helpers.js

I noticed right now immature and live tickets are showing as Purchased, at our txs row.

Fix stake txs label

---

app/components/views/TransactionPage/Page.js
app/components/views/TransactionPage/TransactionPage.jsx
app/components/views/TransactionPage/hooks.js

This PR fixes #2614.
I also took the time to create a hooks file so we can better organize the code.

Fix function when tx is pending

---

test/unit/components/SideBar/Sidebar.spec.js

This diff fixes #2606. Selectors are mocked instead of injecting the initial redux store if it is possible.

Fix SideBar automated tests

---

app/components/modals/Modals.module.css
app/components/views/GetStartedPage/Settings/Settings.jsx
app/components/views/ProposalDetailsPage/helpers/EligibleTickets/EligibleTickets.module.css
app/components/views/SettingsPage/PrivacySettings.jsx
app/components/views/SettingsPage/Settings.jsx
app/components/views/SettingsPage/Settings.module.css
app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/index.js
app/components/views/TransactionsPage/ReceiveTab/ReceiveTab.module.css
app/style/ExportPage.less
app/style/HomePage.less
app/style/Layout.less
app/style/MiscComponents.less
app/style/SendPage.less

This PR fixes multiple ``CSS`` minor bugs in Decrediton. All bugs listed in https://github.com/decred/decrediton/issues/2639 have been solved, cept tx lists in "Transaction History" page and "My Tickets" page.

Fix multiple minor CSS misalignments

---

app/actions/WalletLoaderActions.js
app/components/views/GetStartedPage/hooks.js

Fix spv wallet not starting

---

app/components/views/SettingsPage/Settings.module.css
app/components/views/SettingsPage/TimezoneSettings.jsx
package.json
yarn.lock

This diff replaces custom radio buttons used in timezone settings with pi-ui's component.
Closes #2653 
Needs https://github.com/decred/pi-ui/pull/293
---
Before:
After:

[settings] Use pi-ui's radio buttons in timezone settings

---

app/actions/DaemonActions.js
app/components/views/FatalErrorPage.js
app/components/views/GetStartedPage/hooks.js
app/main.development.js
app/main_dev/launch.js
app/style/Layout.less

[launch] Return to daemon connection on error

---

app/middleware/politeiaapi.js
app/wallet/politeia.js

[governance] ditch old not used pi routes

---

app/components/views/GetStartedPage/hooks.js

Uncaught TypeError on `OpenWallet` component: `onOpenWallet is not a function`

[launcher] not possible to open a decrypted wallet

---

app/actions/TransactionActions.js
app/actions/TrezorActions.js
app/components/modals/trezor/WalletCreationPassPhraseModal.js
app/helpers/msgTx.js
app/helpers/trezor.js
test/data/decodedTransactions.js
test/unit/helpers/encodeWitness.spec.js
test/unit/wallet/service.spec.js

Some bugfixes for the current master for transaction signing when using trezor.
Individual commits should be easy to review individually.

[Trezor] Tx Signing Fixes

---

app/components/views/SecurityPage/SignMessage/SignMessageForm.jsx
app/components/views/SecurityPage/SignMessage/hooks.js

It doesn't look like the button has an `onSubmit`: https://github.com/decred/pi-ui/blob/master/src/components/Button/Button.jsx
Also was not passing needed params I believe. Please check me.

trezor: Allow message signing.

---

app/components/shared/Balance.js
test/unit/components/Balance.spec.js

Comma seperated atom values

---

app/components/views/HelpPage/TutorialsTab/TutorialsTab.module.css
app/components/views/HelpPage/TutorialsTab/index.js
app/components/views/HomePage/RecentTransactions/RecentTransactions.jsx

Fix tutorial link styles

---

app/components/views/GetStartedPage/CreateWalletPage/ExistingSeed/ExistingSeed.jsx

Add missing error message to ExistingSeed view

---

app/actions/VSPActions.js
app/config.js

Fix backup redeem script warning reappearing after restart

---

app/components/views/TransactionsPage/SendTab/SendPage/SendPage.module.css
app/wallet/daemon.js

Tiny fixes

---

app/components/views/AccountsPage/Accounts/hooks.js

[Accounts] fix the failing new account creation

---

app/actions/StatisticsActions.js
app/components/views/TransactionsPage/ExportTab/helpers.js
app/selectors.js

This diff fixes some errors on the export of ticket statistics.
Closes #2692 and #2693

Fix ticket statistics export

---

app/components/views/GetStartedPage/GetStarted.module.css

Fix advanced mode on small width

---

app/components/buttons/EyeFilterMenu/EyeFilterMenu.module.css

Fix dropdown z-index on Tx History view

---

app/actions/TransactionActions.js
app/components/shared/TxHistory/StakeTxRow.jsx
app/components/shared/TxHistory/TxHistory.module.css
app/components/views/TicketsPage/MyTicketsTab/MyTicketsTab.jsx
app/components/views/TicketsPage/MyTicketsTab/MyTicketsTab.module.css
app/components/views/TicketsPage/MyTicketsTab/Page.jsx
app/components/views/TicketsPage/MyTicketsTab/VoteChoice.jsx
app/components/views/TicketsPage/StatisticsTab/Page.jsx
app/components/views/TicketsPage/hooks.js
app/constants/Decrediton.js
app/style/MiscComponents.less

This diff closes #2670 and closes #2521 by refactoring MyTickets page to a functional approach, by using hooks and css modules.

[MyTickets] functional components, hooks & css modules 

---

app/components/views/GetStartedPage/CreateWalletPage/CreateWalletPage.jsx
app/components/views/GetStartedPage/GetStarted.module.css
app/stateMachines/CreateWalletStateMachine.js

Confirm seed view and button covers error fixes

---

app/components/inputs/DcrInput.js
app/components/inputs/index.js
app/components/views/TransactionsPage/SendTab/SendTab.jsx
app/helpers/strings.js

This PR fixes #2682 
~~It is still a wip because right now after a transaction is sent, its value is kept, which I still haven't figured why.~~

Dcr input func comp

---

app/components/modals/Modals.module.css
app/components/views/GetStartedPage/GetStarted.module.css
app/components/views/GetStartedPage/PrivacyPage/PrivacyPage.jsx
app/components/views/GetStartedPage/hooks.js

Closes #2660
I cherry-picked commits relevant to #2660 into this separate PR to be easier reviewed.

[launcher] fix some minor issues on GetStarted views

---

app/actions/ControlActions.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/Page.jsx
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseForm.jsx
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseTickets.jsx
app/components/views/TicketsPage/PurchaseTab/hooks.js
app/helpers/tickets.js
app/wallet/control.js

This is built on top of @vctt94's v3 auto buyer PR.
This allows for manual ticket purchasing for v3 vsp tickets.

[tickets] Add manual v3 VSP ticket purchasing

---

app/components/views/GetStartedPage/CreateWalletPage/ConfirmSeed/Form.jsx
app/components/views/GetStartedPage/CreateWalletPage/CopySeed/Form.jsx
app/components/views/GetStartedPage/CreateWalletPage/CreateWallet.module.css
app/components/views/GetStartedPage/CreateWalletPage/ExistingSeed/Form.jsx
app/components/views/GetStartedPage/GetStarted.module.css

Centering loading indicator on creating/restoring wallet

---

app/actions/VSPActions.js
app/components/views/SettingsPage/PrivacySettings.jsx
app/components/views/TicketsPage/MyTicketsTab/MyTicketsTab.jsx
app/components/views/TicketsPage/MyTicketsTab/hooks.js
app/components/views/TicketsPage/PurchaseTab/PurchaseTab.jsx
app/components/views/TicketsPage/PurchaseTab/hooks.js
app/components/views/TicketsPage/TicketsPage.jsx
app/index.js
app/reducers/vsp.js
app/selectors.js

Multi: fix warning on settings page and make persistent IsLegacy across screens

---

app/components/views/AccountsPage/Privacy/ConfigMixer/ConfigMixer.jsx
app/components/views/AccountsPage/Privacy/ConfigMixer/CreateDefaultAccounts.jsx
app/components/views/AccountsPage/Privacy/ConfigMixer/CreateNeededAccounts.jsx
app/components/views/AccountsPage/Privacy/hooks.js
app/reducers/grpc.js
app/selectors.js

Disable the "create accounts" button and set it to the loading state

---

app/components/shared/TxHistory/TxHistory.module.css

Fix eligible tickets misalignments

---

app/components/SideBar/MenuBottom/MenuBottom.module.css
app/components/SideBar/MenuBottom/MenuBottomCollapsed.jsx
app/components/indicators/indicators.module.css

Vertical align rescan button with neighbouring text.

---

app/components/SideBar/SideBar.module.css

Closes https://github.com/decred/decrediton/issues/2793.

Fix sidebar small menu icon

---

app/components/views/AccountsPage/Privacy/ConfigMixer/CreateDefaultAccounts.jsx
app/components/views/LNPage/ConnectPage.js
app/i18n/docs/en/Warnings/LNWalletCreation.md
app/i18n/docs/en/Warnings/SeedCopy.md
app/reducers/snackbar.js

- LN Connect page - Spell out Lightning Network in heading and description. Using abbreivated LN in some places is fine, but for headings its unusual.
- Reword the LN Wallet Creation preamble. Reduce the length of the text whilst keeping all vital information. Don't mention lnd - deep implementation detail not familiar to most end-users. Dont mention bitcoin.

String updates.

---

app/style/LN.less

[CSS] Improve LN Warning style

---

app/actions/DaemonActions.js
app/components/indicators/AnimatedLinearProgressFull.jsx
app/components/views/GetStartedPage/GetStarted.module.css
app/components/views/GetStartedPage/GetStartedMachinePage.jsx
app/components/views/GetStartedPage/hooks.js
app/components/views/HelpPage/LogsTab/Page.jsx
app/hooks/useDaemonStartup.js
app/main_dev/logging.js
app/reducers/daemon.js

This PR fixes #2689. Fixes #2781 and it also re-add the dcrd logs which were missing from the linear progress component.

Fix dcrd db upgrade not being notify

---

app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_AddForm.js
app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/hooks.js
app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/index.js

fix add legacy custom stakepool

---

app/actions/ControlActions.js
app/components/modals/CantCloseModals/AutobuyerRunningModal.jsx
app/components/modals/CantCloseModals/CantCloseModals.jsx
app/components/modals/CantCloseModals/HasTicketFeeError.jsx
app/components/modals/CantCloseModals/hooks.js
app/components/modals/index.js
app/connectors/app.js
app/containers/App.js
app/main.development.js
app/main_dev/templates.js
app/selectors.js

This PR improves our ticket buyer closing warning for also warning when there is tickets which failed to properly register on vsp.

Add closing warn when has tickets with vsp ticket fee error

---

app/actions/ClientActions.js
app/components/layout/StandalonePage.js
app/components/views/TransactionPage/TransactionPage.jsx
app/reducers/grpc.js

[TransactionPage] fix: clear abandoned transaction from tx history lists

---

app/components/SideBar/MenuLinks/MenuLink/MenuLink.jsx
app/components/SideBar/MenuLinks/MenuLink/MenuLink.module.css
app/components/SideBar/MenuLinks/MenuLinks.jsx
app/components/SideBar/MenuLinks/hooks.js
app/components/SideBar/SideBar.jsx
app/components/SideBar/SideBar.module.css
test/unit/components/SideBar/Sidebar.spec.js

Closes https://github.com/decred/decrediton/issues/2584.

[sidebar] Add tooltips to sidebar menu links

---

app/components/views/LNPage/ChannelsTab/ChannelsTab.module.css
app/components/views/LNPage/NetworkTab/NetworkTab.module.css
app/components/views/LNPage/WalletTab/WalletTab.module.css

This PR adjusts LN tiles responsiveness to make them fit better on small screens and resolutions.
Before:
After:
Closes https://github.com/decred/decrediton/issues/2791.

Make LN tiles more responsive

---

app/components/views/GetStartedPage/PrivacyPage/CustomPrivacyOptions.jsx
app/components/views/GetStartedPage/PrivacyPage/PrivacyPage.jsx
app/components/views/GetStartedPage/Settings/Settings.jsx
app/components/views/SettingsPage/PrivacySettings.jsx
app/components/views/SettingsPage/Settings.jsx

Closes https://github.com/decred/decrediton/issues/2790.

Do not show change passphrase option when launching

---

app/components/modals/Modals.module.css
app/components/views/LNPage/ChannelsTab/ChannelsTab.module.css
app/components/views/LNPage/NetworkTab/NetworkTab.jsx
app/components/views/LNPage/NetworkTab/NetworkTab.module.css
app/components/views/LNPage/PaymentsTab/Page.js
app/components/views/LNPage/PaymentsTab/PaymentsTab.module.css
app/components/views/LNPage/WalletTab/Page.js
app/components/views/LNPage/WalletTab/WalletTab.module.css
app/components/views/LNPage/WatchtowersTab/WatchtowersTab.module.css
app/style/Header.less
app/style/icons/search-light.svg
app/style/themes/icons.js

Closes https://github.com/decred/decrediton/issues/2811.
Closes https://github.com/decred/decrediton/issues/2804.

Fix several LN minor CSS bugs

---

app/actions/DaemonActions.js
app/actions/VSPActions.js
app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_AddForm.js
app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_Tickets.js
app/config.js
app/constants/config.js
app/index.js

Multi: fix "Is Legacy" control misalignment, set its default value to checked, and make it persistent

---

app/components/views/TransactionsPage/SendTab/SendOutputRow/SendOutputRow.jsx
app/components/views/TransactionsPage/SendTab/SendTab.jsx
app/components/views/TransactionsPage/SendTab/hooks.js

[TX Send] Fix `Send all funds` issue

---

app/reducers/daemon.js

fix dcrd not starting after daemon started once

---

app/actions/WalletLoaderActions.js
app/components/views/GetStartedPage/hooks.js
app/hooks/useDaemonStartup.js
app/index.js
app/reducers/walletLoader.js
app/selectors.js

This PR aims to resolve some weird behaviors on launch which were spotted by @davecgh

Fix launch weird behavior

---

app/wallet/loader.js
app/wallet/version.js

This PR removes the certs which are being logged

Remove certs logs

---

app/components/views/HelpPage/LogsTab/Page.jsx

Closes https://github.com/decred/decrediton/issues/2826.

Add padding to dcrwallet logs

---

app/components/views/TransactionsPage/HistoryTab/HistoryTab.jsx

Increase threshold size, so it also loads more on smaller screens

---

app/style/icons/menu-rescanDark-hover.svg
app/style/themes/darkTheme.js
app/style/themes/icons.js
app/style/themes/lightTheme.js

Previously there was no darkmode icon, and the lightmode icon was barely visible.

Add darkmode rescan hover icon.

---

app/actions/ControlActions.js
app/components/shared/PrivacyForm/PrivacyForm.jsx
app/components/shared/PrivacyForm/hooks.js
app/components/views/PrivacyPage/Privacy/hooks.js
app/selectors.js

Privacy: Hide mixed account branch.

---

app/components/views/GetStartedPage/hooks.js

[GetStarted] Don't ask for pwd on watching only wallets

---

app/components/views/LNPage/ConnectPage.js
app/components/views/LNPage/index.js
app/components/views/PrivacyPage/Privacy/ConfigMixer/ConfigMixer.jsx
app/components/views/PrivacyPage/Privacy/ConfigMixer/CreateDefaultAccounts.jsx
app/components/views/PrivacyPage/Privacy/ConfigMixer/CreateNeededAccounts.jsx
app/components/views/PrivacyPage/Privacy/Privacy.module.css
app/components/views/PrivacyPage/Privacy/PrivacyContent.jsx
app/i18n/docs/en/Warnings/MixerIntroduction.md
app/i18n/docs/en/index.js
app/style/Documentation.less
app/style/LN.less

Adds an introduction in the form of a markdown document.
- Reuses the style of the LN introduction document.
- Also makes the introduction available from the main privacy tab through an "i" icon.
A wall of text is not a great solution to make mixing more accessible, but its definitely a step in the right direction (better than having nothing at all).
Closes #2880
Closes #2879

Add introduction to Privacy.

---

app/components/indicators/AnimatedLinearProgressFull.jsx

[startup] fix double messages when switching SPV on

---

app/components/views/GetStartedPage/hooks.js

Closes #2855
This update adds a more detailed error message with instructions when Decrediton tries to connect to a daemon, which uses the unsupported P-521 curve.

[Remote daemon] Improve error message

---

app/actions/ControlActions.js

This PR fixes the wrong change destination on privacy wallets

Fix wrong change destination

---

app/components/views/GovernancePage/Proposals/ProposalsList/ProposalsList.jsx

[Governance] Fix infinite scrolling on proposal lists

---

app/actions/TransactionActions.js
app/components/shared/TxHistory/LiveStakeTxRow.jsx
app/components/shared/TxHistory/TxHistory.jsx
app/components/views/TicketsPage/VSPTicketsStatusTab/Page.jsx
app/components/views/TicketsPage/VSPTicketsStatusTab/hooks.js
app/helpers/tickets.js

This PR has some multi fixes:
- closes #2894;
- closes #2868;
- Remove a log from helpers, which make the call to get tickets much slower if agenda not founded. Related to #2831
- Add a reference to vsp tickets so it also works on large screens

Improve my tickets view

---

app/components/SideBar/MenuBottom/MenuBottom.module.css
app/components/SideBar/MenuBottom/MenuBottomExpanded.jsx
app/components/views/GovernancePage/Proposals/ProposalsListItem/ProposalsListItem.jsx
app/i18n/po/decrediton.de.po
app/i18n/po/decrediton.es.po
app/i18n/po/decrediton.fr.po
app/i18n/po/decrediton.ja.po
app/i18n/po/decrediton.pt.po
app/i18n/po/decrediton.zh.po
app/i18n/pot/decrediton.pot
app/i18n/translations/original.json

- Remove mouse pointer from unclickable peers icon
- Add a space between the latest block label and value
- Fix caps on proposal "Last Updated". eg (`Last updated 2 minutes ago` rather than `Last updated 2 minutes ago`)

Minor UI fixes

---

app/actions/AccountMixerActions.js
app/actions/DaemonActions.js
app/actions/WalletLoaderActions.js
app/components/views/HelpPage/LogsTab/Page.jsx
app/components/views/PrivacyPage/Privacy/Privacy.jsx
app/components/views/PrivacyPage/Privacy/Privacy.module.css
app/components/views/PrivacyPage/Privacy/PrivacyContent.jsx
app/components/views/PrivacyPage/Privacy/hooks.js
app/main.development.js
app/main_dev/launch.js
app/main_dev/logging.js
app/wallet/daemon.js

This PR adds log to privacy page

Add log to privacy page

---

app/actions/ControlActions.js
app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_TicketAutoBuyer/Form.js
app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_TicketAutoBuyer/index.js
app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/hooks.js
app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/index.js
app/components/views/TicketsPage/PurchaseTab/TicketAutoBuyer/Form.jsx

Closes #2852 
Closes #2856
Also, I noticed that although the host was set up correctly, the legacy auto buyer did not start (and could not be stopped). It was because a part of the relevant v2 code has been deleted at some point. I restored it and wired up to the legacy auto buyer page.

Improve legacy autobuyer and the new autobuyer modal

---

app/main_dev/launch.js

This should resolve issues when decrediton is closed without having the opportunity to issue the close dcrlnd rpc request.

[launch] Close dcrlnd via pipe in win32

---

app/actions/TrezorActions.js
app/components/views/TrezorPage/ConfigSections.js
app/components/views/TrezorPage/FirmwareUpdate.js
app/connectors/trezor.js
app/main.development.js
app/main_dev/ipc.js
app/reducers/trezor.js
app/selectors.js

This reverts commit bf54bf8bfdf5214f6aa61a5fd121b50de2a95004.
This commit was causing build errors that were not easily fixed so 
we're revert until the cause can be tracked down and fixed.

Revert "TrezorActions: Allow updating firmware. (#2816)"

---

app/components/modals/AddMixerAccountsModal.jsx

[privacy] intl: add i18n to Mixer Accounts Modal placeholders

---

app/selectors.js

This diff fixes an issue with transfer fee tx showing wrong receiver account, as these txs may have multiple
outputs, this commit picks the account which corresponds to the first not change output.
---
Closes #2919

Fix: Transfer tx showing wrong receiver account

---

app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_AddForm.js
app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_Tickets.js

[VSP] show vsp tooltip on tickets `use Legacy` checkbox only if it is not checked

---

app/containers/App.js
app/index.js

fix: Required `autobuyerRunningModalVisible` warning in console

---

app/actions/AccountMixerActions.js

This PR updates accounts selectors, after first configuring the mixer.

update accounts selectors

---

app/actions/TransactionActions.js
app/reducers/grpc.js

fixes https://github.com/decred/decrediton/issues/2860 and fixes https://github.com/decred/decrediton/issues/2635

Update selectors when receiving new tx

---

app/actions/ClientActions.js
app/components/modals/CantCloseModals/CantCloseModals.jsx
app/components/modals/CantCloseModals/HasTicketFeeError.jsx
app/components/modals/CantCloseModals/hooks.js
app/components/modals/Modals.module.css

This PR adds a button for going to ticket status on the closing warning modal

Add button for going to ticket status

---

README.md

These shouldnt exist in the decrediton repo, they should be added to the `bin/` directory as per dcrd/dcrwallet

Remove LN binaries

---

app/selectors.js

fix: Handle tickets without `ticket` tx and fallback to `spender`

---

app/actions/AccountMixerActions.js
app/actions/ClientActions.js
app/actions/NotificationActions.js
app/constants/Decred.js
app/selectors.js

This PR stop the mixer if the unmixed account balance gets below the minimum relay Fee, which is 0.0001 dcr. 
closes #2892

Stop mixer after mixing

---

app/actions/GovernanceActions.js
app/components/views/GovernancePage/Proposals/ProposalsFilter/ProposalsFilter.jsx
app/components/views/GovernancePage/Proposals/ProposalsList/ProposalsList.jsx
app/components/views/GovernancePage/Proposals/hooks.js

Closes https://github.com/decred/decrediton/issues/2969.

Fix finished vote proposals filter

---

app/components/shared/TxHistory/RegularTxRow.jsx
app/components/shared/TxHistory/TxHistory.module.css

[RegularTxRow] Improve from/to accounts alignment

---

app/selectors.js

[governance] fix: remove duplicate agendas

---

app/components/shared/PrivacyForm/PrivacyForm.module.css
app/components/views/TicketsPage/PurchaseTab/PurchaseTab.module.css
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseForm.jsx
app/components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfo.module.css
app/style/PurchaseTickets.less

[Purchase Tickets] improve the responsiveness of ticket purchase view

---

app/components/views/PrivacyPage/Privacy/Privacy.module.css
app/components/views/PrivacyPage/Privacy/PrivacyContent.jsx

The error drawn outside of the white panel looks wrong, it seems detached from the rest of the form.

Move unmixed balance error up into panel.

---

app/components/shared/SendTransaction/SendTransaction.js
app/components/views/PrivacyPage/Privacy/PrivacyContent.jsx
app/components/views/PrivacyPage/Privacy/hooks.js

Mixer: filter out unmixed account from `from` dropdown

---

app/components/views/PrivacyPage/PrivacyPage.jsx
app/components/views/PrivacyPage/hooks.js
app/selectors.js

Mixer: header should use actual account names

---

app/components/shared/SendTransaction/SendTransaction.jsx
app/components/shared/SendTransaction/hooks.js

[transaction] clean tx info on unmount

---

app/components/views/GetStartedPage/hooks.js

While working on #2907 found that restoring mixed wallet doesn't work with SPV on, this diff fixes that.

[privacy] fix: Restore mixed wallet with SPV on

---

app/components/shared/SendTransaction/SendOutputRow/SendOutputRow.jsx
app/components/views/PrivacyPage/Privacy/SendForm.module.css

[Privacy] Add "Send all funds" button to the Privacy view

---

app/components/modals/SyncVSPFailedTickets.jsx

Fix cancel button on `Sync failed VSP tickets` modal 

---

app/components/views/GetStartedPage/GetStarted.module.css

[CSS] Improve style of release notes 

---

app/components/SideBar/MenuLinks/MenuLink/MenuLink.module.css
app/components/SideBar/MenuLinks/MenuLinks.jsx
app/components/SideBar/MenuLinks/hooks.js

Closes #3058
Closes #3055 
Hide caret on sidebar when Settings is selected and center icons

[Sidebar] Hide caret on the sidebar when settings is selected and center icons

---

app/actions/ClientActions.js
app/actions/ControlActions.js
app/components/buttons/index.js
app/components/modals/CantCloseModals/AccountMixerRunningModal.jsx
app/components/modals/CantCloseModals/AutobuyerRunningModal.jsx
app/components/modals/CantCloseModals/CantCloseModals.jsx
app/components/modals/CantCloseModals/HasTicketFeeError.jsx
app/components/modals/CantCloseModals/PurchasingTicketsModal.jsx
app/components/modals/CantCloseModals/hooks.js
app/components/modals/Modals.module.css
app/components/views/SettingsPage/SettingsPage.jsx
app/containers/App.js
app/hooks/useSettings.js
app/index.js
app/reducers/control.js
app/selectors.js

Add warning of ticket fee errors to close wallet action

---

app/components/SideBar/MenuBottom/MenuBottom.module.css
app/components/buttons/RescanButton/RescanButton.module.css

Tiny Sidebar css improvements

---

app/actions/TransactionActions.js
app/components/indicators/LoadingMoreTickets/LoadingMoreTickets.js
app/components/views/TicketsPage/VSPTicketsStatusTab/MyVSPTickets.jsx
app/components/views/TicketsPage/VSPTicketsStatusTab/Page.jsx
app/components/views/TicketsPage/VSPTicketsStatusTab/hooks.js
app/index.js
app/reducers/grpc.js
app/selectors.js

A work torwards #2831.
I am not closing it, as I still think we can do more improvements on it

Add search limit for live tickets

---

app/actions/TransactionActions.js

Fix vsp ticket showing as solo

---

app/package.json
app/yarn.lock

Connect was unable to locate the app directory. This has been corrected.

deps: Update connect.

---

app/actions/TransactionActions.js

Fix address not updating after receveing amount

---

app/actions/VSPActions.js

Show VSPs in random order in the select control

---

app/actions/ClientActions.js
app/components/shared/Subtitle/Subtitle.module.css
app/components/views/ListUtxo/ListUtxo.jsx
app/components/views/ListUtxo/ListUtxo.module.css
app/components/views/ListUtxo/hooks.js
app/components/views/TransactionsPage/SendTab/SendForm.module.css
app/components/views/TransactionsPage/SendTab/SendTab.js
app/containers/Wallet.js
app/wallet/service.js

This PR adds a list utxo view.
It can be accessed from send tab -> list utxo
And looks right now like this:

Add list utxo view

---

package.json
yarn.lock

Fixes a dependabot alert for node-notifier optional dep within jest.

update jest dep

---

app/components/views/GovernancePage/Proposals/ProposalsList/ProposalsList.jsx
app/components/views/GovernancePage/Proposals/hooks.js

[PI] fix never-ending `Enable PI Integration` loader

---

app/components/views/GetStartedPage/SetMixedAcctPage/SetMixedAcctPage.jsx
app/components/views/GetStartedPage/hooks.js

Fix cancel/discard button in Set Mixed Account Page

---

app/components/views/GetStartedPage/SetMixedAcctPage/SetMixedAcctPage.jsx
app/components/views/GetStartedPage/SetMixedAcctPage/SetMixedAcctPage.module.css

Use pi-ui's Checkbox instead of custom in `Set Mixed Account` page

---

app/components/views/GetStartedPage/SetMixedAcctPage/SetMixedAcctPage.jsx
app/components/views/GetStartedPage/hooks.js

Enable switching accounts in coinjoin account selection page

---

app/components/views/GetStartedPage/hooks.js
app/hooks/useDaemonStartup.js

This PR adds a check for showing process unmanaged tickets, instead of always showing it.

Add check for solo tickets, before showing process unmanaged tickets

---

app/components/views/GetStartedPage/hooks.js

This PR adds a check so we skip the process unmanaged tickets on legacy vsp tickets

Add input check before process unmanaged tickets

---

app/actions/TransactionActions.js

Closes https://github.com/decred/decrediton/issues/3146.

Fix out of order new transactions in history tx

---

app/components/views/TicketsPage/PurchaseTab/PurchaseTab.module.css
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/Page.jsx
app/components/views/TicketsPage/TicketsPage.jsx

[staking] fix title & private tickets section arrow direction

---

app/components/views/TicketsPage/VSPTicketsStatusTab/MyVSPTickets.jsx

Closes https://github.com/decred/decrediton/issues/3159.

Fix filters shared between Tickets tabs

---

app/components/buttons/ToggleSwitch/ToggleSwitch.module.css
app/components/shared/Subtitle/Subtitle.module.css
app/components/views/TransactionsPage/SendTab/SendForm.module.css
app/style/MyTickets.less
app/style/PurchaseTickets.less

[CSS] fix purchase tickets page misalignments

---

app/index.js

This PR adds a initial value to the ticket status for new vsp tickets

Add initial value to new vsp tickets filter

---

app/components/buttons/ModalButton.js
app/components/inputs/Input.js
app/components/inputs/LanguageSelectInput/LanguageSelectInput.jsx
app/components/inputs/PassphraseModalField.js
app/components/inputs/SettingsInput.js
app/components/modals/ChangePassphraseModal/ChangePassphraseModalContent.jsx
app/components/modals/PassphraseModal/PassphraseModalContent.jsx
app/components/views/SettingsPage/SettingsTab/MiscSettings.jsx
app/components/views/SettingsPage/SettingsTab/NetworkSettings.jsx
app/components/views/SettingsPage/SettingsTab/PrivacySettings.jsx
app/components/views/SettingsPage/SettingsTab/ProxySettings.jsx
app/components/views/SettingsPage/SettingsTab/UISettings.jsx
app/constants/config.js
test/unit/components/views/SettingsPage/SettingsPage.spec.js

This is the continuation of #2606. I focus this time on the `SettingsPage` component.

Settings: automated tests

---

app/components/shared/TabsHeader/TabsHeader.jsx
app/components/views/HomePage/HomePage.jsx
app/components/views/HomePage/HomePage.module.css
package.json
yarn.lock

Closes #3201
This diff fixes the flickering animation on the dashboard using https://github.com/decred/pi-ui/pull/322
~~Until it will be merged, I edited the package.json.~~ https://github.com/decred/pi-ui/pull/322 has been merged and I upgraded the pi-ui package

Fix tabs animation on the dashboard

---

app/components/views/TransactionsPage/ReceiveTab/ReceivePage/ReceivePage.module.css

Close https://github.com/decred/decrediton/issues/3226.
Before:
After:

Fix "Receive" page responsiveness

---

app/components/indicators/AnimatedLinearProgressFull.jsx

Fix color of loader bar

---

app/actions/VSPActions.js
app/components/inputs/VSPSelect/VSPSelect.js
app/components/inputs/VSPSelect/hooks.js
app/components/views/GetStartedPage/ProcessManagedTickets/ProcessManagedTickets.jsx
app/components/views/GetStartedPage/hooks.js
app/stateMachines/FetchStateMachine.js
app/stateMachines/GetStartedStateMachine.js

This PR adds a timeout when selecting new VSPs.

Add timeout check

---

app/components/views/TicketsPage/VSPTicketsStatusTab/MyVSPTickets.jsx
app/components/views/TicketsPage/VSPTicketsStatusTab/Page.jsx
app/components/views/TicketsPage/VSPTicketsStatusTab/hooks.js
app/reducers/snackbar.js
app/reducers/vsp.js

This will allow us to see loading on the button and show success message on request completion of Sync Failed Tickets

[tickets] Add reducers for SyncFailed action

---

app/actions/ClientActions.js
app/actions/VSPActions.js
app/components/views/GovernancePage/Blockchain/AgendaOverview/AgendaOverview.jsx
app/components/views/GovernancePage/Blockchain/AgendaOverview/Overview.jsx
app/components/views/GovernancePage/Blockchain/Blockchain.jsx
app/components/views/GovernancePage/Blockchain/Page.jsx
app/components/views/GovernancePage/Blockchain/hooks.js
app/index.js
app/middleware/api.proto
app/middleware/walletrpc/api_grpc_pb.js
app/middleware/walletrpc/api_pb.js
app/reducers/grpc.js
app/reducers/snackbar.js
app/reducers/vsp.js
app/selectors.js
app/wallet/control.js

~Requires https://github.com/decred/dcrwallet/pull/1981~
Close #3197 
Now on update vote preference the wallet is sent a SetVspdVoteChoice request for any currently available vspd.

[tickets] Add SetVspdVoteChoice request

---

app/selectors.js

Forgot to add a selector in the previous Syncing Failed tickets PR which was causing Ticket Status tab to crash on click

[stakinng] Add forgotten selector

---

app/actions/LNActions.js

This changes the connection logic to dcrlnd to perform multiple attempts after
unlocking the dcrlnd node. This might be needed due to dcrlnd stopping the
WalletUnlocker service and starting the Lightning service.

[LN] Attempt multiple connections

---

app/actions/TransactionActions.js

This PR fixes ticket showing as solo after purchase

Fix ticket showing as solo after purcahase

---

app/components/views/GovernancePage/Blockchain/AgendaOverview/Overview.jsx
app/i18n/po/decrediton.ar.po
app/i18n/po/decrediton.de.po
app/i18n/po/decrediton.es.po
app/i18n/po/decrediton.fr.po
app/i18n/po/decrediton.it.po
app/i18n/po/decrediton.ja.po
app/i18n/po/decrediton.pl.po
app/i18n/po/decrediton.pt.po
app/i18n/po/decrediton.zh-HK.po
app/i18n/po/decrediton.zh.po
app/i18n/pot/decrediton.pot
app/i18n/translations/original.json

[governance] fix wrong POW consensus change threshold value.

---

test/unit/components/inputs/DcrInput.spec.js

This diff refactors `DcrInput.spec.js` test file using hooks.
Part of #2438

Functional DcrInput test

---

app/components/SideBar/MenuBottom/MenuBottomExpanded.jsx

fix single peer count typo

---

app/style/ReleaseNotes.less

Delete empty ReleaseNotes.less file.

---

app/components/inputs/PassphraseModalField/PassphraseModalField.jsx
app/components/inputs/PassphraseModalField/PassphraseModalField.module.css

fix SyncFailedVSPTickets dropdowns

---

app/components/views/GovernancePage/Proposals/ProposalsFilter/ProposalsFilter.jsx

Remove tooltips from proposal filter buttons

---

app/components/views/GetStartedPage/GetStarted.module.css

Fix tooltips

---

app/components/views/HomePage/HomePage.module.css
app/components/views/HomePage/Tabs/BalanceTab/BalanceTab.jsx
app/components/views/HomePage/Tabs/BalanceTab/hooks.js
app/selectors.js

Reorganize overview balances

---

app/components/buttons/SendTransactionButton/SendTransactionButton.jsx
app/components/buttons/SendTransactionButton/hooks.js
app/components/modals/TrezorModals/TrezorPinModal.jsx
test/unit/components/buttons/SendTransactionButton.spec.js

Fixes sending tranzactions from trezor wallets and the warning on the trezor
pin modal.

[Trezor] Fix send button and modal

---

app/components/inputs/LanguageSelectInput/LanguageSelectInput.jsx

Closes #2438 - should go in after #3325.
Closes #2530.

Functional inputs/LanguageSelectInput.

---

package.json
webpack.config.development.js
webpack.config.production.js
yarn.lock

Based on #3325. See commit for specific changes: https://github.com/decred/decrediton/pull/3330/commits/413403841036b8a18861e222b4737b6b595d88f3.
Closes #2439.

Delete `less` related deps & update webpack loaders.

---

app/components/Snackbar/Snackbar.module.css
app/components/indicators/StepIndicator/StepIndicator.module.css
app/components/views/GetStartedPage/CreateWalletPage/CreateWallet.module.css
app/components/views/GetStartedPage/TutorialPage/Tutorial.module.css

[CSS] Fix various paddings

---

app/components/views/GetStartedPage/GetStarted.module.css
app/components/views/GetStartedPage/GetStartedPage.jsx
app/components/views/GetStartedPage/messages.jsx

[launch] Improve the style of update available button

---

app/actions/NotificationActions.js
app/actions/WalletLoaderActions.js
app/components/views/DexPage/CreateDexAcctPage/CreateDexAcctPage.jsx
app/components/views/DexPage/CreateWalletsPage/CreateWalletsPage.jsx
app/components/views/DexPage/CreateWalletsPage/CreateWalletsPage.module.css
app/components/views/DexPage/DexPage.jsx
app/components/views/DexPage/EnablePage/EnablePage.jsx
app/components/views/DexPage/InitPage/InitPage.jsx
app/components/views/DexPage/RegisterPage/RegisterPage.jsx
app/components/views/DexPage/RegisterPage/RegisterPage.module.css

This includes various DEX pages UI improvements.

[DEX] Polish pages UI.

---

app/components/buttons/EyeFilterMenu/EyeFilterMenu.module.css
app/components/shared/ButtonsToolbar.jsx
app/components/views/AccountsPage/Accounts/AccountRow/RenameAccount.jsx
app/components/views/AccountsPage/Accounts/Accounts.module.css
app/components/views/GetStartedPage/PreCreateWallet/CreateWalletForm/CreateWalletForm.jsx
app/components/views/GetStartedPage/PreCreateWallet/CreateWalletForm/CreateWalletForm.module.css
app/components/views/LNPage/ConnectPage/ConnectPage.jsx
app/components/views/LNPage/ConnectPage/ConnectPage.module.css
app/style/ReactSelectGlobal.css
app/style/themes/sharedTheme.js

fix css bugs

---

app/components/modals/SeedCopyConfirmModal/SeedCopyConfirmModalContent.jsx
app/components/views/GetStartedPage/CreateWalletPage/CopySeed/CopySeed.jsx
test/unit/components/views/GetStaredPage/CreateWallet.spec.js

Submit copy seed to clipboard with enter

---

app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/PurchasePage.jsx

Add legacy VSP toggle to empty state page.

---

app/package.json
go.mod
go.sum
package.json

Also includes dcrdex dep commit bump

Bump v1.6.3

---

app/components/buttons/AutoBuyerSwitch.jsx
app/components/buttons/ToggleSwitch/ToggleSwitch.jsx
app/components/shared/PurchaseTicketsForm/PurchaseTicketsForm.jsx
app/components/shared/PurchaseTicketsForm/PurchaseTicketsForm.module.css
app/components/shared/SendTransaction/Form.jsx
app/components/shared/TicketAutoBuyerForm/TicketAutoBuyerForm.jsx
app/components/shared/TicketAutoBuyerForm/TicketAutoBuyerForm.module.css
app/components/views/PrivacyPage/Privacy/Privacy.module.css
app/components/views/PrivacyPage/Privacy/PrivacyContent.jsx
app/components/views/PrivacyPage/Privacy/SendForm.module.css
app/components/views/TransactionsPage/SendTab/SendForm.module.css

Fix malformed tooltips

---

app/components/views/DexPage/RegisterPage/RegisterPage.jsx
app/components/views/DexPage/RegisterPage/RegisterPage.module.css
app/components/views/DexPage/RegisterPage/SendForm.module.css
app/components/views/DexPage/RegisterPage/SendOutputRow/SendAllFundsIcon/SendAllFundsIcon.jsx
app/components/views/DexPage/RegisterPage/SendOutputRow/SendAllFundsIcon/SendAllFundsIcon.module.css
app/components/views/DexPage/RegisterPage/SendOutputRow/SendAllFundsIcon/index.js
app/components/views/DexPage/RegisterPage/SendOutputRow/SendOutputRow.jsx
app/components/views/DexPage/RegisterPage/SendOutputRow/SendOutputRow.module.css
app/components/views/DexPage/RegisterPage/SendOutputRow/index.js
app/components/views/DexPage/RegisterPage/hooks.js
app/selectors.js

[dex] add send to Dex Account form to Dex Register page

---

app/components/views/GetStartedPage/CreateWalletPage/ExistingSeed/ExistingSeed.jsx
app/components/views/GetStartedPage/CreateWalletPage/ExistingSeed/Form/Form.jsx
test/unit/components/views/GetStaredPage/CreateWallet.spec.js

This allows restoring BIP0039 seeds.
Closes #3183

[getstarted] Allow hex seeds up to 128 chars

---

app/components/views/GetStartedPage/SetupWallet/hooks.js

I noticed when having coinjoin outputs, and no mixed account set on config, the screen turns blank, being not possible to leave it. 

fix coinjoin not showing

---

app/components/modals/SyncVSPFailedTickets/SyncVSPFailedTickets.jsx
app/components/views/TicketsPage/VSPTicketsStatusTab/MyVSPTickets.jsx
app/components/views/TicketsPage/VSPTicketsStatusTab/Page.jsx
app/components/views/TicketsPage/VSPTicketsStatusTab/hooks.js

Fills in the VSP if the preferred VSP is selected, also fixes the "Options not defined" error that was being shown.

[tickets] Fix Sync Failed Modal vsp dropdown

---

go.mod
go.sum
modules/dex/libdexc/adapter.go

Build libdexc with dcrdex v0.2.0-beta.
Also make `(*CoreAdapter).shutdown` wait for the webserver in addition to `Core`.

update dex to 0.2.0-rc1, wait for webserver shutdown

---

app/actions/ControlActions.js
app/hooks/useDaemonStartup.js
app/wallet/control.js

Also fixes an incorrect dispatched action type.

[locks] Remove unused processUnmanged

---

app/main.development.js

This PR fixes our dev command on windows, which is broken right now

fix windows dev

---

app/selectors.js

Fix saved balance to maintain zero value

---

app/components/shared/ExternalButton.jsx
app/components/shared/PoliteiaLink.jsx
app/components/shared/index.js
app/components/views/GovernancePage/Blockchain/Blockchain.jsx
app/components/views/GovernancePage/Blockchain/Blockchain.module.css
app/components/views/GovernancePage/Proposals/ProposalsTab.jsx

Fix `Go to Voting Dashboard` button

---

app/components/views/TransactionsPage/ExportTab/ExportPage/ExportPage.jsx
app/components/views/TransactionsPage/ExportTab/ExportPage/index.js
app/components/views/TransactionsPage/ExportTab/ExportTab.jsx
app/components/views/TransactionsPage/ExportTab/index.js
app/components/views/TransactionsPage/TransactionsPage.jsx
app/components/views/TransactionsPage/index.js
app/containers/Wallet/Wallet.jsx
test/unit/components/views/TransactionsPage/ExportTab/ExportTab.spec.js

This is the continuation of #3490. I've covered the ExportTab view:
- app/components/views/TransactionsPage/ExportTab/*
- app/components/views/TransactionsPage/ExportTab/ExportPage/*

Export tab: automated tests

---

app/components/views/GetStartedPage/SetupWallet/ProcessUnmanagedTickets/ProcessUnmanagedTickets.jsx
app/components/views/GetStartedPage/SetupWallet/hooks.js
app/components/views/TicketsPage/VSPTicketsStatusTab/hooks.js

Improve`VspSelect` input on `manage unprocessed tickets` view 

---

app/components/views/TransactionsPage/HistoryTab/HistoryPage/HistoryPage.module.css
app/components/views/TransactionsPage/HistoryTab/HistoryTab.jsx

Closes #3528
(Also fixed the cut-off tooltips of the filters)

[transactions] Fix history filters

---

app/actions/ClientActions.js
app/actions/TransactionActions.js
app/actions/VSPActions.js
app/actions/WalletLoaderActions.js
app/components/shared/TxHistory/LiveStakeTxRow.jsx
app/components/views/TicketsPage/VSPTicketsStatusTab/MyVSPTickets.jsx
app/constants/decrediton.js
app/index.js
app/middleware/api.proto
app/middleware/walletrpc/api_pb.js
app/wallet/control.js

Requires https://github.com/decred/dcrwallet/pull/2083
This adds the confirmed VSP ticket status and adds the requests for VSP tickets in that status.

vsp: Add confirmed status and fix processing

---

app/components/modals/ListUTXOsModal/ListUTXOsModal.jsx
app/components/modals/ListUTXOsModal/ListUTXOsModal.module.css

Make UTXO copyable on the `List Unspent UTXOs` modal

---

app/components/buttons/EyeFilterMenu/EyeFilterMenuWithSlider/EyeFilterMenuWithSlider.jsx

Fix Transactions History Range Filter

---

app/selectors.js

This fixes the tickets tab in the home page. The selector was using a function
that no longer applied.

[Home]: Fix Tickets Tab

---

app/components/views/HomePage/HomePage.jsx
app/components/views/HomePage/RecentTickets/index.js
app/components/views/HomePage/RecentTransactions/index.js
app/components/views/HomePage/Tabs/BalanceTab/index.js
app/components/views/HomePage/Tabs/TicketsTab/TicketsTab.jsx
app/components/views/HomePage/Tabs/TicketsTab/index.js
app/components/views/HomePage/Tabs/TransactionsTab/index.js
app/components/views/HomePage/Tabs/index.js
app/components/views/HomePage/hooks.js
app/components/views/HomePage/index.js
app/containers/Wallet/Wallet.jsx
test/unit/components/views/HomePage/HomePage.spec.js
test/unit/components/views/HomePage/mocks.js

This is the continuation of #3584. I've covered the views on Home Page.
Also closes #3531

Home Page: automated tests

---

app/components/layout/DescriptionHeader/DescriptionHeader.module.css
app/components/layout/StandaloneHeader/StandaloneHeader.module.css
app/components/layout/TabbedPage/TabbedPage.module.css
app/components/layout/TitleHeader/TitleHeader.module.css
app/components/views/GovernancePage/TabHeader/TabHeader.jsx
app/components/views/GovernancePage/TabHeader/TabHeader.module.css

Ensure the spacing between Title and Description is 5px, as specified in #3404. More detail in commit messages.

Fix header spacing on Governance tab

---

app/components/views/GovernancePage/GovernancePage.jsx
app/components/views/GovernancePage/Proposals/ProposalsList/ProposalsList.jsx
app/components/views/GovernancePage/Proposals/ProposalsListItem/ProposalsListItem.jsx
app/components/views/GovernancePage/Proposals/ProposalsTab.jsx
app/components/views/GovernancePage/Proposals/hooks.js
app/main.development.js
app/staticPages/confirmation-dialog.html
app/style/themes/darkTheme.js

Closes #3628
Closes #3625
Although I could not reproduce #3623, I've improved the confirmation dialog by removing the white border and applying dynamic height:

Multi: fixes dark mode related issues

---

app/components/views/GovernancePage/Proposals/hooks.js

Fix `In Discussion` tab

---

app/components/views/GovernancePage/Proposals/ProposalsTab.jsx

[governance] Fix create proposal link

---

app/actions/DexActions.js
app/components/views/DexPage/LoginPage/LoginPage.jsx

This fixes a 'flash' that occurred when opening up the Dex Window. 
Also fix the login button showing a 'loading' animation when connecting to the Dex

[dex] Remove extra user call and fix login button

---

app/selectors.js

[governance] Fix current agendas being shown

---

app/components/views/PrivacyPage/PrivacyTab/PrivacyContent.jsx
app/components/views/PrivacyPage/PrivacyTab/PrivacyTab.jsx
app/components/views/PrivacyPage/PrivacyTab/hooks.js

[privacy] Indicate when auto-buyer is running

---

app/main.development.js

First attempt at fixing some of the issues mentioned in #3657 and #3658

[dex] Improve dex window functionality

---

app/actions/VSPActions.js
app/reducers/vsp.js
app/selectors.js
test/unit/actions/VSPActions.spec.js

Fetch `vspinfo` async

---

app/wallet/control.js

[tickets] Set minimum ticketbuyer limit

---

app/actions/ClientActions.js
app/middleware/dcrdataapi.js

[governance] Add the new treasury balance

---

app/components/Snackbar/Notification/Message.jsx
app/components/Snackbar/Snackbar.module.css

[css] Fix overlapping copy/dismiss buttons on toast notification

---

package.json
yarn.lock

This updates to the latest version of electron.

[deps] Update to electron v17.0.0

---

app/components/SideBar/MenuLinks/hooks.js

[sidebar] refresh menu links after toggling SPV mode

---

app/components/buttons/ImportScriptIconButton/ImportScriptIconButton.jsx
app/components/modals/ImportScriptModal/ImportScriptModal.module.css
app/components/views/SettingsPage/GeneralSettingsTab/MiscSettings/MiscSettings.jsx
test/unit/components/views/SettingsPage/SettingsPage.spec.js

[tickets] Re-add Import Script button to Settings page

---

app/components/views/LNPage/ConnectPage/CreationWarning/CreationWarning.jsx

Fix typo in LN initial screen

---

app/components/views/TransactionPage/TransactionContent/TransactionContent.jsx
app/components/views/TransactionPage/TransactionContent/TransactionContent.module.css
app/components/views/TransactionPage/TransactionPage.jsx
app/components/views/TransactionPage/hooks.js
app/helpers/tickets.js
test/unit/components/views/TransactionPage/TransactionPage.spec.js
test/unit/components/views/TransactionPage/mocks.js
test/unit/helpers/tickets.spec.js

[vsp] Add vote choices to vote transaction details

---

app/actions/DaemonActions.js
app/actions/WalletLoaderActions.js
app/components/views/TicketsPage/StakingTabWarning/StakingTabWarning.jsx
app/components/views/TicketsPage/StakingTabWarning/StakingTabWarning.module.css
app/components/views/TicketsPage/StakingTabWarning/hooks.js
app/components/views/TicketsPage/StakingTabWarning/index.js
app/components/views/TicketsPage/TicketsPage.jsx
app/components/views/TicketsPage/hooks.js
app/constants/config.js
app/index.js
app/reducers/walletLoader.js
app/selectors.js
test/unit/components/TicketsPage/PurchaseTab/PurchasePage.spec.js
test/unit/components/TicketsPage/PurchaseTab/TicketsPage.spec.js
test/unit/components/TicketsPage/PurchaseTab/mocks.js

[ux] Add staking tab warning

---

app/actions/DaemonActions.js
app/actions/DexActions.js
app/components/views/DexPage/hooks.js
app/constants/config.js
app/reducers/walletLoader.js
app/selectors.js

This should smooth out the working flow and make loading up the Dex window faster.

[dex] Skip Login once Dex Launched

---

app/components/views/GetStartedPage/SetupWallet/hooks.js
app/stateMachines/GetStartedStateMachine.js

This diff is a direct continuation of #3579 and takes care of the restored wallets too.

[setupWallet] Set the new per-account encryption automatically for the restored wallet

---

app/components/views/TicketsPage/VSPTicketsStatusTab/Page.jsx
test/unit/components/views/TicketsPage/MyVSPTickets/MyVSPTicketsTab.spec.js

[tickets] fix the never disappearing `loading more tickets` issue

---

app/components/views/TicketsPage/MyTicketsTab/hooks.js

User in support channel reported the button not working after 1.7.2

[tickets] Fix Ticket History QR Code button

---

app/main_dev/launch.js

Remove magics in favor of constants to current mixing server.

[launcher] Use cspp constants

---

app/components/modals/DocumentationInfoModal/DocumentationInfoModal.module.css
app/components/modals/InfoModal/InfoModal.module.css
app/components/views/PrivacyPage/PrivacyTab/PrivacyContent.jsx
app/i18n/docs/en/Warnings/MixerIntroduction.md

Close #3766
After taking a look, not sure I like the multiple columns or the "justify" alignment in any circumstance.
Also changed to use Stakeshuffle++ in favor of the plain "Coin Mixer"

[style] Fix info modal columns and justification

---

app/components/layout/TabbedPage/TabbedPage.module.css

[css] Fix tabs scrolling when UI animations are disabled

---

app/i18n/translations/pt.json

translation: ptbr typo

---

app/components/views/TransactionsPage/HistoryTab/HistoryPage/HistoryPage.jsx
app/components/views/TransactionsPage/HistoryTab/HistoryPage/HistoryPage.module.css

This pr fix the problem in this [issue](https://github.com/decred/decrediton/issues/3773), and recomended by this [conversation](https://github.com/decred/pi-ui/pull/452#pullrequestreview-993973404)

transactions: fix placeholder size in textinput

---

app/main.development.js

This adds the ability to refresh the DEX window with the F5 key. 
Tested on Linux and Mac.

[dex] Refresh DEX window with F5 key

---

README.md
app/main.development.js

Closes https://github.com/decred/decrediton/issues/3824

docs: document devtools installer + logs

---

app/main_dev/ipc.js

[dex] Fix not launching Dex Window after Reload UI

---

app/components/SideBar/MenuLinks/MenuLinks.jsx
app/components/SideBar/SideBar.jsx
app/components/SideBar/SideBar.module.css
app/components/indicators/RescanProgress/RescanProgress.jsx
app/components/indicators/RescanProgress/RescanProgress.module.css
app/components/views/GetStartedPage/Settings/Settings.module.css
app/components/views/ProposalDetailsPage/ProposalDetails.jsx
app/components/views/ProposalDetailsPage/ProposalDetails.module.css
test/unit/components/SideBar/Sidebar.spec.js

- fix sidebar border color in dark mode. before/after:
- fix the "See proposal comments on Politeia" button's padding on smaller screens. The button was also not visible on smaller screens if the text is long.
- fix the hidden rescan progress bar on smaller screens (or when the sidebar is collapsed
- fix padding on "get started" Settings view:

[css] fix minor css issues

---

app/components/buttons/DocButton.jsx
app/components/buttons/index.js
app/components/layout/StandaloneHeader/StandaloneHeader.jsx
app/components/layout/TitleHeader/TitleHeader.jsx
app/components/layout/TitleHeader/TitleHeader.module.css
app/components/shared/Subtitle/Subtitle.jsx
app/components/shared/Subtitle/Subtitle.module.css
app/components/views/AccountsPage/AccountsPage.jsx
app/components/views/GetStartedPage/LanguageSelectPage/Page/Page.jsx
app/components/views/GetStartedPage/LanguageSelectPage/Page/Page.module.css
app/components/views/GetStartedPage/PreCreateWallet/CreateWalletForm/CreateWalletForm.jsx
app/components/views/GetStartedPage/PreCreateWallet/CreateWalletForm/CreateWalletForm.module.css
app/components/views/GovernancePage/GovernancePage.jsx
app/components/views/PrivacyPage/PrivacyPage.jsx
app/components/views/SettingsPage/SettingsPage.jsx
app/components/views/TicketsPage/MyTicketsTab/Page.jsx
app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/Page.jsx
app/components/views/TicketsPage/StatisticsTab/StatisticsTab.jsx
app/components/views/TicketsPage/VSPTicketsStatusTab/Page.jsx
app/components/views/TransactionsPage/ExportTab/ExportPage/ExportPage.jsx
app/components/views/TransactionsPage/HistoryTab/HistoryPage/HistoryPage.jsx
app/components/views/TransactionsPage/ReceiveTab/ReceivePage/ReceivePage.jsx
app/components/views/TransactionsPage/SendTab/SendTab.jsx

Closes #2008
Example screenshots:

Add links to helpful topics in the documentation

---

app/components/views/LNPage/ChannelDetailsPage/ChannelDetails.jsx
app/components/views/LNPage/ChannelsTab/ChannelsTab.jsx
app/components/views/LNPage/OverviewTab/OverviewTab.jsx
test/unit/components/views/LNPage/ChannelDetailsTab.spec.js

[LN] Enable to close inactive channels

---

package.json

Fix prettify on windows

---

app/components/modals/TrezorModals/TrezorWordModal.jsx

Fix losing focus between words issue on the trezor word modal

---

app/components/shared/SendTransaction/SendTransaction.jsx
test/unit/components/views/TransactionsPage/SendTab/SendTab.spec.js

Use debounce to fix the send form

---

modules/dex/libdexc/adapter.go

dex: add missing client/asset/eth import

---

app/components/modals/MixerSettingsModal/MixerSettingsModal.module.css

[css nit] Fix button text misalignment on Mixer Settings

---

app/package.json

Capitalize Decrediton

---

webpack/trezor.js

Trezor: Fix webpack build.

---

.github/workflows/nodejs.yml
package.json
yarn.lock

This should fix another vulnerability and fixes an issue when building on mac

deps: Upgrade electron-builder
