- .eslintrc.js
- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/actions/LoginActions.js
- app/actions/NotificationActions.js
- app/actions/SeedServiceActions.js
- app/actions/WalletLoaderActions.js
- app/components/Header.js
- app/components/History.js
- app/components/Home.js
- app/components/Receive.js
- app/components/Send.js
- app/config.js
- app/containers/App.js
- app/containers/CreateWalletForm.js
- app/containers/HomePage.js
- app/containers/LoaderForm.js
- app/containers/LoginForm.js
- app/containers/WalletExistForm.js
- app/containers/WalletOpenForm.js
- app/index.js
- app/main.development.js
- app/middleware/grpc/client.js
- app/middleware/grpc/control.js
- app/middleware/grpc/loader.js
- app/middleware/grpc/seeder.js
- app/routes.js
Allow console statements in .eslintrc.  We can always remove this
later on.
This includes many automatic fixes, a corrected variable name caught
by the linter, and removing unneeded requires from various files.
Closes #73
> Address more lint issues.

- app/actions/ClientActions.js
- app/components/History.js
- app/components/Send.js
- app/containers/HistoryPage.js
- app/helpers/byteActions.js
- app/index.js
- app/middleware/grpc/client.js
- app/reducers/grpc.js
For now we can just display the block height, timestamp and txid of the transactions due to limitations with the current GetTransactions gRPC.  In the coming weeks we can add all the information we'd like dcrwallet to provide to remove any major smarts or logic in decrediton and have dcrwallet do most of the heavy lifting.
Closes #100
> Rough first pass to display getTransactions

- app/components/Balance.js
If balance is zero (as with a fresh wallet), the display formatting is
broken due to an uninitialized value causing the home screen to not
load properly.
Closes #152
> Fix display when balance is zero.

- app/main.development.js
When in production (packaged mode) add --debug option to show dcrd and
dcrwallet output and info to stdout.  Otherwise there will be no
output to stdout.
The logs data is available in the app specific log files even without
the debug flag.
The behavior should be the same on OSX when started from a terminal
and Linux.
Closes #138
> Add debug mode to production.

- app/actions/ClientActions.js
- app/actions/WalletLoaderActions.js
- app/components/Balance.js
- app/components/GetStarted.js
- app/containers/GetStartedPage.js
- app/index.js
- app/reducers/walletLoader.js
Due to various constraints on paths of communication, we currently can't easily determine what the progress on a daemon/wallet block syncness is.
To give users some sort of feedback, we've decided to calculate a rough block height that a daemon "should be at" given the current date.  So, for example, on testnet:  It's been roughly 350 days since the chain started.  With block time set in the dcrd params we can roughly expect 720 blocks mined each day on testnet.  Then we multiple by 95% to accomodate for a bit of variance.  So the current "neededBlocks" value is 239864 which is just under our current height of ~242000.
Obviously this is not ideal, but should be a good replacement in the meantime until we have another option.
Fixes #109
> Give user some feedback for daemon syncing

- app/main.development.js
On macOS they were closed automatically but not cleanly.  This tells
both to shutdown cleanly on macOS and other OSes.
Only done in production mode.
Closes #135
> Make sure dcrd and dcrwallet shutdown when app closes.

- README.md
- app/main.development.js
- app/middleware/grpc/client.js
Previously, on linux, some things went in ~/.config/decrediton, others
wnet in ~/.decrediton.  Switch to always using ~/.config/decrediton/.
macOS was already using a single directory.
Correct wallet data location on windows.
Closes #61
> Use single directory for saved items.

- README.md
Add notes for extra package needed on fedora.
Move install to the top since most people will need that rather than
building instructions.
Mention glide in packaging section.
Some minor formatting fixes.
Closes #136
> Improve the documentation.

- app/actions/WalletLoaderActions.js
- app/components/GetStarted.js
- app/config.js
This is a little refinement for #162.  If they have a bad RPC username/password, port, etc it's not really clear what they would need to do to fix it so inform the user of the path to the config so they can edit it.
> print config path in error

- README.md
Since electron support went into grpc we no longer need
to use a special branch or build instructions.
Until there is a new GRPC release local building is still necessary.
Closes #170
> Simplify grpc build instructions.

- README.md
- app/actions/WalletLoaderActions.js
- app/config.js
- app/main.development.js
- app/middleware/grpc/client.js
- app/middleware/grpc/loader.js
- app/middleware/grpc/seeder.js
- app/middleware/grpc/version.js
Need to construct the path for Windows rather than using env variables
the way were we doing it before.
Move all functions that need path and config info to a single file,
config.js.
Detached should be false, esp for windows.
Don't use fd 4 that doesn't seem to work on win with wallet.
Closes #122
> Fixed for Windows.

- app/actions/WalletLoaderActions.js
- app/index.js
- app/middleware/api.proto
- app/middleware/regen.sh
- app/middleware/walletrpc/api_pb.js
With new FetchHeadersResponse fields we can now just compare MainChainTipBlockHeight with what we calculated to be "neededBlocks" 
Also added the regen.sh script to update *pb.js files when api.proto changes
Fixes #165
> Update grpc bindings for updated FetchHeaders response

- app/main.development.js
- package.json
If either process fails to start (in production mode only of course)
let the user know then stop (since there is no way to continue from
there).
Only shutdown processes that are currently running.
Closes #108
> Handle dcrd or dcrwallet startup errors.

- app/actions/ClientActions.js
- app/actions/WalletLoaderActions.js
- app/components/GetStarted.js
- app/components/History.js
- app/components/TxHistory.js
- app/containers/HistoryPage.js
- app/index.js
- app/middleware/grpc/client.js
- app/reducers/grpc.js
- app/reducers/walletLoader.js
Previously, only mined transactions were handled from the getTransactions rpc and they were all appended to the transactions state array. Now unmined and mined are dealt with in a relatively smart way (checking if they already exist and don't add if so).  This should set up decrediton to allow for pagination in a coming PR as well
> Add logic for mined and unmined transactions

- app/components/Receive.js
- package.json
Uses a pure js qr generating package (qr-image).
Closes #188
> Add qr code to receive page.

- app/components/Send.js
- app/containers/ConstructTxForm.js
Display units in send summary.
Closes #189
> Use DCR as units on Send page instead of atoms.

- app/actions/WalletLoaderActions.js
- app/components/CreateWalletForm.js
Due to user confusion, we'll just be removing the public passphrase on wallet creation which has dcrwallet use the default 'public' passphrase instead.  Now on wallet open it will attempt to use that public passphrase first and if that fails it will ask the user for a proper password
> Rig to remove public password on wallet creation for now

- app/main.development.js
On win7 we had to avoid the fd 4 pipe for wallet.
win10 appears to need the same thing for dcrd (fd 3).
> Do not use pipe for dcrd.

- app/main.development.js
- app/package.json
An error is now show if an undefined argument is used.
This adds a dependency on minimist.
Closes #253
> Improve cmd line parsing.

- app/config.js
- app/main.development.js
This fixes an issue where decrediton can get stuck reading the config
from both places leaving a weird, mixed config that does not work.
Remove some redundant package imports in config while there.
Closes #273
> Use same cfg path in dev and production.

- app/actions/SettingsActions.js
- app/actions/WalletLoaderActions.js
- app/config.js
- app/index.js
> Carry over settings from past instances

- app/actions/ClientActions.js
- app/actions/StakePoolActions.js
- app/components/MenuLink.js
- app/components/SideBar.js
- app/components/views/StakePool.js
- app/components/views/StakePoolPage.js
- app/config.js
- app/index.js
- app/middleware/stakepoolapi.js
- app/reducers/index.js
- app/reducers/stakepool.js
- app/routes.js
- package.json
To allow for communications between decrediton and various stakepools' apis, 
we added functionality for users to be able to set their APIKey given out by the 
pools.  Once that APIKey has been confirmed that corresponding users' purchase 
Information is polled. If the user has not yet provided a pubkey address then one
is created from an address from the default account.  Since there is currently no
method of adding accounts, the default account is set automatically.  When the
functionality for adding accounts is added, that dropdown will also be added to 
the stakepool configuration page.
Close #267
> Integrate Stakepools' API

- README.md
It's very hard to find where to download the binaries if you come from Google directly.
> Clarify where to download Decretion in the README

- app/actions/ClientActions.js
- app/actions/NotificationActions.js
- app/components/views/History.js
- app/components/views/Home.js
- app/components/views/HomePage.js
WIth the current method of querying for transaction history on decrediton bringup and no noticeable issue with memory, these fixes allow easy pagination with minamal redux state changes. 
If/when we update the getTransaction rpc we can do another round of optimization.  Results are unclear on huge wallets with thousands and thousands of transactions.  But for general/everyday usage this should suffice for the time being.
Closes #233
> Final audit/fixing of currently transaction history/pagination

- app/config.js
- app/main.development.js
- package.json
To help debugging, config files are written for dcrd and dcrwallet and
then the binaries are call using those config files when run in
production mode.
A config file for dcrctl is created as well to allow interaction with
the daemon if needed for debugging or other purposes.
Closes #198
> Write config files for cmd line tools

- app/actions/WalletLoaderActions.js
Since private passphrase is only needed for discovery of new accounts, it is not required between starts.
> Only ask for private passphrase on startup for newly created wallets

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/actions/WalletLoaderActions.js
- app/components/views/StakePool.js
- app/components/views/StakePoolPage.js
- app/index.js
- app/middleware/grpc/client.js
- app/reducers/control.js
- app/reducers/grpc.js
Takes care of the first part of #268
> Add basic autobuyer start/stop

- README.md
- package.json
npm seems to mean something different by compatible with than I do so
just specify the version that we are using.  Also list the correct
version in the README.md
Closes #345
> Force specific version of electron

- app/main.development.js
When changing modes (testnet vs. mainnet) the daemons may sometimes
start before the config files are written causing them to use
incorrect values.  This commit makes the startup of each cli program
wait until after we have written the config files.  This also fixes a
cases where a totally fresh install will try to start before ANY cli
config file has been written.
There may be more ordering/waiting issues during initial bringup, but
this is a significant improvement over the previous behavior.
Closes #357
> Make startup more async friendly

- README.md
- app/config.js
Move dcrd rpc and dcrwallet grpc servers to non-standard ports
similar to what Paymetheus does (but different ports).
Closes #390
> Use non-standard ports.

- README.md
- build-docker.sh
This makes the docker build run the linter and fails if the linter
fails.  This will also catch compile errors.  It is necessary for
using this in a CI system, but also generally useful.
Added the ability to specify a github id to build from (to build a
fork).
Add some doc in the README.md for the docker build.
Closes #392
> Add checks, options, and docs to docker builds.

- Dockerfile
- build-docker.sh
Post docker image to docker repo and use that
rather than building each time.
Move grpc build into the docker image so it is
only done once.
The docker image will be moved to a decred repo in a future commit.
Closes #399
> Speed up docker builds.

- app/main.development.js
Allow dev tools in production mode (but default to off).  Move to
advanced menu.  Remove reload from menu since it was only in dev mode,
never worked, and should never be needed.
Closes #415
> Make menu items more consistant between prod and dev mode.

- app/config.js
- app/main.development.js
Closes #417 
This commit is on top of #416 (for the change in menu name) although it can easily be rebased on master if we don't won't #416.
> Add menu item to open log files.

- app/components/CreateWalletForm.js
Previously, if decodeSeedError was ever non-null it would then set it to null, when it is updated.  The createWalletButton was checking for decodeSeedError !== '' instead of null.
Fixes #431
> Set the seedError check to be !== null

- build-docker.sh
This was causing a failure with the latest version of travis.
Closes #460
> Don't try to set permissions with rsync in build script.

- app/config.js
- app/index.js
This does not add any options in the GUI to change the host, it is
just the first step in adding support for running dcrd on a seperate
(and hopefully faster) machine that way Paymetheus does it.  It also
removes hardcoded value from a few places.
Closes #476
> Add config file support for running cli tools on seperate hosts.

- app/config.js
Depending on when calling it is possible for process.env.HOME to fail
(return undefined) so switch to os.homedir() which should work at all
times in app lifecycle.
Closes #490
> Switch from process.env.HOME to os.homedir()

- app/actions/ControlActions.js
- app/actions/StakePoolActions.js
- app/components/views/StakePool.js
- app/components/views/ViewStyles.js
- Added instructions for better clarity about how to enter/set up your stakepool with decrediton. 
- Added import script check when apikey is entered to avoid situations where the stakepool account is not associated with the current wallet.  Now to link a stakepool via apikey it MUST be for that wallet.  This is also the reason for the private pass request when adding the stakepool.
> Update stakepool apikey entry

- app/actions/ControlActions.js
- app/actions/NotificationActions.js
- app/components/Header.js
Will be sticking with material-ui Snackbar implementation for now until a better/more flexible solution can be developed.  Ideally we can add an onClick that would go to the transaction details page and also the ability to 'stack' notifications.  Currently it just shows one then disappears.
> Update styling on incoming transaction notifications

- app/main.development.js
This changes the logfile timestamps from the format `2017-08-01T15:16:29.794Z` (in GMT) to `2017-08-01 13:00:38.199` (local time), which matches the format used by dcrd and dcrwallet log files.
> Change timestamp for winston logs to match dcrd and dcrwallet logs

- app/components/GoToAccountsButton.js
- app/components/views/Receive.js
- app/components/views/Send.js
- app/components/views/StakePool.js
- app/components/views/ViewStyles.js
- app/style/MiscComponents.less
Now all wallet icons next to account dropdowns will go to accounts page for better ease of use.
Closes #551
> Add working go to accounts buttons

- app/config.js
- app/main.development.js
If JSON validation fails for `config.json`, the `electron-config` library silently fails and overwrites the file with default values. We shouldn't punish the user for making a minor mistake like this, so I've added validation before the file is initially fetched. I've also changed the implementation of `getCfgPath` because simply creating a new instance from the `electron-config` library will cause the config file to be overwritten.
An error dialog will be shown if JSON validation fails and the app will exit:
> Add JSON validation of config file on startup

- app/middleware/grpc/client.js
I've been seeing the "Failed to connect before deadline" error when starting Decrediton on Windows because it's having issues connecting to dcrwallet after it first launches the process. Here are the relevant logs:
`decrediton.log`:
2017-09-13 19:36:51.220 - info: launching dcrwallet at {}
`dcrwallet.log`:
2017-09-13 19:36:59.528 [INF] DCRW: gRPC server listening on 127.0.0.1:9121
2017-09-13 19:36:59.552 [INF] RPCS: Listening on 127.0.0.1:9110
On my machine it's taking about 8 seconds for dcrwallet to start listening, so I've increased all the deadlines to connect to 30 seconds.
> Increase all gRPC deadlines to 30 seconds.

- app/components/VotingPrefs/Page.js
Fixes an issue on the vote settings screen where selecting an agenda card to show the overview didn't hide the card:
> Fix bug where agenda overview and card are displayed at the same time

- app/main.development.js
- app/version/version.html
- app/version/version.js
Fixes first part of #669.
During development, Decrediton version will **not** show up correctly because of [issue 7085 of electron package](https://github.com/electron/electron/issues/7085).
> Read version from binaries and display in about window

- app/style/AgendaCard.less
Fixes #696 
Both .agenda-card-indicator-pending and .agenda-card-bottom-cfg had margin-bottom set to 20px, causing an overlap.  I updated the .agenda-card-indicator-cfg to have a margin-bottom of 55px.
> fixed overlapping divs in AgendaCard

- app/main.development.js
- package.json
- webpack.config.base.js
Previously the pathing for the win32ipc was incorrect and resulted in absolute paths of the build machine being used which caused the installed versions of decrediton not to be able to locate the required `.node` file.  
I forked https://github.com/ushu/node-addon-loader and added a special case path to look in the `resources/` path relative to the executable.  This with the additional extraResources file inclusion should make builds always work on windows.
> Add specialized loader to include native node add-ons

- app/actions/ClientActions.js
- app/actions/NotificationActions.js
- app/reducers/grpc.js
Previously there was an issue with the way in which get transaction's streamed progress was being handled by the actions.  If you don't do a shallow copy with `var array = arrayToCopy.slice()`  and just do `var array = arrayToCopy`  all changes to that `array` will be made to the redux state of `arrayToCopy` as well. 
This removes all that anyways and just accumulates the get transaction data stream then commits that to state upon GETTRANSACTIONS_COMPLETE signal.
Also add a check to return if getTransactionsRequestAttempt is true (which basically means) there is an existing request being processed.
Fixes #689
> Fix race in getTransactions and clean up

- app/actions/StakePoolActions.js
- app/selectors.js
- app/wallet/service.js
- app/wallet/stakePool.js
Splits RPC communication to wallet/
> Refactor StakePoolActions

- app/components/views/TicketsPage/index.js
Issue #755 - componentDidMount() is not called when this component is first viewed by a user. That's where ReactToolTip is usually initialized and built. Here we explicitly call it in componentDidUpdate() and place a check to prevent unnecessary rebuilds since this is a high-volume method (one that is called frequently).
> tooltip rebuild needed in componentDidUpdate()

- app/selectors.js
I erroneously got the revoke notification when loading decrediton on a machine that hadn't connected in a while, the notification went away once the wallet was synced.
This change requires that the wallet be synced before hasTicketsToRevoke can be true.
> Only show revoke ticket notification when wallet is synced

- app/components/shared/Tooltip.js
- app/components/shared/index.js
- app/components/views/AccountsPage/Accounts/AccountRow/Row.js
- app/components/views/AccountsPage/Accounts/AccountRow/index.js
- app/style/Tooltip.less
- webpack.config.base.js
I reworked the tooltip, pulled it out of the other PR, and implemented it using less class declarations in app/styles/Tooltip.less
I also applied it in one location as a PoC
I picked a location that allows us to remove a react-tooltip rebuild, allowing us to remove a state container altogether.
> Adds Tooltip w/ no external library dependencies

- app/actions/StakePoolActions.js
- app/actions/WalletLoaderActions.js
- app/components/StakePools/index.js
- app/config.js
- app/connectors/stakePools.js
- app/index.js
- app/middleware/stakepoolapi.js
- app/reducers/stakepool.js
Fix #801.
There was a possibility for the list of stakepools to not be correctly loaded on the first run after an install, also fixed in this PR.
> Fix StakePool cleared bug

- .babelrc
Babel is not needed for the api headers compiled by protoc.
This shaves a few seconds off decrediton's initialization during development.
> Ignore grpc api headers on babel

- app/components/Snackbar/Notification/Transaction.js
- app/reducers/snackbar.js
- app/style/Snackbar.less
Also, the publish transaction success message has been removed entirely from the snackbar, since it seems redundant to show that success and the received transaction notification.
> Re-enable unmined transaction notifications

- app/components/views/TicketsPage/MyTicketsTab/TicketListPage.js
- app/selectors.js
Fix #884 
This is a quick fix for the case of a purchased ticket that does not pay back into the wallet.
> Fix ticket price on non-wallet ticket

- app/components/views/TicketsPage/MyTicketsTab/TicketListPage.js
https://github.com/decred/decrediton/commit/538b9dbab4c48e7bc67f10262bfd09b10eebf01b had a small typo that prevented the spender transaction from being decoded.
> Fix decoding of spender ticket transaction

- package.json
- yarn.lock
electron-builder was broken for macOS High Sierra, this bumps that version and fixes some new errors as a result of that update.
> Update electron-builder and some other tweaks

- app/connectors/send.js
- app/selectors.js
The fix to estimated fees is especially strange.  On master, when you have "atoms" currency display selected and an output of 1 atom transaction entered it will show 25300.000000000004 for estimated fees.  With the extra parenthesis it appears to not cause the slight float accuracy oddity.
> Fix observed issues with unit and fees

- app/main.development.js
Fix #859 
Due to ctrl-q or issuing a Quit request from the dock on macOs windows are closed immediately and we need to ensure that the daemon and wallet are requested for shutdown before-quit.
> Add additional cleanShutdown request in before-quit for mac shutdown

- app/components/SideBar/MenuLinks/index.js
- app/components/TxHistoryRow/index.js
- app/routes.js
With the changes to MenuLinks, transaction details crashes due to having no corresponding activeLink to use.  This mostly fixes that issue and changes the selected menu to Transactions, but it doesn't highlight the link, because it isn't the "active" route.
> Fix issue with transaction details and new menu links

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/index.js
- app/reducers/grpc.js
- app/selectors.js
- app/style/Loading.less
Fix #961 
The transactions for the overview listing are now stored on a separate state and updated after the wallet is loaded, after rescan is completed or when new transactions are received.
> Fix overview transaction listing

- app/components/buttons/EyeFilterMenu/index.js
- app/components/views/TransactionsPage/HistoryTab/Page.js
- app/components/views/TransactionsPage/HistoryTab/index.js
- app/style/MiscComponents.less
Fix #996.
I think we need some way of showing the selected filter without the user needing to hover the mouse over the icon or open the dropdown menu, but that should be checked by the designers...
> Add check mark to selected tx filter

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/reducers/grpc.js
Fix #993 
This adds a call to update the tickets list on:
- Rescan Complete
- StakeInfo change (when any of the user's stats changes)
This also loads unmined tickets (weren't being loaded before) and changes the reducer so that tickets are only updated after successfully completing the `getTickets` call.
This is not the perfect solution to #993 as reloading the whole ticket tx set every time is not ideal performance-wise, but should be sufficient until we implement real ticket streaming.
I tested on a testnet wallet with over 2k ticket transactions (among tickets/votes/revokes) and performance was acceptable on my machine. Could use some testing on a bigger wallet.
> Update MyTickets ticket list

- app/components/views/HomePage/Page.js
Due to false positive notifications of needing to revoke, we've decided to remove the "Revoke tickets ..." div on the overview.  The revoke button will still appear on the Purchase Tickets page when hasTicketsToRevoke is true.  We'll be figuring out better ways of letting decrediton know that it needs to revoke tickets.
> Remove revoke div from Overview

- app/package.json
- app/yarn.lock
Due to an error in electron/asar below, some windows users have encountered this issue.  Until the underlying issue is resolved we will roll back to a known working version.
Fixes #995
> Rollback electron-store version and conf version

- app/main.development.js
- package.json
Fix #1025.
I believe the point of `yarn start` is to simulate a production run on a development machine, so I added a `customBinPath` command line arg to pass the fix the problem and added `--debug` to help check out any errors.
I also modified the logging of the launchXXXX functions to show the path to the executable being run.
Tested in development and on a packaged version on Linux.
> Add customBinPath cmdline arg

- app/actions/WalletLoaderActions.js
- app/logging.js
- app/main.development.js
- app/wallet/app.js
Fix #541 
Log format generated by the main logger now follows the dcrd/dcrwallet convention. Currently, it is using a single fixed subsystem (DCTN = DeCrediToN) as we don't have many logging messages.
This also moves all logging init logic into a separate file to improve readability.
It also adds the ability to send log messages to the main logger from the react app, by adding a `wallet.log()` function. These log messages will be persisted to the decrediton.log file, so we can start to add logging throughout the app to improve debugging.
> Change log format to dcrd/dcrwallet

- app/components/views/TransactionsPage/HistoryTab/Page.js
- app/components/views/TransactionsPage/HistoryTab/index.js
- app/connectors/historyPage.js
Fix #1044 
The new threshold is empirically defined (meaning: in a hacky way), but I think it should suffice for now.
Tested with a window height up to 1280 px.
I didn't hook to the window.resize listener, so the only outstanding possible bug is if the window is resized while the transaction list is opened (currently the user can just go to another page and come back and it will list correctly). If you think that is a relevant thing to fix, let me know and I'll work on a further fix.
> Change tx scroll threshold on large height

- app/config.js
Fix #1026 
This prevents stakepools that are not currently returned from the decred api (due to timeout between api and stakepool or any other reason) from being removed from the users config.
This also opens up the possibility of manually configured stakepools by editing config.json and adding the necessary stakepool fields.
> Prevent stakepools getting removed when not returned from api

- app/actions/StakePoolActions.js
- app/components/buttons/DangerButton.js
- app/components/buttons/index.js
- app/components/modals/ConfirmModal/index.js
- app/components/modals/index.js
- app/components/views/TicketsPage/GovernanceTab/index.js
- app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/index.js
- app/components/views/TicketsPage/PurchaseTab/StakePools/List.js
- app/components/views/TicketsPage/PurchaseTab/StakePools/index.js
- app/components/views/TicketsPage/PurchaseTab/index.js
- app/connectors/stakePools.js
- app/connectors/ticketsPage.js
- app/connectors/votingPrefs.js
- app/index.js
- app/reducers/snackbar.js
- app/reducers/stakepool.js
- app/selectors.js
- app/style/MiscComponents.less
- app/style/Modals.less
Fix #1058 
This adds the following changes:
- Move selected stakepool into global state so it is maintained between tab/page changes
- Add a remove stakepool button into the the stakepool list
- Add a DangerButton to be used in remove operations
- Add ConfirmModal to be used in operations that need confirmation but not necessarily the passphrase
Only thing I'm not 100% sure is if I need to dispatch a rescan after removing a stakepool from the configured ones.
> Maintain selected stakepool state and remove stakepool

- app/components/views/TransactionsPage/SendTab/index.js
Fix #1055 
This changes to only reconstruct the output tx when `parseFloat(newValue) !== parseFloat(oldValue)`, which handles the invalid string case and also cases of irrelevant zeros (3.0 === 3.0000000 === 0003.000 === 3.)
> Construct output tx only on float value change

- app/middleware/grpc/client.js
- app/wallet/loader.js
- app/wallet/seed.js
Small refactoring to unify all get*Service functions into a single builder function.
Only ones slightly different were the `loader()` and `seeder()` functions, which were fixed to the correct function signature.
This is meant mainly to reduce code duplication.
> Refactor grpc getService functions

- app/components/views/GetStartedPage/DaemonLoading/Form.js
- app/components/views/GetStartedPage/Logs/Form.js
- app/components/views/GetStartedPage/Logs/Header.js
- app/components/views/GetStartedPage/Logs/index.js
- app/components/views/GetStartedPage/Page.js
- app/components/views/GetStartedPage/index.js
- app/components/views/HelpPage/LogsTab/Page.js
- app/connectors/logging.js
- app/style/GetStarted.less
Fix #1049 
Besides during blockchain downloading, I also added the log button on daemon loading (before starting the blockchain download) as that seems to be the step most people get stuck.
Let me know if you think it should be added to more places.
> Add log viewing to GetStarted stage

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/actions/NotificationActions.js
Fixes #574 
Now instead of blindly requesting information about all accounts, we only update the account referred to in the transaction or account notification streams. 
I believe more work can be done on streamlining the storing of account information, plus I'm not positive that it's currently Immutable.  
Seems to be making extraneous account update calls, but otherwise appears to be working as expected.
> Clean up account individual updating

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/actions/NotificationActions.js
Further streamlining of new block connecting.  Now we should only request stake info updates when we receive a new stake transaction (ticket, vote, revoke).  This is especially important since StakeInfo is a very expensive request for dcrwallet to process.
> Change to only request stakeInfo when new stake transactions are noticed

- .gitignore
- app/main.development.js
- package.json
- yarn.lock
Fix #1051 
I tried to update to the 1.8.x release line, but got some undebugable white error screen (electron didn't load the app, didn't throw an exception or gave me anything to indicate where it had errored), so I pulled back to the latest release of the 1.7.x (non-beta) line.
I tested the general functions (seed input, transactions, ticket purchase, simple and advanced mode) on the following platforms:
- Linux (development version with `yarn dev`)
- Linux (locally packaged version with `yarn package`)
- Windows (development version with `yarn dev`)
- Windows (locally packaged version with `yarn package`)
Don't have a macOS computer to test, so could use some help there if available.
I had to delete the `node_modules` and `app/node_modules` and execute `yarn` to rebuild the correct …
> Update electron to 1.7.10

- app/actions/ClientActions.js
- app/actions/ControlActions.js
To avoid certain calls being called multiple times, this cleans up the startup actions.  
When there are no new headers, then there is no need to rescan the chain.  Then these calls are explicitly done.  Otherwise if a rescan is required we do the same startup action calls (stakeinfo, gettransactions, ticketinfo, account balances) on that success as well.
> Fix startup actions call procedures

- app/actions/DaemonActions.js
- app/components/views/GetStartedPage/StartRPC.js
NeededBlocks was not being checked whether it was greater than 0, so it was bypassing the daemon syncing check.  This also exposed an incorrect component being imported for ShowErrors on the StartRPC screen.
> Fixes for startup crashing

- app/components/buttons/index.js
- app/style/MiscComponents.less
Renamed "purchase-tickets-info-button" to "info-modal-button". That name made more sense.
Added some margin to the left. I found it too close to the on the left hand side. 
Before
After
> Renamed "purchase-tickets-info-button" and added some margin

- package.json
- scripts/aliasDefaultMessage.js
- scripts/prepareUntranslated.js
Running eslint gives:
```
.../decrediton/scripts/aliasDefaultMessage.js
13:5   error  Expected indentation of 2 spaces but found 4    indent
13:5   error  Strings must use doublequote                    quotes
16:35  error  Strings must use doublequote                    quotes
20:5   error  Expected indentation of 2 spaces but found 4    indent
21:9   error  Expected indentation of 6 spaces but found 8    indent
22:13  error  Expected indentation of 10 spaces but found 12  Vindent
25:9   error  Expected indentation of 6 spaces but found 8    indent
28:5   error  Expected indentation of 2 spaces but found 4    indent
29:9   error  Expected indentation of 6 spaces but found 8    indent
29:41  error  Strings must use doublequote                    quotes
32:5   error  Expected indentation …
```
> Fix misc lint errors

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/components/views/GetStartedPage/RescanWallet/Form.js
- app/components/views/GetStartedPage/RescanWallet/index.js
- app/components/views/GetStartedPage/index.js
- app/connectors/walletStartup.js
- app/reducers/snackbar.js
- app/reducers/walletLoader.js
- app/wallet/daemon.js
Fix #1089 
This moves the initial rescan and wallet info gathering (balances & latest transactions) to the GetStarted stage. This way, the main wallet UI is only shown after all needed data is already on the state, preventing flashes of zero or a mutating balance.
This commit accomplishes this by:
- Promisifying a few wallet startup actions
- Unifying the logic for the different branches of wallet info gathering (brand new wallet from seed, existing wallet from seed, existing wallet with no new block headers, existing wallet with new block headers available) into the `getStartupWalletInfo` action
- Modifying the startup logic to wait for the balances before requesting the transactions (as it is needed)
- Modifying the GetStarted stages to add a rescan step (triggered as needed) before …
> Move initial rescan to GetStarted stage

- package.json
- yarn.lock
https://electronjs.org/blog/protocol-handler-fix
Appears that the vulnerability doesn't effect us, but better bump to be sure.
> Bump electron version due to critical security fix.

- app/wallet/daemon.js
Fixes small string parsing bug introduced on #1100, when the `get-block-count` returns an error.
> Fix for get-block-count error

- app/components/views/TxDetails.js
Fix #1103 
Besides votes, this also changes the txdetail page to show the account name on received transactions.
> Show account name in votes and received txs

- app/actions/ControlActions.js
- app/wallet/app.js
- app/wallet/client.js
- app/wallet/config.js
- app/wallet/daemon.js
- app/wallet/loader.js
- app/wallet/message.js
- app/wallet/notifications.js
- app/wallet/service.js
- app/wallet/stakePool.js
- app/wallet/version.js
Part of #1042 
This adds logging to all wallet actions. I tried to track down and omit private information leaking (such as balance amounts, transaction data, etc) but it should be double checked to see if I missed any.
I also added logging to the `purchaseTicketAttempt`, due to the recent #1084 issue, but before adding more logging we should see if the action refactors (#907 & future PRs) will continue, as it is easier to add logging to the normalized wallet functions rather then on each react action.
Also didn't add logging to config yet as there is work being done on that to refactor it for multiple wallet support.
> Add logging to all wallet methods

- app/components/inputs/DcrInput.js
- app/components/inputs/FloatInput.js
- app/components/inputs/Input.js
- app/components/inputs/IntegerInput.js
- app/components/inputs/index.js
- app/components/views/TicketsPage/PurchaseTab/TicketAutoBuyer/Details.js
- app/components/views/TransactionsPage/SendTab/OutputAccountRow.js
- app/components/views/TransactionsPage/SendTab/OutputRow.js
- app/components/views/TransactionsPage/SendTab/index.js
- app/connectors/balance.js
- app/helpers/strings.js
Fix #1110 
This changes the `DcrInput` component to manage the input amount in atoms instead of as string, implementing rounding for floating values following the same procedure as dcrd/dcrwallet (https://github.com/decred/dcrd/blob/v1.1.2/dcrutil/amount.go#L77).
It also adds `FloatInput`, `IntegerInput` (behave as expected) and `FixedDcrInput` (which behaves as the old `DcrInput`, meant for inputs that are *always* assumed to be in DCR amounts).
> Switch DcrInput to atoms

- app/components/modals/SeedCopyConfirmModal/Modal.js
- app/components/views/AccountsPage/Accounts/AccountRow/RenameAccount.js
- app/components/views/AccountsPage/Accounts/AccountRow/index.js
Fix #1127 
The rename account input was also broken.
I checked all `<\w+Input` components and all of them (except the rename account and the seed input) were using the `onChange={...}/value={...}` style for storing the inputs, ao only those two got broken.
> Fix seed and rename account inputs

- app/actions/DaemonActions.js
- app/actions/WalletLoaderActions.js
- app/components/views/GetStartedPage/FetchBlockHeaders/Form.js
- app/components/views/GetStartedPage/Page.js
- app/components/views/GetStartedPage/index.js
- app/connectors/walletStartup.js
- app/reducers/walletLoader.js
- app/selectors.js
Due to the upcoming onboarding/get started changes, it is required that wallet is loaded before the daemon is attempted to load.  
This offers a much more intuitive onboarding flow, so users can do all of the wallet creation prior to spinning up the daemon.  In a future PR we can parallelize the process as well, so the daemon can be syncing in the background while the user creates the wallet.
> [getstarted] Load wallet before daemon

- .travis.yml
- package.json
This adds a yarn script to generate binaries for linux, without generating the .rpm and .deb packages.
I'm mainly using this to generate the development binaries for periodic testing.
> Add development binary linux target

- .eslintrc.js
- app/helpers/strings.js
We should try to activate default eslint rules.
The dot operator doesn't need to be escaped inside brackets.
For reference see
https://stackoverflow.com/questions/10397968/escape-dot-in-a-regex-range
https://stackoverflow.com/questions/19976018/does-a-dot-have-to-be-escaped-in-a-character-class-square-brackets-of-a-regula
or directly https://www.regular-expressions.info/refcharclass.html
> Activate Eslint Rule no-useless-escape

- package.json
With the added stylelint command to "lint" the --fix was only getting added to the stylelint command with `npm run lint -- --fix`
> Update lint-fix to properly fix lint issues

- app/style/MiscComponents.less
Fix mouse hover on macOS. Similar as #1038 and #436.
> Add cursor pointer to rescan-button and rescan-cancel-button

- app/components/views/HomePage/RecentTransactions.js
- app/components/views/HomePage/TicketActivity.js
- app/connectors/home.js
- app/index.js
- app/selectors.js
This is a first pass at properly displaying stake transactions on the overview.  
We are currently reusing TxHistory for these as well, but we should probably do a new TxHistoryRow based on TicketCards from the MyTicketsTab.  That change will also require usage of the normalizedTickets.
> Populate Recent Tickets for Overview

- app/actions/DaemonActions.js
- app/config.js
- app/main.development.js
- app/reducers/grpc.js
- app/wallet/daemon.js
Fix #852 
This opens up the possibility of running multiple wallet instances at the same time (not yet implemented).
On non-windows platforms, the `--rpclistenerevents --pipetx` dcrwallet arguments are used to pipe the events from the wallet daemon into decrediton. The grpc port is found when the appropriate IPC message is received.
On windows, due to various node/golang incompatibilities it's not possible to do that, so for the moment we resort to parsing the stdout output, looking for the appropriate log string. This is an ugly hack, so hopefully, we can have a better IPC mechanism on windows in the future.
Tested on linux and windows (needs testing on macOS).
To test this on an existing configured wallet, you'll need to edit the corresponding `dcrwallet.conf` (usually …
> Support dynamic dcrwallet port

- app/index.js
- app/package.json
- app/yarn.lock
- package.json
- yarn.lock
Fix #1096 
Updates the grpc to latest version (which removes the argue.js dependency) and also adds the eval() prevention check on `app/index.js`.
> Bump grpc package version

- app/actions/StatisticsActions.js
- app/components/charts/ChartTooltip.js
- app/components/shared/Balance.js
- app/selectors.js
- app/style/MiscComponents.less
Fixes three small bugs related to recent refactors:
- Returns the spin animation to the rescan button
- Prevents hover bug on charts on empty wallets
- Prevents hover bug on charts on an errored wallet (I had a wallet with a vote but not the related ticket, which was causing a BSOD; a rescan fixes the issue, but I couldn't easily trigger the rescan due to the BSOD).
> Overview stats bugs

- app/components/indicators/LinearProgressFull.js
- app/components/views/GetStartedPage/DaemonLoading/Form.js
- app/components/views/GetStartedPage/OpenWallet/DecryptForm.js
- app/components/views/GetStartedPage/OpenWallet/index.js
- app/components/views/GetStartedPage/index.js
- app/style/GetStarted.less
This PR is an attempt to offer more clear information about what decrediton is doing for the loading.  It removes most text out of the loading bar except for Waiting/Loading/Synced Blockchain text.  All other states or information about it is doing is now located next to the loading icon upper right of the loading bar.
> [launcher] Remove unnecessary text and move to wallet loading area

- app/actions/DaemonActions.js
- app/components/views/GetStartedPage/index.js
- app/config.js
- app/index.js
- app/main.development.js
- app/reducers/daemon.js
- app/wallet/daemon.js
This switches the previous wallet to be saved as a var on main.development instead of a config. This enables running multiple wallets simultaneously, connecting to the same daemon (when running in advanced daemon mode).
Last step to supporting multiple concurrent wallets is managing a single dcrd instance when not running in advanced daemon mode.
> Store previousWallet as var instead of config

- app/components/modals/PassphraseModal/ButtonsToolbar.js
- app/components/modals/SeedCopyConfirmModal/Modal.js
- app/style/Modals.less
Closes #1217 
Now all cancel buttons should be InvivisbleButtons.  The pair of cancel/confirm should always be on the right and in that order.
> Update modal buttons to use consistent styling and right justification

- app/actions/DaemonActions.js
- app/actions/WalletLoaderActions.js
- app/components/indicators/LoaderBarBottom.js
- app/components/views/GetStartedPage/CreateWallet/CreateForm.js
- app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ContinueWalletCreation.js
- app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/CreateWallet.js
- app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/index.js
- app/components/views/GetStartedPage/CreateWallet/ExistingOrNewScreen.js
- app/components/views/GetStartedPage/DaemonLoading/Form.js
- app/components/views/GetStartedPage/WalletSelection/CreateWalletForm.js
- app/components/views/GetStartedPage/WalletSelection/index.js
- app/components/views/GetStartedPage/index.js
- app/config.js
- app/connectors/walletStartup.js
- app/index.js
- app/main.development.js
- app/reducers/daemon.js
- app/style/GetStarted.less
- app/wallet/daemon.js
This PR is an attempt to have the UX be more like what @linnutee had suggested in the docks.  Which network that the wallet will be using will be determined by the config instead of chosen on startup.  This now allows us to auto-load the daemon (if not in advanced mode) so the user can have the daemon syncing while they create/select their wallet.
> [launcher] Remove network toggle and autoload daemon

- app/style/GetStarted.less
Fixes #1258
With margin-bottom removed:
> Remove bottom margin

- app/components/views/GetStartedPage/Logs/Form.js
- app/style/GetStarted.less
I'm uncertain if the div and class code are placed correctly but this is at least an example of how #1260 can be solved.
> Closes #1260. Add container to prevent overlapping scroll

- app/components/layout/TabbedPage.js
- app/style/Layout.less
- app/style/main.less
Fix #1189 
Due to various limitations, the simplest way (least amount of changes to overall app structure) to fix this was to add an overlay over the scrollbar during tab switching, which gets shown after the tab is fully in view.
> Dynamic scrollbar

- app/components/SideBar/MenuLinks/index.js
- app/components/views/HelpPage/index.js
- app/components/views/SecurityPage/index.js
- app/components/views/TicketsPage/index.js
- app/components/views/TransactionsPage/index.js
Previously, whenever you went to a tab that wasn't first (or specifically the one in the links path) it grey out the active menu link
> Fix for menulinks not being highlighted

- app/package.json
- app/yarn.lock
- package.json
- yarn.lock
Due to a notified critical vulnerability https://nvd.nist.gov/vuln/detail/CVE-2018-1000118  we have updated electron to 1.8.2-beta.5
> Update electron due to security vulnerability

- app/actions/DaemonActions.js
- app/config.js
- app/main.development.js
- app/wallet/daemon.js
Fix #1293 
dcrd does not create a conf file if a conf file is specified in the options (which we do for decrediton).  So we now just create a temp dcrd.conf in appdataDirectory to be used until the user places (or generates) a config file in the default dcrd location.
> Create temp dcrd.conf if none is found in expected location

- app/components/views/HomePage/tables/NoTicketsLinks.js
- app/components/views/TutorialsPage/Staking/index.js
- app/components/views/TutorialsPage/TicketLifecycle/index.js
- app/style/Tutorial.less
I've also hidden the "purchase tickets" tutorial that was listed on the original tutorial design, since we don't have copy and images for it.
> Update tutorial copy and styles

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/index.js
Found this while leaving decrediton open for a long time, then trying to purchase a ticket. Since we moved away from requesting the accounts balances on every block, the block height of `getAccountsResponse` would get outdated. 
This switches the remaining instances of where `getAccountsResponse` was being used to grab the block height to the `grpc.currentBlockHeight` state var.
> Remove references to getAccountsResponse.getCurrentBlockCount

- app/main.development.js
Due to constant user confusion and reports, we will now enable immediate ticket purchasing for auto buyer.  This should be totally fine with only a slight bump in fees for the first block of a down ticket price window.
> [config] Add nospreadticketpurchases option for wallet  start up

- app/components/views/TicketsPage/GovernanceTab/AgendaCard.js
- app/components/views/TicketsPage/GovernanceTab/AgendaOverview/Overview.js
- app/style/AgendaOverview.less
Due to various reasons, we currently don't have a graceful way of notifying dcrwallet (and thereby decrediton) of an agenda's state at any given moment.  Until that solution is in place, we will simply show the user that the agenda voting has finished and passed.
I will be opening an issue describing various solutions that can be implemented in the future.
> [tickets] Set all currently shown agendas to finished

- app/actions/ClientActions.js
- app/actions/NotificationActions.js
- app/components/views/AccountsPage/Accounts/AccountRow/AccountDetails.js
- app/index.js
- app/reducers/daemon.js
- app/reducers/grpc.js
Fix #1320 
This also fixes small bugs related to account hiding:
- Tooltip was reversed ("show" vs "hide")
- The wrong state was being updated on account hiding (grpc vs daemon) so multiple updates weren't being correctly processed
- Small refactoring of the code to make it less cluttered
> Fix account creation and hiding

- app/style/ReactSelectGlobal.less
This is a slight tweak of the css for the accounts select, to avoid breaking lines when there is an account with a big name.
> Fix accounts select style when account name is big

- app/main.development.js
I had the extraneous `config.json` on my wallets dir as well, but I couldn't track why it was there. I tested several combinations of the migration code, but couldn't reproduce the creation of the config.json file inside ~/.config/decrediton/wallets. Maybe this was happening on a development test or an earlier version?
Anyway, I simplified the code that lists available wallets a bit and added a check to only list if it's a dir.
> Ignore non-dirs when listing available wallets

- app/components/views/GetStartedPage/DaemonLoading/Form.js
- app/components/views/GetStartedPage/StartRPC.js
- app/components/views/GetStartedPage/index.js
- app/main.development.js
- app/style/GetStarted.less
- app/wallet/daemon.js
Fix #1333 
This shows the last log lines of dcrd and dcrwallet during the "Stablishing RPC Connections..." stage of startup. This is the stage where migrations in the daemon/wallet databases happen, so it should be slightly clearer for users what is going on.
> Show last log lines while starting RPC

- app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ExistingSeed/Form.js
- app/style/CreateWalletForm.less
Close #1339 
Way to replicate error: C-V any bad words into any box in the restore seed area.  Previously, it would make the seed words disappear, now it determines whether a valid 33 mnenomic seed so it will display correctly.
> Capture invalid seed pasting and display error

- app/style/GetStarted.less
On restore wallet from seed when the button turns disabled and loading, on hover it would remove the button's box-shadow.  This was due to the special wallet creation button style that overrides the disabled button style.  
This is a quick fix until we can do a full overhaul to make buttons consistent everywhere.
> [launcher] Fix disabled Restore Wallet button box shadow

- .travis.yml
- package.json
- yarn.lock
You'll need to blow away app/node_modules to rebuild grpc bindings with `yarn`
> Update electron to v2.0.0

- app/components/views/HelpPage/LogsTab/Page.js
- app/components/views/HelpPage/LogsTab/index.js
Close #1350 
This uses roughly the same pattern from the showing of the last log lines on StartRPC.js.  When the LogsTabBody mounts it will periodically update the value of the state of dcrdLogs and dcrwalletLogs.  When it unmounts it will no longer request these updates.
> Update dcrd and wallet logs automatically

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/main_dev/templates.js
To avoid users having to manually click the button to rebroadcast, I've added a check on startup to see if there are any unmined then issue publishUnminedTransactions if so.
Also includes a small lint-fix that was merged to master.
> Call publishUnminedTransactions on startup

- app/main.development.js
- package.json
- yarn.lock
Required after the bump to electron 2 to install the react/redux dev tools.
> Update devtools installer

- app/actions/WalletLoaderActions.js
There was a slight change in wording (wallet already loaded --> wallet already opened), which made it not catch the error properly on reload.
> Fix error message check for already opened wallet

- app/reducers/daemon.js
- app/reducers/walletLoader.js
- app/selectors.js
Noticed yesterday when working on the import script fix.
Steps to reproduce problem: 
- Create new wallet. Name it.
- On the initial seed page, close the app.
- Reopen app. Continue wallet creation.
- Can't get past the "existing or new" screen.
> Fix continue with wallet creation

- .travis.yml
- app/style/Tutorial.less
Close #1413 
This also includes a reverting of the node version in travis due to it starting to have issues with a Buffer() deprecation in some dependency.
> Styling fixes to tutorial

- app/actions/StatisticsActions.js
- app/helpers/byteActions.js
- app/index.js
- app/middleware/api.proto
- app/middleware/walletrpc/api_grpc_pb.js
- app/middleware/walletrpc/api_pb.js
- app/wallet/service.js
This switches the startup statistics calculation to happen backwards (from current balance back to -15 days) instead of forwards from the start of the wallet.
This speeds up startup time for wallets with a large number of transactions, as we now only need to obtain transactions up to about 15 days in the past.
The trickiest things to make this work is accounting for immature balances and ticket amounts (when calculating forwards, we can also count on having the ticket before the vote, so when going backwards we need to be able to grab individual ticket data given the vote tx).
I had to update the grpc api to the latest one from dcrwallet because I needed the block hash on the `GetTransaction` call.
One way to verify that the balances are correct is the following: export the normal …
> Calculate startup stats backwards

- app/components/SideBar/MenuLinks/index.js
- app/components/layout/TabbedPage.js
- app/components/shared/RoutedTabsHeader.js
- app/components/shared/StaticSwitch.js
- app/components/shared/TransitionMotionWrapper.js
- app/components/shared/index.js
- app/config.js
- app/connectors/index.js
- app/connectors/theming.js
- app/containers/App.js
- app/containers/Wallet.js
- app/index.js
- app/selectors.js
This adds a config option (`ui_animations`) and implements the appropriate behavior to disable animations/transitions/motions when requested.
This is meant as an attempt to track down some recent bugs reported, that might be related to the animations being slow on older machines.
The option is currently not exported on the UI, since for the moment it is meant as a last resort alternative in older machines.
> Add config option to disable animations

- app/actions/ClientActions.js
- app/actions/DaemonActions.js
- app/config.js
- app/index.js
- app/reducers/grpc.js
- app/selectors.js
fixes #911 
I removed the cleanShutdown method from before-quit, because it calls for the second time, which gives a connection error when trying to get the block height.
Is there a reason for cleanShutdown being called there?
I am just adding these recent transactions to the selector, we still need to show it in a component.
> Show transactions received while away

- app/components/Snackbar/index.js
- app/style/Snackbar.less
- package.json
- yarn.lock
Fix #1428 
Part of #1406 
This removes the use of the material-ui snackbar in favor a custom built one. Pretty much the only thing that was needed was moving the event listeners into the snackbar component and fixing the styling.
This also adds an event listener to prevent the snackbar message from disappearing when the user has the mouse hovering over the snackbar (useful for maintaining longer messages visible).
The added dependencies aren't really new: they are just stuff material-ui used that have been moved into the component.
> Remove material ui from snackbar

- app/components/indicators/LinearProgressSmall.js
- app/components/indicators/RescanProgress.js
- app/components/views/GetStartedPage/RescanWallet/Form.js
- app/style/GetStarted.less
- app/style/Loading.less
- app/style/MiscComponents.less
Part of #1406 
This replaces all remaining linear progresses from the material-ui library to our custom one.
> Replace material-ui linear progress

- app/actions/StatisticsActions.js
- app/connectors/myTicketsCharts.js
- app/index.js
- app/reducers/statistics.js
- app/selectors.js
Fix #1456 
This reverts the stake reward statistics to use the forward-calculating daily balances.
> [charts] use forward daily balances to calculate stake rewards

- app/actions/ClientActions.js
This fixes a potential race condition that happens during startup when the wallet has airdropped coins (coins in ledger of the block with height == 1) and not many more transactions after that.
This was preventing users from accessing the app.
> Fix transaction listing when wallet has airdrop coins

- app/main_dev/launch.js
Fix #1467 
Location for the win32ipc node module was wrong after all the main_dev refactorings, causing the module not to be loaded.
> Fix win32ipc node location

- app/actions/VersionActions.js
- app/actions/WalletLoaderActions.js
- app/components/views/GetStartedPage/CreateWallet/CreateForm.js
- app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ConfirmSeed/index.js
- app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/ExistingSeed/index.js
- app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/index.js
- app/connectors/createWallet.js
- app/connectors/walletStartup.js
- app/middleware/grpc/client.js
- app/reducers/snackbar.js
- app/reducers/walletLoader.js
- app/style/CreateWalletForm.less
- app/wallet/seed.js
- app/wallet/service.js
Fix #1466 
This also refactors the seed service functions so that it follows the same conventions as the other service functions (getting rid of an error message in the process) and also makes it so that when creating a watching only wallet, the user is not presented with the ExistingOrNew screen (as that is superfluous for that particular wallet creation branch).
> [launcher] fix initial wallet creation

- app/actions/ClientActions.js
- app/wallet/constants.js
Fix #1337 
This switches the getAccountsBalances function to correctly use `Promises.all` and only dispatch the event after all balances have been received.
> Improve getAccountsBalances function

- app/config.js
This particular fix is for the case when `~/.dcrd/dcrd.conf` is **not** present. If that file existed, this error wasn't triggered.
> [launcher] fix ui reload on non-advanced mode

- app/actions/ControlActions.js
- app/actions/StakePoolActions.js
- app/components/buttons/index.js
- app/components/inputs/StakePoolSelect.js
- app/components/views/GetStartedPage/StakePools/Form.js
- app/components/views/TicketsPage/PurchaseTab/StakePools/AddForm.js
- app/components/views/TicketsPage/PurchaseTab/StakePools/List.js
- app/connectors/index.js
- app/connectors/newStakePool.js
- app/index.js
- app/main_dev/externalRequests.js
- app/middleware/stakepoolapi.js
- app/reducers/snackbar.js
- app/reducers/stakepool.js
- app/selectors.js
- app/style/Modals.less
- app/wallet/stakePool.js
Close #1464 
Adds the ability to add a custom stakepool by typing its address in the stakepool select drop down, and selecting and option to add that stakepool.
Before adding the stakepool, a request is made to its `/api/v1/stats` endpoint, to check if it exists and get its available api versions. Only then is the stakepool added to the supported list.
Easiest way to test it is probably to run a local webserver (eg: via `php -S` or python simplewebserver) that returns a fixed json with the required fields (eg: copy from an existing stakepool).
> [stakepools] allow adding custom stakepool

- app/package.json
- app/yarn.lock
Close #1485 
Fix #1387 
The main tell for the #1387 bug is the log line
```
2018-05-14 14:00:22.920 [INF] GRPC: Server.Serve failed to complete security handshake from "127.0.0.1:52936": EOF
```
It seems that the old grpc libs have some compatibility problems on the new fedoras. The new version fixes it.
Tested on: fedora 26, 28 and windows.
> [dependencies] update grpc

- app/style/HistoryPage.less
- app/style/TxHistory.less
- Pending transactions were causing slightly smaller rows on overview
- Pending indicator was overlapping with other pending in a row beneath.
- Tx History page was showing a row off to the right next to the title area.
> [history] Fix a couple styling issues with tx history on Overview and History pages

- app/components/buttons/WatchOnlyWalletSwitch.js
- app/components/views/GetStartedPage/CreateWallet/CreateForm.js
- app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/CreateWallet.js
- app/components/views/GetStartedPage/WalletSelection/CreateWalletForm.js
- app/components/views/GetStartedPage/WalletSelection/Form.js
- app/index.js
- app/reducers/walletLoader.js
- app/style/GetStarted.less
- app/style/Global.less
- app/style/LanguageSelect.less
- app/style/StakePool.less
Partially completes #1476 
This mostly completes the design/flow of wallet creation.  I have removed the intermediate step (where only the 2 choices are shown new/restore) temporarily so it can be reworked.  The logic to decide whether to show that screen was becoming cumbersome and too easy to break.  In a following PR I will be addressing that and making sure that the flow proposed by @linnutee is implemented.
> [launcher] Wallet name and Watch only styling

- app/actions/ControlActions.js
- app/components/inputs/Input.js
- app/components/views/TransactionsPage/SendTab/index.js
- app/connectors/send.js
- app/reducers/control.js
- app/selectors.js
Instead of passing the insufficient funds error through to be used in the snack bar, we instead capture it and alert the amount fields instead.
This also includes a fix to hide the "unit" of an input field if there is an error detected.
> [send] Show insufficient funds error below field

- app/actions/StatisticsActions.js
- app/components/charts/TicketChart.js
Fix #1493 
Fix #1514 
This removes the immature balance from tickets balances which is calculated as negative in the startup statistics and also fixes the negative balances on the daily balances chart.
The underlying problem was a small difference in how pool fees were being calculated in the forwards vs backwards statistics.
> [charts] fix negative balances

- app/actions/WalletLoaderActions.js
- app/components/views/GetStartedPage/WalletSelection/Form.js
- app/config.js
- app/connectors/walletStartup.js
- app/main_dev/ipc.js
- app/selectors.js
Close #1530 
Close #1460 
This isn't backwards compatible (won't label already created watch only wallets), but I think that's acceptable since it will really only effect the devs that have been recently using watch only wallets.
This also includes a sort for available wallets so the most recently user wallet is list on the left.
> [launcher] Label watch-only wallets

- app/components/views/AccountsPage/Accounts/List.js
- app/components/views/AccountsPage/Accounts/index.js
- app/components/views/AccountsPage/Page.js
- app/components/views/AccountsPage/index.js
- app/components/views/SecurityPage/index.js
- app/components/views/SettingsPage/Page.js
- app/connectors/accountsPage.js
- app/connectors/index.js
- app/connectors/security.js
- app/connectors/settings.js
- app/selectors.js
starts #1490 
This PR hides some functionalities when in watching wallet only mode. 
- sign/verify message
- new account button
- change passphrase button
We still need to figure what to do with tabs that need to be hidden.
I believe hiding the tabs would be fine, if we have a message showing that the wallet is not fully functional because of the watching only mode.
> [multi] Hide watching only functionalities

- app/actions/ControlActions.js
- app/components/buttons/SendTransactionButton.js
- app/components/buttons/SignMessageButton.js
- app/components/buttons/index.js
- app/components/shared/VerticalAccordion.js
- app/components/shared/index.js
- app/components/views/AccountsPage/Accounts/AccountRow/RenameAccount.js
- app/components/views/AccountsPage/Accounts/AccountRow/Row.js
- app/components/views/AccountsPage/Accounts/AccountRow/index.js
- app/components/views/SecurityPage/SignMessage/Form.js
- app/components/views/SecurityPage/SignMessage/index.js
- app/components/views/TransactionsPage/SendTab/Page.js
- app/components/views/TransactionsPage/SendTab/index.js
- app/connectors/signMessagePage.js
- app/helpers/byteActions.js
- app/helpers/index.js
- app/index.js
- app/reducers/grpc.js
- app/selectors.js
- app/style/AccountRow.less
- app/style/AccountsPage.less
- app/style/MiscComponents.less
- app/wallet/service.js
Part of #1491 
This PR should *not* have any trezor references, but is a step in integrating it. These commits have been extracted from my main trezor branch and are sent as a separate PR in order to facilitate review and merge, since the actual trezor code will require a lot of review.
This refactors 3 ui elements into their own components, which will (in the actual trezor PR) be used:
- SendTransactionButton (which will have to decide how to sign a transaction before sending)
- SignMessageButton (same thing)
- VerticalAccordion (which is used in the config page)
I've refactored the AccountsList page to use the new VerticalAccordion, which removes quite some code and styles, simplifying it a bit. It also has slightly better responsiveness.
> [multi] refactor tx, msg and accounts components

- app/style/GetStarted.less
- app/style/LanguageSelect.less
- app/style/Loading.less
Small improvement in the wallet selection page to allow launching the wallet when screen height < 600px (happens often in laptops).
> [launcher] improve wallet selection responsiveness

- app/components/views/HomePage/index.js
- app/containers/App.js
By default doing a third click on something on the sidebar opens a new electron window however with this fix that action is stopped.
Fixes #1537
> Prevention of third click (mouse wheel) opening new window open

- app/selectors.js
Fix #1548 
This fixes the issue by forgoing accounting for non-wallet inputs/outputs of tickets and votes. While this solves the presence of negative balances, it's not ideal because we don't get to see the locked balances in the charts.
Another alternative (but which might require modifications to dcrwallet) is to unlock the wallet during the initial scan for transactions, which allows it to import scripts it finds in the blockchain automatically and seems to also fix the issue.
> [charts] fix negative startup balance charts

- app/components/buttons/ModalButton.js
- app/components/buttons/SendTransactionButton.js
- app/components/inputs/AccountsSelect.js
- app/components/views/TransactionsPage/SendTab/OutputAccountRow.js
- app/components/views/TransactionsPage/SendTab/OutputRow.js
- app/components/views/TransactionsPage/SendTab/Page.js
- app/components/views/TransactionsPage/SendTab/index.js
This enables the Enter key shortcut on the send transaction page such that when e enter key is pressed, it defaults to the send button if the transaction is valid
This fixes #1221
> Add event listener to submit send transaction form on enter key press

- app/components/views/GetStartedPage/WalletSelection/Form.js
- app/components/views/GetStartedPage/WalletSelection/index.js
- app/config.js
- app/connectors/createWallet.js
- app/index.js
- app/selectors.js
Adds a config option (not currently exposed in the UI) to allow creation of more than 3 wallets.
This is specially useful when testing things that involve wallet creation, since you usually need to create multiple wallets.
> [launcher] add max_wallet_count config

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/actions/DaemonActions.js
- app/actions/WalletLoaderActions.js
- app/components/views/GetStartedPage/DaemonLoading/Form.js
- app/components/views/GetStartedPage/DaemonLoading/index.js
- app/components/views/GetStartedPage/SpvSync/Form.js
- app/components/views/GetStartedPage/SpvSync/index.js
- app/components/views/GetStartedPage/StakePools/index.js
- app/components/views/GetStartedPage/WalletSelection/Form.js
- app/components/views/GetStartedPage/WalletSelection/index.js
- app/components/views/GetStartedPage/index.js
- app/components/views/TicketsPage/PurchaseTab/Tickets.js
- app/components/views/TicketsPage/PurchaseTab/index.js
- app/config.js
- app/connectors/walletStartup.js
- app/index.js
- app/middleware/api.proto
- app/middleware/walletrpc/api_grpc_pb.js
- app/middleware/walletrpc/api_pb.js
- app/reducers/grpc.js
- app/reducers/snackbar.js
- app/reducers/walletLoader.js
- app/selectors.js
- app/style/StakePool.less
- app/wallet/client.js
- app/wallet/loader.js
~This PR requires https://github.com/decred/dcrwallet/pull/1221 binary to be used.~
The new SPV mode in dcrwallet uses a simple all-inclusive startupSync method that does everything required to prepare the wallet for usage while in SPV mode.  This is accessed by the new rpc `SpvSync`.  This creates a new response stream that will stay open for the life of the dcrwallet process, is canceled or has an unrecoverable error.  
This PR also includes updates and refinements to the existing normal mode startup procedures.  A new call for `FetchMissingCFilters` has been added.  Also we now rely on `RescanPoint` requests to tell us where the last rescan had ended so we can consistently pick up from there.  There was also some juggling of startupSteps that took place to further correct and smooth …
> [various] Changes to allow new dcrwallet SPV mode

- app/main_dev/paths.js
There is still more work to do to get the 32-bit builds properly killing the various spawned processes.  This makes it work again on win64.  The corresponding issue discussing the problem is here: #1345
> Revert changes for win32/64 exe pathing

- app/main_dev/launch.js
`require()` doesn't accept a run time constant. The location of the module needs to be a static string.
> [win32] fix win32ipc.node location

- app/style/GetStarted.less
Needed on MacOS when hovering over clickable area.
See screenshots below of mouse pointer style without these changes.
> Add cursor pointer to GetStarted view

- app/actions/WalletLoaderActions.js
Fix #1604 
The error when a wrong public passphrase is entered changed in dcrwallet, that's why the "decrypt wallet" page was not being shown.
> [launcher] show public passphrase page

- app/actions/ControlActions.js
Fix #1606 
In a brand new (ie, not imported/recovered) wallet there's no expectation of address use, so we perform an initial rescan at the best block height so that the wallet will start relaying new transaction notification data.
The bug only happened in normal (non-spv) mode.
> [launcher] fix notifications for new wallet in normal mode

- app/connectors/sideBar.js
- app/selectors.js
This fixes the logo being undefined when opening a watching only wallet. I will also open an issue to refactor these selectors so use only one in both case using an `or` method.
> Fix Watch only logo

- app/components/SideBar/Bar.js
This solves the NaN error returned by balances of new accounts.
if total is empty, set to zero. Newly created accounts would have their balances set to zero. 
Closes #1611
> [sidebar] Fix NaN on balance for new account

- app/components/views/TxDetails.js
- app/selectors.js
- app/style/Header.less
- app/style/TxHistory.less
Fix #1622 
This fixes the icons related to ticket transactions in the tx details page and shows the correct status for recent stake txs in the overview.
The fix is slightly hackish, but I'll improve it later as part of a refactoring of the GetTickets call.
> [multi] fix tx details and home icons

- app/actions/StatisticsActions.js
- app/index.js
- app/reducers/statistics.js
This prevents a small race condition (more likely to happen in big wallets) where the stats gathering is started twice.
> [stats] prevent fetching startup stats twice

- package.json
- yarn.lock
Resolves: https://electronjs.org/blog/web-preferences-fix
> [deps] Update electron to 2.0.8 due to a vulnerbility

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/actions/DaemonActions.js
- app/actions/SidebarActions.js
- app/actions/WalletLoaderActions.js
- app/components/SideBar/Bar.js
- app/components/SideBar/Logo.js
- app/components/SideBar/index.js
- app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/index.js
- app/components/views/GetStartedPage/WalletSelection/CreateWalletForm.js
- app/components/views/GetStartedPage/WalletSelection/Form.js
- app/components/views/GetStartedPage/WalletSelection/index.js
- app/connectors/createWallet.js
- app/connectors/sideBar.js
- app/connectors/walletStartup.js
- app/containers/App.js
- app/index.js
- app/main_dev/ipc.js
- app/reducers/control.js
- app/reducers/sidebar.js
- app/reducers/walletLoader.js
- app/selectors.js
Fix #1626 and a few other small issues. Can rework into separate PRs if needed.
Things fixed:
- Removed sidebar cruft that is no longer applicable now that we moved the GetStarted pages into a separate container that doesn't have the sidebar
- Unified `isWatchOnly` and `isWatchingOnly` into a single selector to simplify things
- Fix casing of `/getStarted` (converted to `/getstarted`) which was causing a small modal bug when closing a wallet then trying to remove it
- Fix a small bug when trying to create two new wallets in a row (seed was not shown)
> [multi] Refactor sidebar, isWatchingOnly, GetStarted

- app/components/views/TicketsPage/PurchaseTab/Tickets.js
A few user had reported not being able to purchase tickets in the final 5 blocks of a sdiff window in v1.3.0 while in normal mode.
> [tickets] Normal mode should allow tickets always

- app/components/views/TicketsPage/StatisticsTab/Page.js
- app/components/views/TicketsPage/StatisticsTab/charts/StakePoolStats.js
- app/components/views/TicketsPage/StatisticsTab/index.js
- app/connectors/myTicketsCharts.js
- app/selectors.js
Close #1668 
This switches the stakepool stats page to initially select the first configured stakepool (if available).
It also fixes a small issue on the tickets stats page introduced by #1667.
> [tickets] show stats for selected stakepool

- app/components/views/TicketsPage/PurchaseTab/Tickets.js
- app/connectors/spv.js
- app/selectors.js
Currently ticket purchasing for SPV is only not allowed on the second to last block of a window.  This is due to the upcoming changing price will ultimately cause the ticket itself to be pruned from the mempool.  Now we are just blocking ticket purchasing on that 1 block.
> [tickets] Fix SPV ticket purchasing

- app/main_dev/launch.js
- app/main_dev/logging.js
This fixes a small UI issue where after closing the wallet and going back to the wallet selection page you'd see a log line superimposed to the list.
> [logs] Clean after closing wallet

- app/main_dev/launch.js
- app/modules/win32ipc/module.cc
- app/modules/win32ipc/moduleTestWallet.js
- app/modules/win32ipc/pipe_wrapper.cc
- app/modules/win32ipc/pipe_wrapper.h
Close #1675 
Close #1653 
Fix #1645
> [win32] Explicitly close rx pipe when closing wallet

- app/actions/ClientActions.js
- app/actions/WalletLoaderActions.js
Close #1701 
I can regularly hit the getBestBlock failure error without this change.  I was able to complete 10 reloads in a row with no issues.  This was the case in both SPV and normal mode.
> [launcher] Delay getBestBlock slightly to avoid issues on reload

- app/actions/SettingsActions.js
The initial privacy page saves settings without having a loaded wallet, so this needs to be protected.
> [launcher] Fix initial privacy page

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/actions/DaemonActions.js
- app/actions/SettingsActions.js
- app/actions/WalletLoaderActions.js
- app/components/views/SettingsPage/GeneralSettings.js
- app/index.js
- app/main_dev/launch.js
- app/reducers/walletLoader.js
- app/selectors.js
This now allows decrediton users to change the network they would like to use without closing and restarting.
> [settings] Add network toggle to settings

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/actions/NotificationActions.js
- app/components/Snackbar/index.js
- app/connectors/send.js
- app/fp.js
- app/index.js
- app/reducers/snackbar.js
- app/selectors.js
- app/style/Snackbar.less
Close #1718 
I was doing this in the context of improving performance for large wallets (so that after loading, the wallets didn't have so many state updates) but refactored it into a separate PR.
This changes the transaction notification handler to collect all notifications issued during a period of time (currently hard coded at 5 seconds) and perform a single state change with the new transactions.
This is specially useful for large wallets which receive multiple notifications once a new block is connected (eg: due to new tickets/votes being published by an online hot wallet). This has the side effect of also handling #1718 by bundling split and ticket transactions (which are received as separate notifications of new unmined transactions) into a single `NEW_TRANSACTIONS_RECEIVED` state …
> [notifications] Delay transaction notifications

- app/reducers/snackbar.js
Fixes #1694
Now it says "Entered incorrect private passphrase reset blocked."
> More allusive passphrase update failed message

- package.json
- test/mocks/electronMock.js
- test/mocks/fileMock.js
- test/mocks/grpcMock.js
- test/mocks/styleMock.js
- test/setup.js
- test/unit/components/Balance.spec.js
- yarn.lock
This re-enables and fixes the unit tests for the Balance component that had been disabled when we introduced the i18n subsystem.
It also adds some global mocks and imports which are required when unit testing other components.
> [tests] Fix and return balance tests

- app/config.js
Close #1731 
This cleans the global config and wallet config files for any field that isn't currently used by the wallet.  Also remove some fields that weren't needed any more.
> [config] Cleanup configuration files

- app/components/views/GetStartedPage/WalletSelection/Form.js
- app/style/Global.less
- app/style/Modals.less
When you want to delete any wallet from home view a module popup with "remove default-wallet (mainnet)" used to come up no matter which one clicked now with this PR it says "remove name-of-wallet-selected"
Fixes number 5 of #1725
> Wrong label for delete wallet fix

- app/style/GetStarted.less
I was testing creating a new wallet and noticed the copy to clipboard button on the new seed page wasn't showing the pointer cursor
> Fixed copy seed button cursor

- app/style/MiscComponents.less
Close #1669 
Fix for the misaligned search button in the Transactions Exports page.
First option: just removed the margin (the one I used)
Second option: smaller icon
Which do you guys prefer?
> [transactions] Misaligned search button fix

- app/actions/ClientActions.js
- app/actions/DecodeMessageActions.js
- app/components/views/TxDetails.js
- app/connectors/transactionDetails.js
- app/index.js
- app/reducers/grpc.js
- app/selectors.js
- app/style/TxDetails.less
Part of #1775 
The timestamp bug in the header happens because the information used for showing the timestamp, ticket price and ticket reward was not available in the appropriate selector (due to that ticket not being in the list returned by the last call to `GetTickets()`). 
This needs to be solved by individually requesting the stake information when the data of the respective ticket is not yet available.
There's an outstanding UX issue if details for a very old ticket are requested: given dcrwallet doesn't have an endpoint to request the information for a single ticket, we're unable to show whether this ticket voted or not. To fix this, we first need a new `GetTicket()` endpoint in dcrwallet to then double back and wrap this.
> [transaction] Fix timestamp in headers for votes

- app/actions/ClientActions.js
- app/actions/StatisticsActions.js
- app/index.js
- app/reducers/statistics.js
- app/wallet/service.js
- package.json
- yarn.lock
This improves the startup time and usability for large wallets by:
- Using local (js) code to decode transactions instead of the wallet service
- Only starting to listen for tx/account notifications after full startup
- Preventing repeated stats calculation if the initial calc time was big
Testing on a large testnet wallet (96k+ votes, 3k+ live tickets) startup time reduced from ~10min to ~2min.
Currently a WIP as there's some instrumentation left to facilitate testing.
The initial code for transaction decoding was done by @alexlyp
> [stats] Improve startup stats in large wallets

- app/actions/StatisticsActions.js
- app/helpers/dateFormat.js
Part of #1775 
If you set your timezone in settings to "UTC", and export transactions, the time is still exported with your local timezone offset.  In my case this made the time value the correct instant in UTC, however there was -0500 appended to the time, which then makes the whole time value incorrect.
By the way, I believe if your local machine timezone is GMT and your offset is 0000, the time would have been formatted to 12:20:21.000-0000, which is not ISO 8601 format, so this fixes that issue also.
This is my first contrib, so I'm very open to tweaks.  I considered using a constant for "utc" but it wasn't obvious.  Also, I found another use of the hardcoded string, and given utc is self-explanatory, I left it.  Current example in selectors.js 
`export const tsDate = compose(timezone …
> Fix the Timezone on exported transaction records when set to UTC

- app/components/layout/TabbedPage.js
This PR improves motion effects on tabbed pages, which I discussed with @alexlyp at slack. 
It fixes the bug when having only 2 tabs;
It removes some unused code; 
It adds opacity into the transitions and makes the effect more stiff
> Improve motion effect

- app/components/layout/TabbedPage.js
This PR fixes a bug on tabbed pages.
How to reproduce: 
- Click on a tabbed page menu (like transactions)
- Click on the menu again
- the content on the screen will dismiss
> Fix tabbedPage bug

- app/actions/DaemonActions.js
- app/index.js
- app/reducers/daemon.js
The check to make sure that the network chosen and the daemon match should only need to occur once.  Rather than every time we check the synced block height.
> [launcher] Only check network info once

- app/components/SideBar/LastBlockTime.js
- app/components/buttons/ModalButton.js
- app/components/inputs/AccountsSelect.js
- app/components/inputs/DcrInput.js
- app/components/inputs/LanguageSelect.js
- app/components/inputs/SettingsInput.js
- app/components/modals/Modal.js
- app/components/shared/VerticalAccordion.js
- app/components/views/AccountsPage/Accounts/AccountRow/Row.js
- app/components/views/AccountsPage/Accounts/AccountRow/index.js
- app/components/views/GetStartedPage/CreateWallet/CreateWalletForm/index.js
- app/components/views/GetStartedPage/WalletSelection/Form.js
- app/components/views/GetStartedPage/WalletSelection/index.js
- app/components/views/GetStartedPage/index.js
- app/components/views/GetStartedPosition.js
- app/components/views/GovernancePage/Blockchain/AgendaOverview/index.js
- app/components/views/GovernancePage/Proposals/index.js
- app/components/views/SecurityPage/SignMessage/index.js
- app/components/views/SecurityPage/ValidateAddress/index.js
- app/components/views/SecurityPage/VerifyMessage/index.js
- app/components/views/TicketsPage/PurchaseTab/StakePools/index.js
- app/components/views/TicketsPage/PurchaseTab/index.js
- app/components/views/TicketsPage/StatisticsTab/index.js
- app/components/views/TransactionsPage/SendTab/index.js
This PR updates the code that are being deprecated in react 17. 
The methods `componentWillMount`, `componentWillReceiveProps`, and `componentWillUpdate` are going to be deprecated at react 17: 
https://reactjs.org/docs/react-component.html 
Where was needed to do more code refactor then simple changing the props, I committed separated, to make code review easier. 
Also this PR still a work in progress because I could not test `app/components/views/TicketsPage/PurchaseTab/StakePools/index.js` because I am not being able to reimport an API key into my wallet. 
Additionally our snackbar uses componentWillReceiveProps, and I think it would be better to use memoization, one of the methods that is suggested to replace the  componentWillReceiveProps method. Here more about it: …
> Update deprecated react code

- .travis.yml
- package.json
Currently we are having travis package for linux and osx, but realistically there isn't much worth to do this since the packages themselves won't be usable since they don't include dcr* binaries.  I'll be opening a new issue that will cover the changes that we need for travis to properly include packaging.
> Remove travis packaging for now

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/actions/StakePoolActions.js
- app/components/views/GetStartedPage/StakePools/index.js
- app/components/views/TicketsPage/PurchaseTab/Page.js
- app/components/views/TicketsPage/PurchaseTab/StakePools/AddForm.js
- app/components/views/TicketsPage/PurchaseTab/StakePools/index.js
- app/components/views/TicketsPage/PurchaseTab/index.js
- app/connectors/stakePools.js
- app/connectors/ticketsPage.js
- app/reducers/snackbar.js
Close #1773 
This changes the interaction of stakepool api key entry to preserve the api key and host selection if an error (such as wrong passphrase or wrong api key) is triggered. 
It also refactors the stakepool actions in the following ways:
- Use async/await calls to reduce code/indentation depth
- The importScriptAttempt() function now no longer triggers success/error snackbars (which removes the need for many conditionals and parameters throughout stakepool import/ticket purchasing actions)
- A manualImportScriptAttempt() function was added for manual script import (which does trigger snackbar messages and rescans)
- the setStakepoolInfo() call now does some of the checks that were done deeper in the call stack (removing the need to propagate arguments)
- The snackbar has been …
> [stakepools] Refactor actions and apikey entry ux

- app/actions/WalletLoaderActions.js
- app/reducers/walletLoader.js
Fix #1698 
Tracked down the issue to the `syncCall` state var not being correctly cleared when closing the wallet and not being replaced on a subsequent invocation.
> Fix stream error

- app/components/views/GetStartedPage/DaemonLoading/Form.js
- app/components/views/GetStartedPage/OpenWallet/DecryptForm.js
- app/components/views/GetStartedPage/OpenWallet/index.js
- app/components/views/GetStartedPage/index.js
- app/connectors/walletStartup.js
- app/selectors.js
Fix #1699 
The main issue seems to be that after all the launcher refactorings, the `isInputRequest` selector was left using some superseded state, so the decrypt wallet page was being shown in some wrong situations.
This cleans up and renames the selector to `openWalletInputRequest` so that it's more obvious what it's doing and to make it explicit it's following the corresponding state var.
I tested a bunch of combinations of the startup procedure (spv/rpc/advanced/non-advanced) on existing and new wallets, and with/without the public passphrase.
> [launcher] Fix asking for public passphrase

- app/actions/StatisticsActions.js
- app/helpers/dateFormat.js
- app/selectors.js
This PR closes #1823 .
It also clean up a bit the `StatisticsActions`.
I am starting the clean up by separating the methods from `balancesStats`, making them more independent, and separating the backwards logic from the straight forward one.
The objective behind that is to make it easier to understand and maintain the statistics logic. 
This still a WIP because I still have to check if all the exports methods are right, and there are some more clean up to do, but I am opening this PR now so you guys can see it.
The immature and locked values on daily balance looks wrong on master and this PR also fixes it
> Fix negative locked

- app/actions/ClientActions.js
- app/components/views/TransactionPage/index.js
- app/components/views/TxDetails.js
- app/connectors/transactionDetails.js
- app/connectors/transactionPage.js
- app/fp.js
- app/reducers/grpc.js
- app/selectors.js
This happens on some situations with a ticket transaction continually requesting the missing stake info.
The easiest way to test this is to purchase a ticket, then create a new wallet using the same seed but without importing the stakepool api key, then try to see the tx details. A few other situations (eg: split tickets without voting rights) also trigger this.
There are a couple of things triggering this, bust mostly the issue is that when the normalized transaction data has `!TicketPrice`, it will continually request the stake info. I had to refactor some stuff to allow the correct state to be propagated.
> [actions] Fix fetchMissingStakeInfo infinite loop

- app/actions/ClientActions.js
- app/components/views/FatalErrorPage.js
- app/main_dev/launch.js
- app/main_dev/logging.js
Close #1861 
This primarily fixes a bug that was causing an unexpected error on `reactIPC.sendSync()`
I've also added another log line reader to parse for panics (or stack traces).  If a wallet error is captured, then the failed ping redirect is overridden.
> [logging] Properly capture panics and display to the user 

- app/components/buttons/ImportScriptIconButton.js
- app/components/buttons/index.js
- app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/Form.js
- app/components/views/TicketsPage/PurchaseTab/StakePools/AddForm.js
- app/connectors/importScript.js
- app/connectors/index.js
- app/style/StakePool.less
This allows an user to import a script without having to add a stakepool first (which is necessary to use if the stakepool has disappeared or you're trying to import a script other than ones used by stakepools).
The loading indicator will need some iteration from design, but we can improve it in time.
> [tickets] Add import script button to AddStakepool form

- app/actions/StatisticsActions.js
- app/reducers/statistics.js
3 fixes rolled up:
- Fix small regression for large wallet startup introduced in #1839 (backwards stats wasn't being stopped after the 14 day window)
- Fix close state not correctly clearing stats daily stats
- Fix stats calc when the wallet doesn't have the ticket transaction associated with a given vote/revocation.
This last one will usually happen in pool fee wallets, which only record the reward received via a vote/revocation. The easiest way to test this (if you don't have easy access to a pool fee wallet) is to create a wallet, grab an address, then go back to a ticket buying wallet and manually change (in the corresponding `config.json`) the pool fee address so that you buy a ticket paying into the new wallet.
Obviously you need to wait for the purchased ticket to vote or be …
> [stats] Fix startup stats regression and ticketless wallets

- app/reducers/trezor.js
This disables trezor integration once a trezor-enabled wallet is closed.
Without this, you would still see the trezor sidebar menu item after closing a trezor wallet and opening a non-trezor one.
> [trezor] Disable integration when closing wallet

- app/components/views/GetStartedPage/WalletSelection/index.js
Fix #1877 
Ended up adding a few more chars than simply PATH_SEPARATOR.
> [launcher] Prevent special chars in new wallet name

- app/components/views/TicketsPage/PurchaseTab/StakePools/index.js
- app/selectors.js
Fix two small bugs I found while testing previous PRs:
- Fix an error with the tickets page when first creating a wallet. If you access the tickets page fast enough (before the stakepool list has finished loading) you could get a white page error due to not having a previous `selectedUnconfigured` state var set in the page.
- Fix an exception thrown in the accounts page if the `isWatchingOnly` selector didn't store a bool (this could happen if, eg, the `iswatchonly` config var got erased.
> [multi] Small new wallet bugs

- app/actions/ControlActions.js
- app/components/buttons/SendTransactionButton.js
- app/components/views/TransactionsPage/SendTab/Page.js
- app/components/views/TransactionsPage/SendTab/index.js
- app/connectors/send.js
- app/selectors.js
- app/style/SendPage.less
closes #1682 
I need to rebase, so if can test in trezor mode, that would be great.
> [watch only] Watch only transaction

- app/actions/TrezorActions.js
- app/components/views/GetStartedPage/WalletSelection/index.js
- app/connectors/createWallet.js
- app/reducers/trezor.js
Fix #1881 
This changes the wallet create page so that when leaving it or disabling the trezor switch, trezor integration is correctly disabled.
> [trezor] Disable trezor integration when creating wallet

- app/actions/SettingsActions.js
- app/components/buttons/EnableExternalRequestButton.js
- app/connectors/settings.js
- app/reducers/settings.js
Close #1887 
The main motivation for being an individual action instead of reusing the saveSettings action is so that the current temp settings can be preserved if it's changed (eg: go to the settings page, change language and check politeia, then go to the governance page and enable politeia - the changed language will be preserved in the changed settings but not will not be applied yet).
> [settings] Fix enabling external politeia requests

- app/components/views/GetStartedPage/WalletSelection/index.js
The error was the componentDidUpdate code relying on having a previous
selectedWallet available, when this won't be true if this the very first
wallet which creation was canceled.
Fix #1886
> [launcher] Fix whitescreen in wallet selection

- app/reducers/daemon.js
This adds a reset to daemonwarning (currently used for the v1.4.0
migration) on some situations when the warning is no longer applicable.
Fix #1907
> [launcher] Reset daemonwarning when appropriate

- app/components/modals/ChangePassphraseModal/Modal.js
- app/components/modals/ChangePassphraseModal/index.js
- app/components/modals/PassphraseModal/PassphraseModal.js
This changes the ChangePassphraseModal to submit the form when the user
presses the enter key with one of the inputs on focus.
This is slightly tricky due to how modals are currently structured.
Fix #1909
> [settings] Submit passphrase change on enter

- app/components/views/GetStartedPage/DaemonLoading/Form.js
- app/components/views/GetStartedPage/SpvSync/Form.js
Close #1921 
This will make it so the logs button is always shown.  Then depending on what logs are available they will be shown there.
> [launcher] Show logs on launcher

- app/actions/StatisticsActions.js
- app/selectors.js
Fix #1933 
#1933 was caused by appending unmined transactions at the end of the transaction list for processing, when the correct (in backwards mode) is to prepend it to the start of the list.
Fix #1930 
#1930 was caused by a division by 0 when there are tickets but no votes yet.
> [stats] Fix locked balance and vote time stats

- app/actions/GovernanceActions.js
- app/reducers/governance.js
This changes the logic for fetching Politeia data such that, if the
wallet is detected as closed (or changed) then the results or any errors
are ignored.
This is necessary because the external access to Politeia can be slow
(due to server load) or the call to the wallets CommittedTickets grpc
endpoint may take some time to complete if the wallet has many tickets.
An user closing the wallet while the results are still being fetched
would cause an undersirable snackbar error message without this fix.
close #1964
> [politeia] Ignore listing after wallet closed

- app/actions/ClientActions.js
- app/components/indicators/LoadingMoreTickets.js
- app/components/views/TicketsPage/MyTicketsTab/Page.js
- app/connectors/index.js
- app/connectors/loadingTickets.js
- app/index.js
- app/reducers/grpc.js
- app/selectors.js
- app/style/Loading.less
- app/style/MiscComponents.less
- app/style/Themes.less
This allows cancelation of the whole getTickets process mid-way through,
when problems or delays are noticed.
Decrediton's getTickets current scans the whole transaction set for
tickets of the specified filter status, so some combinations may be slow
to fulfill.
close #1958
> [mytickets] Allow cancelation when listing tickets

- app/actions/GovernanceActions.js
This changes the timestamp used for determining notification status from
the original 'timestamp' (last modification timestamp) to 'publishedat'
(publishing timestamp), given that proposals that sit a long time for
vetting might not generate a notification if they haven't been updated.
> [politeia] Use publishedat for notifications

- package.json
- yarn.lock
This upgrades to the latest electron version and updates node-abi which is required for rebuilding native modules.
Relevant upgrade notices for electron 4:
- Minimum macOS version is now 10.10 (Yosemite)
- Upgraded internal node version to 10.11 (should finally allow #1712 to be fixed)
Tested on linux and windows. You might need to `yarn rebuild-natives` after updating to this so that you don't warnings about the grpc module not being found.
> [deps] Update to electron 4

- app/connectors/spv.js
This PR fixes the purchase ticket tab crashing due the wrong selector name.
> [purchase ticket] Fix wrong selector name

- app/actions/WalletLoaderActions.js
> Host & Port not hardcoded anymore

- app/helpers/dateFormat.js
- test/unit/helpers/date.spec.js
It seems like the first setSeconds call has no use, because it's called again with `-1` a bit later.
> Remove extra setSeconds call

- app/main_dev/launch.js
- app/modules/win32ipc/module.cc
- app/modules/win32ipc/moduleTestWallet.js
- app/modules/win32ipc/pipe_wrapper.cc
- app/modules/win32ipc/pipe_wrapper.h
~**Requires #2009**~
This adds the pipetx flag to wallet initialization when running on the windows platform, so that the app can perform correct fetching of the grpc port during wallet startup and allows us to get rid of port detection via logs, which is brittle.
This requires the app to be compiled with an electron version 4 or higher, due to the correct function only being available on libuv 1.23+.
When testing this you might need to remove the entire `node_modules` and `app/node_modules` for the correct version of the module to be compiled. The win32ipc module does **not** work when using `yarn build && yarn start`, only with either `yarn dev` or `yarn package`.
Close #1712.
> [launcher] Add pipetx to wallet on win32 platform

- app/style/Governance.less
- app/style/Layout.less
Right now, on governance page, if the height is small, it is not possible to see all the proposals because it is not possible to scroll till the end. 
Also, if the text is long enough, it will not show the whole text, making it impossible to read the whole proposal.
This PR fix those.
> [governance] Fix proposal not scrolling on small height

- app/main_dev/launch.js
Due to various issues, the exporting of closeDCRD was removed in a previous PR.  This will fix an unexpected error when switching networks in settings.
> [main_dev] Make closeDCRD exported again

- app/package.json
- app/yarn.lock
- package.json
- yarn.lock
This updates grpc and electron to supported versions.
I haven't updated electron past 4.1.4 yet due to not having pre-built grpc binaries for those.
> Update grpc and electron

- app/main_dev/launch.js
The `addridxscanlen` dcrwallet option has been removed and replaced by `gaplimit`
> [launcher] Rename wallet option

- app/actions/GovernanceActions.js
- app/reducers/snackbar.js
I noticed when notification error  are objects, they do not show at the snackbar.
This PR transforms the error message to array, so we can show it.
> Return array on notification when error is object

- app/actions/DaemonActions.js
- app/actions/SettingsActions.js
- app/components/views/FatalErrorPage.js
- app/components/views/GetStartedPage/AdvancedStartup/index.js
- app/config.js
- app/connectors/fatalErrorPage.js
- app/main_dev/configConstants.js
- app/reducers/daemon.js
This PR starts https://github.com/decred/decrediton/issues/2121 and closes https://github.com/decred/decrediton/issues/2033
It starts refactoring our global config and I also added the ability to return to remote credentials after a fatal error when in advanced mode. 
after https://github.com/decred/decrediton/issues/2121 we can now check the dcrd connection and if it is different from decrediton there is no need to close decrediton to fix the problem (in advanced mode)
I am not yet refactoring wallet configs
> Refactor config.js

- app/actions/StatisticsActions.js
I noticed there is an error when counting tickets on the heatmap. It was zeroing the counter before switching the day, resulting in a wrong amount.
> [statistics] Move verification to the beginning of the loop

- app/index.js
Per Slack discussion dcrwallet api version 7.0.0 is compatible with 6.0.0
https://decred.slack.com/archives/C0NRMDVMJ/p1562949621352700
This resolves an issue where decrediton cannot be built with the latest release of dcrwallet v2.1.1
> Bump required dcrwallet api version to 7.0.0

- app/main_dev/launch.js
- app/reducers/snackbar.js
This PR fixes #2136 
I noticed logs are only not showing when connected as remote, which is expected. But I added a line to the logs informing that, to be more descriptive. 
I also noticed when failing to connect, decrediton is crashing due to a missing id on the notification message. This PR also fixes it. 
Here is an image of the crash:
> Fix log and no id message

- app/components/views/GovernancePage/Proposals/Details/Page.js
- app/components/views/GovernancePage/Proposals/Details/helpers.js
- app/components/views/GovernancePage/Proposals/Details/index.js
- app/helpers/strings.js
I noticed a run condition at governance Pages. If you open a proposal details, before `GETVETTED_UPDATEDVOTERESULTS_SUCCESS` is dispatched, the proposal stop showing at the governance page when it is dispatched.
> fix proposal details stop rendering

- app/components/buttons/EyeFilterMenu/index.js
after commit https://github.com/decred/decrediton/commit/4b4fd7af41b00478510cc80579e2746fba5ae9e6 decrediton will now crash when going to tx history or my ticket page, saying `menuOpen` is undefined.
This PR fixess it.
The crash:
> Move undefined variable to beginning

- app/style/TxHistory.less
I noticed the revoked icon is missing at overview
> fix revoked icon

- app/components/inputs/Input.js
After commit https://github.com/decred/decrediton/commit/3d399552856aec933b899ac37113dd5adfb630f6 most of the code being deprecated was removed, but this bits were missed or re-added. 
This PR removes it.
Also, these warnings are showing in decrediton despite all deprecated code being removed. So I believe it is from some dependency we are using:
When they get updated we can follow, as theses warnings can be annoying.
> Remove deprecated code

- app/components/SideBar/LastBlockTime.js
- app/components/indicators/LoaderBarBottom.js
- app/components/inputs/AccountsSelect.js
- app/components/inputs/LanguageSelect.js
- app/components/inputs/SettingsInput.js
- app/components/shared/FormattedRelative.js
- app/components/shared/index.js
- app/components/views/GetStartedPage/DaemonLoading/Form.js
- app/components/views/GetStartedPage/SpvSync/Form.js
- app/components/views/GetStartedPage/WalletSelection/Form.js
- app/components/views/GovernancePage/Proposals/Details/helpers.js
- app/components/views/GovernancePage/Proposals/ProposalList.js
- app/i18n/locales/index.js
- package.json
- yarn.lock
This updates react-intl to major version 3. Due to breaking API changes in
FormattedRelative (now called FormattedRelativeTime) I've re-wrote a
compatible FormattedRelative component in the shared dir.
Also the polyfill for Intl.RelativeTimeFormat can probably be removed after
we upgrade to electron v6.
Also I'm getting an error when rendering the `< 1 minute` message in the sidebar. Please double check if this happening to you as well. I've opened an issue in the upstream react-intl repo.
> [i18n] Update to react-intl v3

- app/helpers/tickets.js
This adds the missing agendas for DCP0004 and for the upcoming DCP0005 votes.
This is required so that the tickets page shows the selected vote choice in
cast tickets.
> [helpers] Add missing agendas

- app/actions/LNActions.js
- app/components/views/LNPage/ChannelsTab/PendingChannel.js
- app/components/views/LNPage/ConnectPage.js
- app/connectors/lnPage.js
- app/index.js
- app/reducers/ln.js
- app/selectors.js
This adds a check during node connection to ensure ln operations are only
performed after the node is synced to chain.
It also fixes a bug where you could go to another page, come back to the
ConnectPage view and try to connect again while a previous connection attempt
was still ongoing.
I'm also hiding the MaturingHeight attribute for the moment, since that's not 
working in the underlying dcrlnd.
> [ln] Add syncedToChain check at connect

- app/actions/StatisticsActions.js
- app/selectors.js
- package.json
- yarn.lock
Currently rebased on top of #2107 
Now that the wallet tracks the lockedByTickets balance by the individual commitments we can improve the balance stats for wallets that have shared tickets.
This also downgrades the react-intl version to 3.3.1 due to https://github.com/formatjs/react-intl/issues/1500 breaking the custom number formats.
> Fix commit balances

- app/containers/App.js
This fixes an issue with the sidebar showing as the
bottom bar when first loading the app in developer mode.
> [sidebar] Have sidebar leave bottom more aggresively

- app/actions/DaemonActions.js
- app/components/views/GetStartedPage/DaemonLoading/Form.js
- app/main.development.js
- app/main_dev/ipc.js
- app/main_dev/launch.js
- app/main_dev/logging.js
When updating dcrd to its latest version, decrediton will throw a timeout error when updating its database.
This PR avoid a timeout error and warns the user about it.
I updated the message to the following: `You are currently upgrading to a new dcrd version.  Typically, this one-time update will take 10-15 minutes on an average machine.`
On my computer it took less then 10 minutes to upgrade the database, no ssd. 
If you guys expect a longer or shorter time to update, let me know.
> Add warn when upgrading to new dcrd database version

- app/style/Modals.less
> Fix input field size and alignment on `Seed Clipboard Copy Warning` modal

- app/actions/ClientActions.js
- app/actions/GovernanceActions.js
- app/components/views/GovernancePage/Proposals/Details/Page.js
- app/components/views/GovernancePage/Proposals/Details/helpers.js
- app/components/views/GovernancePage/Proposals/ProposalList/Page.js
- app/config.js
- app/main.development.js
- app/main_dev/ipc.js
- app/main_dev/logging.js
- app/main_dev/paths.js
- app/reducers/governance.js
- app/style/Governance.less
- app/style/MiscComponents.less
~~This PR is built on top of https://github.com/decred/decrediton/pull/2192.~~
When testing this PR if one wants to cast a vote, it will be necessary to have eligible tickets.
It closes https://github.com/decred/decrediton/issues/2076, closes https://github.com/decred/decrediton/issues/2101, closes https://github.com/decred/decrediton/issues/2047, closes https://github.com/decred/decrediton/issues/2015 (duplicated), and closes https://github.com/decred/decrediton/issues/2166, and closes #1807
I am caching the eligible tickets and as @lukebp suggested we are only showing cast vote options for active voting proposals.
I believe we can also cache the information of other votes (we have this information when querying for the proposal details) and show votes of proposals which we have at the …
> Governance fix data download

- app/actions/DaemonActions.js
- app/actions/SettingsActions.js
- app/reducers/daemon.js
When testing the bug @jzbz described when upgrading the database, I wasn't able to reproduce it, but I found a couple of other issues.
When going from spv to regular mode the decrediton crashes the chain and we need to re-download it. Steps to reproduce: 
1. Need to be with dcrd database version 5;
2. Start decrediton in SPV mode
3. Goes from spv to regular mode
4. decrediton will try to download the whole chain and break it.
Also when making changes at the startup settings, after saving politeia will try to start before the wallet is started which makes it fail. I believe this is the cause of #2274.
So this PR closes #2274 and also closes #2273
> [Launch] Launch fixes

- .eslintrc.js
Right now if developing in windows and run lint, all break line will fail lint 
This PR fixes this so we do not need to switch the rule everytime we test lint.
> Accept windows break line in lint rule

- app/style/Governance.less
User mentioned that the proposal text on 1.5.0-rc1 didn't have any proper padding on the right or the bottom of the text area.
> [governance] Add proposal text padding

- app/selectors.js
dcrlnd does not currently support SPV mode so we need to disable the ability
to use LN when the wallet is configured as SPV.
> [ln] Prevent using with SPV

- app/actions/ControlActions.js
- app/actions/LNActions.js
- app/components/views/LNPage/ConnectPage.js
- app/style/LN.less
This adds a toggle that lets users choose whether to create a new LN-specific
wallet account when first initializing an LN wallet.
This way users are incentived to not use their default wallet account which
is likely to have the majority of their funds, which could cause many channels
to be automatically opened if the autopilot feature was selected.
> [ln] Add choice to create LN account during setup

- app/style/Layout.less
- app/style/Loading.less
- app/style/MyTickets.less
- app/style/StakePool.less
- app/style/Trezor.less
- app/style/TxHistory.less
As chatted with @linnutee at Matrix, we only use Incosolata for the overview's larger fonts. 
This PR switches its occurrences in other places.
> [fonts] Fix Incosolata in wrong places

- app/actions/GovernanceActions.js
- app/components/views/GovernancePage/Proposals/Details/helpers.js
- app/reducers/snackbar.js
This PR closes #2329, closes #2330, closes #2331
I also added a success message after casting vote, so the user can have a better feedback.
This is the message I added: 
`"Your vote has been casted with success!\n Thanks for participating in decred's governance"`
If someone has a better suggestions or phrase, I am open to discussion.
> [Governance] Cast vote fixes at proposal details page

- app/actions/WalletLoaderActions.js
This fixes a bug where re-opening the wallet afterwards made it seem the
ticketbuyer was still running.
close #2344
> [ticketbuyer] Stop on close wallet

- app/components/views/LNPage/ChannelsTab/index.js
Test was using the wrong attribute. The only effect was the push
amount panel was still shown, which is not ideal in mainnet.
> [ln] Fix testnet/mainnet attr

- app/middleware/api.proto
- app/middleware/walletrpc/api_grpc_pb.js
- app/middleware/walletrpc/api_pb.js
This PR updates our api.proto file to the latest dcrwallet's version. 
I used protoc v3.4.0: https://github.com/protocolbuffers/protobuf/releases/tag/v3.4.0.
When regenerating it switch the generated code from `Buffer()`, which is being deprecated, to `Buffer.from()`
> [protoc] Update middlewares

- app/components/inputs/DcrInput.js
- app/components/views/LNPage/ChannelsTab/Page.js
- app/components/views/LNPage/ChannelsTab/index.js
- app/components/views/LNPage/InvoicesTab/Page.js
- app/components/views/LNPage/InvoicesTab/index.js
- app/components/views/LNPage/PaymentsTab/Page.js
- app/components/views/LNPage/PaymentsTab/index.js
- app/components/views/TicketsPage/PurchaseTab/TicketAutoBuyer/index.js
- app/components/views/TransactionsPage/SendTab/OutputRow.js
- app/components/views/TransactionsPage/SendTab/index.js
- app/style/SendPage.less
This changes the DcrInput component to require only a single prop as
input ('amount').
Having to track both 'value' and 'amount' as consumer of DcrInput
was cumbersome and led to some mistakes such as in the ticket buyer
input that specifies the balance to maintain.
This improves the component so that only a single set of props
(amount/onChangeAmount) need to be specified and the component behaves
as expected.
> [inputs] Improve DcrInput usage

- app/actions/TrezorActions.js
The sequence field for inputs of prevtxs was not being sent to the device,
causing a failure to verify that the hash of the previous transaction and its
contents matched.
This error could be triggered if the trezor wallet received funds from a
non-dcrwallet sender that did not set the Sequence field of the authored
transaction to MaxTxInSequenceNum.
> [trezor] Send sequence for prevtx inputs

- app/actions/DaemonActions.js
This fixes an instance where selecting to use SPV for the first time on a new
install would cause the dcrd full node to run.
The problem was that to speed up the blockchain download, the node was started
after SPV choice and before the wallet tutorial but it was started
unconditionally, without considering the previous choice to only run in SPV
mode.
How to reproduce the issue (without this commit):
- Rename/remove `~/.dcrd/data/testnet3` (so that it's more obvious the daemon is running and performing IBD)
- Edit `~/.config/decrediton/config.json`:
- `show_tutorial: true`
- `spv_mode: false`
- `show_spvchoice: true`
Start decrediton, select SPV and the daemon is started.
> [launcher] Fix SPV choice triggering daemon launch

- app/actions/DaemonActions.js
- app/actions/WalletLoaderActions.js
- app/config.js
- app/main.development.js
- app/main_dev/ipc.js
- app/main_dev/launch.js
As we had 1.5 release, this branch code got outdated, and after rebasing it against master, some functionalities on advanced startup mode stopped working.
This PR fixes it. To test it, it is needed to run `yarn` as it needs to install `xstate`
Right now, only advanced options works: connect as remote and start dcrd with different appdata. 
Regular mode is started at: https://github.com/decred/decrediton/pull/2198 but not yet merged.
> [Startup] Fix advanced mode after rebase

- app/actions/ClientActions.js
- app/selectors.js
This changes the getTransactions() action call to always fetch and fill
missing stake info for stake transactions.
This fixes an issue where the ticket price and reward amounts appeared as
zero in the history list for stake transactions.
Fix #2350
> [actions] Always record ticket info for stake txs

- app/actions/ControlActions.js
- app/index.js
- app/reducers/control.js
- app/wallet/service.js
This prevents address exhaustion due to generating more than the gap limit
addresses by storing the most recently generated change address and reusing
it for all future transactions (for that account) until the transaction is
published.
Work around https://github.com/decred/dcrwallet/issues/1622
> [control] Prevent gap exhaustion in change generation

- app/i18n/docs/en/ReleaseNotes/v1.5.0.md
> Fix misspelled `consistently` in 1.5.0 release information

- app/i18n/translations/original.json
- app/reducers/snackbar.js
> Import to csv notification quoting fix

- app/components/views/HomePage/tabs/Balance.js
- app/components/views/HomePage/tabs/Tickets.js
- app/components/views/HomePage/tabs/Transactions.js
- app/connectors/ticketHome.js
- app/selectors.js
- app/style/HomePage.less
SPV wallets don't track the live and missed ticket count only the unspent.
Therefore we introduce a new selector to track the active ticket count as
intended for display purposes in the home page.
This correctly tracks the immature+unspent count in SPV wallets and
immature+live in RPC wallets.
This fixes an issue reported in the support channel.
> [home] Fix active ticket count in SPV wallets

- app/components/views/GetStartedPage/WalletSelection/Form.js
This improves an UI issue where users are confused by the "watching-only" label in their trezor-based wallets.
> [walletselection] Show trezor wallets with correct label

- app/actions/ClientActions.js
fixes #2406 and fixes #2341. 
The reason this bug only happen sometimes, is because dcrdata sends a floating number, so it can send numbers with less than 8 decimal places, sometimes (maybe some rounding, Idk). 
> fix treasury balance

- app/components/views/TransactionsPage/ReceiveTab/Page.js
- app/components/views/TransactionsPage/ReceiveTab/QRCode.js
- app/components/views/TransactionsPage/ReceiveTab/index.js
- app/style/ReceivePage.less
> Add BIP-0021 support

- app/package.json
- package.json
The matches similar usage in dcrd/dcrwallet. 
From now on. as a new release is put out will will start the next cycle by bumping to 1.X.0-pre.
> Bump to 1.6.0-pre

- app/actions/ControlActions.js
- app/components/views/TicketsPage/PurchaseTab/index.js
- app/connectors/ticketsPage.js
- app/selectors.js
- app/wallet/control.js
This PR adds the ability to watching only wallets import scripts.
It is a work towards https://github.com/decred/decrediton/issues/1491
> Import script watch only

- server.js
After e73ed049e5b0a50b310296381dbe85401713bdbd, we added a new start at decrediton which disables sandbox. This PR creates a new spawn, otherwise it starts with the same argv `--start-hot`
> Add new spawn

- app/connectors/home.js
- app/connectors/purchaseTickets.js
After f5408a5d3172e5c29d28cdaf305dd5a8147425f5 the selector hasTicketToRevoke was removed. 
This PR removes some left overs
> Remove hasTicketToRevoke selector

- app/style/Layout.less
- app/style/Settings.less
This is a follow-up PR of #2412 and fixes the responsiveness of the close button. 
Also fixes the first issue of #2390 (Close button copy overlap)
> Responsive close button on settings page

- app/actions/ClientActions.js
- app/components/TxHistory/TxHistoryRow/RegularTxRow.js
- app/components/TxHistory/TxHistoryRow/index.js
- app/components/views/HomePage/index.js
- app/selectors.js
- app/style/TxHistory.less
closes #2232
As the addresses we need to show are from non wallet inputs and outputs, we need to decode the raw transaction to show them. 
The problem with that approach is that it gets complicated to get addresses of inputs from received transactions, as they are shown as the previous outpoint. So right now I am showing the previous outpoint, which I am not sure if it is a relevant information for the user.
Here it is how it looks at overview page, so you guys can see it:
> Add tx's addresses to overview and transactions view

- yarn.lock
Currently on https://github.com/decred/decrediton/pull/2479 `yarn lint` step is failing with the following error:
`TypeError: Cannot read property 'range' of null`
As suggested here: https://github.com/babel/babel-eslint/issues/530#issuecomment-579421777
`yarn upgrade babel-eslint` indeed resolved the issue
> Upgrade babel-eslint

- app/components/views/TransactionsPage/SendTab/index.js
Closes https://github.com/decred/decrediton/issues/2495. It ensures that one can use the last generated address just after sending an amount or going back to send page. A new address is generated after transaction.
> Restore last address when switching to send to another account

- app/components/SideBar/Bar.js
- app/components/modals/Modal.js
- app/components/shared/Balance.js
- app/components/shared/TxHistory/StakeTxRow.js
- app/components/views/AccountsPage/Privacy/Page.js
- app/components/views/GetStartedPage/LanguageSelectPage/Page.js
- app/components/views/GetStartedPage/Page.js
- app/components/views/GetStartedPage/PrivacyPage/Page.js
- app/components/views/GetStartedPage/SpvChoicePage/Page.js
- app/components/views/SecurityPage/ValidateAddress/Form.js
- app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseTicketsAdvanced.js
This diff uses piui's exposed `classNames` function instead of (external?) library.
Note: No need to delete any entry from `package.json` as we don't have "classnames" as direct dep in `package.json` it appears only in yarn.lock as a dep of a dep.
Closes #2513
> [pi-ui] Use pi-ui's classnames instead of external lib

- app/actions/ControlActions.js
- app/components/views/TransactionsPage/SendTab/index.js
This diff cleans the send transaction tx info on component unmount.
I started by adding new action to cleanup the transaction info, and then noticed
that we already have one which is even dispatched inside `SendTab` but wasn't called
for anywhere, so I just added a `componentWillUnmount` to call `onClearTransaction` 
which was already there ☺️ 
Closes #2533
> fix: clear tx info when navigating away

- app/components/shared/TxHistory/RegularTxRow.jsx
- app/components/shared/TxHistory/Row.jsx
- app/components/shared/TxHistory/TxHistory.module.css
This diff improves the pending indicator which is displayed in both txs history & overview lists.
It includes the following changes:
- Use flex to align content of the row.
- Use pi-ui's `Tooltip`.
- Use pi-ui's `Text` component with `truncate` prop to ellipsis too wide text. 
Closes #2544 
After:
> Polish tx row pending indicator

- app/actions/GovernanceActions.js
- app/components/views/ProposalDetailsPage/ProposalDetails.jsx
@amassarwi reported to me a bug after voting on latest master. 
After f31cc4b768ee1ff25c5a7ff1e94e34f7bf0f834f, the ticket name was changed to `txHash` before saving it to our politeia directory:
https://github.com/decred/decrediton/commit/f31cc4b768ee1ff25c5a7ff1e94e34f7bf0f834f#diff-c8399d09f1bddd336993b884a3e8d512R623
When opening a proposal with this kind of votes, it would fail to open with the following message, as it is looking for tickets instead of txHash:
> Fix ticket naming when saving proposal votes

- app/store/configureStore.production.js
- package.json
- webpack.config.production.js
- yarn.lock
This PR aims to solve startup break by importing and using missing ``combineReducers`` function in ``app/store/configureStore.production.js``. After that, icons and fonts haven't been found anymore in production build. After investigating, it seems that https://github.com/decred/decrediton/pull/2479 changes have made it impossible to webpack to find out and extract ``url(...)`` imports in ``app/style/themes/*.js`` files, as those ``CSS`` variable definitions are solved in execution time. Due to this reason, it's not possible to use ``url-loader`` or ``file-loader`` to load these assets. The solution I've found is to use [https://webpack.js.org/plugins/copy-webpack-plugin/](url) webpack plugin. It consists in copying the missing dependencies directly to the requested directory. Another …
> Fix production build

- app/actions/TransactionActions.js
- app/selectors.js
I noticed if a wallet does not know some tx details it will crash decrediton when starting. This may happen for many reasons, one we discussed at matrix is that, mixer is set to ignore gap limit. So if someone mixes his outputs with a different wallet.db, decrediton may not recognize it. 
This PR deals with this case, so decrediton can still starts and we can further investigate the cause.
> Deal with error in case no tx details is found

- app/actions/GovernanceActions.js
This diff fixes a minor bug on proposal details when no eligible tickets are available.
Before:
after:
> [governance] fix: add validator for empty eligible tickets list

- app/components/modals/PassphraseModal/hooks.js
- app/hooks/useSettings.js
This PR fixes two minor bugs I've just checked in modal components:
1. ``PassphraseModal`` sometimes does not reset the passphrase input content.
2. ``ChangePasswordModal`` never works properly.
They were probably generated during refactoring.
> Fix minor bugs in modal components

- app/actions/ClientActions.js
- app/actions/DaemonActions.js
- app/actions/WalletLoaderActions.js
- app/index.js
- app/reducers/grpc.js
- app/wallet/client.js
This PR removes decrediton's ping to dcrwallet. 
Right now, most of the calls on decrediton works based on loopback interfaces and the ones which we keep a connection, we can tell when it stopped working, like ticket auto buyer or mixing.
So I am removing this grpc ping to dcrwallet, because it makes decrediton logs polluted
> Remove wallet ping

- app/actions/TransactionActions.js
- app/reducers/grpc.js
This PR fixes a bug on transactions overview and history page.
Right now after buying a ticket, after the split tx getting mined, it will mine the ticket tx again, making it show duplicated at our overview. 
Also, after making a tx, it is not showing at history transactions or my tickets page. 
This PR fixes these both cases. fixes #2520
> Fix unmined tx showing twice

- app/components/buttons/InvisibleButton.js
- app/components/modals/Modal.jsx
- app/components/views/ProposalDetailsPage/ProposalDetails.jsx
- app/components/views/ProposalDetailsPage/helpers/EligibleTickets/EligibleTickets.jsx
This diff adds support for short proposal urls which are supported since last politeia release.
In addition, it fixes a console error which was thrown because of `false` being used as `onClick`, when using `onClick={condition && value}` syntax, this commit resolves it by using `onClick={condition ? value : undefined}` instead.
Closes #2601
> [governance] Use short proposal urls

- app/components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfoDisplay.jsx
This PR corrects the path of the last ticket transaction, setting it to redirect to the right location. This bug has been found in https://github.com/decred/decrediton/pull/2594 as well. After this PR, there will be no further occurrence of ``transactions/history/txHash``.
> Fix transaction wrong path

- app/components/views/TransactionsPage/ReceiveTab/ReceiveTab.module.css
- app/components/views/TransactionsPage/ReceiveTab/ReceiveTabPage.jsx
Talking to @vctt94 , we concluded that we can speed up the tooltip transition when copying or generating a new address in a receive transaction.
This PR provides it.
> Speed up ReceiveTab tooltip transition

- app/actions/DaemonActions.js
- app/config.js
- app/constants/config.js
- app/helpers/byteActions.js
- app/helpers/files.js
- app/helpers/index.js
- app/helpers/strings.js
- app/main.development.js
- app/main_dev/launch.js
This PR fixes #2463 
With this change we are going to use the rpc.cert and rpc.key from decrediton's config directory, instead of the ones at dcrd, when starting decrediton with regular mode. 
If it is an advanced start and a different appdata, it will still need to update the rpc.cert and rpc.key, as we can't start dcrd with electron 8 as it doesn't support curve P-521.
~~Right now we are silently removing the files, as explained here https://github.com/decred/decrediton/pull/2599/files#diff-2c2e316b04b5e082a42f1340fc886b19R283~~
~~But I believe we can have a better approach for that. I believe we can make some kind of warn for the user so he makes a backup of his rpc.cert and rpc.key before removing them, what do you guys think?~~
Now, I am saving the rpc.cert and rpc.key at a directory …
> Use decrediton own rpc.cert and rpc.key instead of the ones from dcrd

- app/actions/ControlActions.js
- app/actions/VSPActions.js
After https://github.com/decred/decrediton/pull/2616, some import scripts methods were missed. 
This PR remove passphrase from them, as well
> Fix missing import scripts with passphrase

- app/components/views/GetStartedPage/TutorialPage/TutorialPage.jsx
This diff fixes the following issue which was reported on #2552:
> @matheusd reported when decrediton starting going to tutorial page, decrediton crashes
> [getstarted] fix crash on startup when `show_tutorial:true` in config.json

- app/components/views/ProposalDetailsPage/ProposalDetails.jsx
- app/components/views/ProposalDetailsPage/ProposalDetailsPage.jsx
This diff closes #2610, it ensures eligible tickets section is displayed only when 
proposal voting is active or finished.
Also, this diff includes changes related to prettifying, as I ran `yarn prettify`.
> [governance] show eligible tickets only when voting is active or finished

- app/actions/AccountMixerActions.js
- app/actions/ClientActions.js
- app/components/views/AccountsPage/Privacy/hooks.js
- app/constants/Decred.js
This PR makes the mixer throws an error and not start if the change account balance has its balances smaller than the min rellay fee.
> [cspp] not allow small balances to start mixer

- app/actions/TransactionActions.js
It is possible right now, that a regular tx which is not mined for some reason, show twice at our recent regular txs selector. 
> [recent txs] Fix recent regular txs showing twice

- app/helpers/tickets.js
This diff fixes a bug I experienced with my testnet wallet which was failing on startup while extracting P2SH for a ticket.
> Fix extract P2SH from ticket

- app/components/views/SettingsPage/Settings.module.css
This diff uses class selector for settings radio button styling to avoid overriding pi-ui's radio buttons styling.
Ideally we should replace all radio buttons in decrediton with pi-ui's. 
Closes #2611
> [governance] Fix pi-ui's radio button unexpected styling

- app/components/views/GetStartedPage/WalletSelection/Form.jsx
- app/components/views/GetStartedPage/hooks.js
- app/stateMachines/GetStartedStateMachine.js
I noticed on startup, if decrediton fails to get available wallets or if it fails to start a wallet, when choosing one, no feedback is given.
This PR fixes it. Example:
> [startup] Better deal with errors

- app/package.json
- app/yarn.lock
- package.json
- yarn.lock
This fixes the vulnerability alerts for dot-prop we are currently seeing.  As far as I can tell all previous issues we had with the locked version of electron-store and conf are no longer problems.
https://github.com/decred/decrediton/pull/1015 was the previous PR that rolled back the conf/electron store versions.
> [deps] Update deps to fix dot-prop vuln

- app/components/views/SettingsPage/PrivacySettings.jsx
- app/components/views/SettingsPage/Settings.module.css
- package.json
- yarn.lock
This diff replaces custom checkbox used in privacy settings with pi-ui's component.
Closes #2661 
Needs decred/pi-ui#294
~~Based on #2662~~
---
> [pi-ui][settings] Use pi-ui's Checkbox component instead of custom one

- app/actions/AccountMixerActions.js
- app/components/views/AccountsPage/Privacy/ConfigMixer/ConfigMixer.jsx
- app/components/views/AccountsPage/Privacy/hooks.js
Noticed that after creating the default accounts required for mixing, there are no changes on the UI. This Diff redirects it to the correct privacy view, and removes some useless `useCallback` hooks.
> [accounts] fix: small improvements on privacy accounts flow

- README.md
When the TLS keypairs for dcrd's rpc endpoint are generated using the default P-521 curve the decrediton can not connect to it. It receives this error message:
```Error: write EPROTO 10328117885128:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:592:SSL alert number 40\n10328117885128:error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO:../../third_party/boringssl/src/ssl/handshake.cc:589:\n```
This diff expands the README to inform users that they should use P-256 curve for generating the TLS keypairs.
> [advanced daemon mode] Use P-256 curve for generating TLS keypairs

- app/components/views/SecurityPage/VerifyMessage/VerifyMessage.jsx
This diff fixes #2699 - before this commit verify message form would show two results after
second submit.
> security page: fix verify message showing double messages

- app/components/views/GetStartedPage/CreateWalletPage/CreateWallet.module.css
- app/components/views/GetStartedPage/CreateWalletPage/CreateWalletPage.jsx
- app/components/views/GetStartedPage/CreateWalletPage/ExistingSeed/ExistingSeed.jsx
- app/components/views/GetStartedPage/CreateWalletPage/ExistingSeed/Form.jsx
- app/stateMachines/CreateWalletStateMachine.js
This diff improves the error handling on the existing seed view by changing the input's border color to red if the seed word is not at valid position.
> Improve error handling on existing seed view

- app/components/shared/TxHistory/RegularTxRow.jsx
- app/components/shared/TxHistory/StakeTxRow.jsx
- app/components/shared/TxHistory/TxHistory.module.css
This diff closes #2690 by adding some CSS tweaks to improve the fields organization in the TxHistory row.
**Regular view:**
**Small-width view:**
**Regular view:**
**Small-width view:**
> [transactions] fix: align transaction history page items

- README.md
Replace outdated modes of communication with a link to decred.org/community.
This matches dcrd and dcrwallet readme files.
> readme: Update contact section.

- app/actions/AccountMixerActions.js
- app/actions/ClientActions.js
- app/actions/VersionActions.js
- app/actions/WalletLoaderActions.js
- app/main.development.js
- app/main_dev/launch.js
- app/middleware/grpc/client.js
- app/wallet/daemon.js
- app/wallet/loader.js
- app/wallet/version.js
This PR depends on https://github.com/jrick/dcrwallet/tree/clientauth.
It adds tls client certificate into grpc client.
> Add grpc client tls certificate

- app/components/views/GetStartedPage/Settings/Settings.jsx
- app/components/views/SettingsPage/Settings.jsx
- app/components/views/SettingsPage/Settings.module.css
Remove .css which is no longer required.
Fixes #2724
> Fix dark mode heading colours on Settings tab.

- app/actions/ControlActions.js
- app/components/views/SecurityPage/SignMessage/SignMessage.jsx
- app/components/views/SecurityPage/SignMessage/SignMessageForm.jsx
- app/components/views/SecurityPage/ValidateAddress/ValidateAddress.jsx
- app/components/views/SecurityPage/ValidateAddress/hooks.js
- app/reducers/control.js
- app/selectors.js
This diff Closes #2700, which reported an unexpected behavior regarding address validation on security page.
I figured out that the addressValidation stuff was using the redux tree to manage the address validation state. But since we use the `useValidateAddress` on multiple components, each one behaving differently according to the `address`, it makes no sense to store the responses on the redux tree.
I thought of caching those address in the redux tree, but I think it's an overkill fo this feature, since there are not much cases we need to keep the validation responses stored.
Therefore, the solution was to keep the validation response as a state variable, and remove the address validation away from the redux tree.
> [security] fix: improve sign message and address validation handlers

- app/actions/ClientActions.js
This diff fixes the validation message issue reported on #2750 by passing the correct grpc key and cert to the `wallet.getMessageVerificationService` call.
Closes #2750
> [security] fix: add grpc keys for message verification service

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/components/SideBar/Logo/Logo.jsx
- app/components/SideBar/Logo/Logo.module.css
- app/components/SideBar/SideBar.jsx
- app/components/SideBar/hooks.js
- app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseTickets.jsx
- app/connectors/walletContainer.js
- app/containers/Wallet.js
- app/reducers/grpc.js
- app/selectors.js
- app/wallet/control.js
This PR depends on https://github.com/decred/dcrwallet/pull/1864.
It adds a peer count into decrediton's sidebar:
> Add peer count

- app/components/views/TransactionsPage/ReceiveTab/ReceivePage/ReceivePage.module.css
This minor diff fixes some styles and responsiveness on receive transactions page. Closes #2751.
**Before:**
**After:**
> [transactions] fix: receive transaction page visual adjustments

- app/actions/AccountMixerActions.js
- app/components/modals/AddMixerAccountsModal.jsx
- app/components/modals/hooks.js
- app/components/views/AccountsPage/Privacy/ConfigMixer/CreateNeededAccounts.jsx
This PR fixes account creation when some of the ones defined as "default" already exists. 
It also fixes privacy wallet recover, if wallet has no privacy utxo.
> cspp small fixes

- app/actions/DaemonActions.js
- app/actions/WalletLoaderActions.js
- app/components/views/GetStartedPage/OpenWallet/DiscoverAccounts.jsx
- app/components/views/GetStartedPage/OpenWallet/OpenWallet.jsx
- app/components/views/GetStartedPage/OpenWallet/PassphraseForm.jsx
- app/components/views/GetStartedPage/hooks.js
- app/reducers/walletLoader.js
- app/stateMachines/GetStartedStateMachine.js
This fixes a bug in SPV wallets where account discovery was broken on restored wallets which had more than one account. Discovery wasn't happening due to the passphrase not being passed along to the SpvSync.
It also modifies the get started sequence to ask for the private passphrase if account discovery hasn't completed yet, so that restarting a wallet restore after some blocks have been synced but before accounts have been discovered correctly finds the additional accounts.
Testing the passphrase request can be done by starting a wallet restore, then closing Decrediton during the initial block sync.
There are four different combinations for being presented the passphrase request view: 
- SPV Sync vs RPC Sync
- Wallet with vs without public passphrase
> Ask for passphrase if account discovery is needed

- app/actions/VSPActions.js
- app/containers/App.js
- app/selectors.js
This PR removes the warning of required props and update ticket fee status value, if vsp sync was successfully.
> Fix not updating feeStatus value after registering it successfully

- app/components/shared/TxHistory/StakeTxRow.jsx
- app/components/shared/TxHistory/TxHistory.jsx
- app/components/views/TicketsPage/MyTicketsTab/Page.jsx
This PR fixes staked tickets displaying their ``enterTimestamp`` instead of ``leaveTimestamp`` on overview screen.
Closes https://github.com/decred/decrediton/issues/2760.
> Show ticket vote time instead of purchase time on overview screen

- app/containers/Wallet.js
fixes #2759 
Righth now the polling time of the peer count is 1 minute, which probably caused #2759. 
This PR changes it to 10 sec, instead
> change polling time for peer count

- app/components/views/LNPage/WatchtowersTab/WatchtowersTab.jsx
- app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_PurchaseTickets/PurchaseTicketsAdvanced.js
- app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_PurchaseTickets/PurchaseTicketsQuickBar.js
- app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_StakePools/StakePoolsList.jsx
- app/i18n/docs/en/InfoModals/PurchaseTickets.md
Also includes one more string update - adding an apostrophe to watchtower session count.
eg. `Sessions: 10` rather than `Sessions 10`
Closes #2334
> Stakepool => VSP

- app/components/SideBar/Logo/Logo.jsx
- app/components/SideBar/Logo/Logo.module.css
- app/components/SideBar/MenuBottom/MenuBottom.module.css
- app/components/SideBar/MenuBottom/MenuBottomExpanded.jsx
- app/components/SideBar/SideBar.jsx
This diff improves the peers count a bit by moving it to the bottom of the sidebar, 
and showing it next to the latest block.
After:
---
Closes #2801
> sidebar: Improve peers count

- app/style/Loading.less
This also fixes the "Loading more transactions" panel.
> Background colour for "No more transactions" panel

- app/components/views/GetStartedPage/Settings/Settings.jsx
- app/components/views/ProposalDetailsPage/ProposalDetails.jsx
- app/components/views/SettingsPage/Settings.jsx
- app/index.js
- app/style/themes/darkTheme.js
- package.json
- yarn.lock
While working on decred/decrediton#2829 I noticed that decrediton is using different theme names as the default ones used in pi-ui & pigui, this is a bit problematic and may cause some styling bugs, as we check internally in pi-ui if default dark theme is used by checking the current theme name: `const isDarkTheme = themeName === "dark"`, and using different theme names as we do in decrediton would cause some pi-ui's components to show wrong styling.
So as solution https://github.com/decred/pi-ui/pull/304 exports two constants for default themes names: `DEFAULT_LIGHT_THEME_NAME` & `DEFAULT_DARK_THEME_NAME`, and uses them when it determines if default dark styling should be used internally in pi-ui's components. After this commit consumers of pi-ui lib would need to provide these default …
> pi-ui: use default themes' names & override toggle bg

- app/style/themes/darkTheme.js
It seems that recent PRs have removed @jholdstock's backup dark icon used in LN page (https://github.com/decred/decrediton/pull/2823) from master. This PR re-adds it.
> Re-add backup dark icon

- app/actions/TrezorActions.js
- package.json
- yarn.lock
This PR updates Trezor _connect_ library to version 8.1.16, supporting ``cancel`` method in order to make Trezor model One device get back to previous screen and cancel PIN setup.
Closes https://github.com/decred/decrediton/issues/2834.
> Fix Trezor modals cancel button

- package.json
This hooge PR gets `yarn package-linux` to create an AppImage file which will allow GNOME users to avoid having to launch Decrediton via CLI.
Closes https://github.com/decred/decrediton/issues/2277 and https://github.com/decred/decrediton/issues/2472.
> Add AppImage build target for Linux

- app/components/SideBar/AccountsList/AccountsList.jsx
- app/components/SideBar/AccountsList/AccountsList.module.css
- app/components/SideBar/MenuBottom/MenuBottomExpanded.jsx
- app/components/SideBar/SideBar.jsx
- app/components/SideBar/hooks.js
This PR adds the possibility of scrolling through the accounts listed in the sidebar by rolling the scroll wheel when the list is visible.
Closes https://github.com/decred/decrediton/issues/2870.
> Add scroll to browse sidebar accounts

- app/components/views/GetStartedPage/PreCreateWallet/PreCreateWallet.jsx
- app/components/views/GetStartedPage/WalletSelection/Form.jsx
- app/components/views/GetStartedPage/WalletSelection/WalletSelection.jsx
- app/constants/config.js
- app/hooks/useDaemonStartup.js
- app/index.js
- app/selectors.js
The limit was imposed to protect the UI in case of a large number of wallets, but actually the UI handles large numbers of wallets pretty well.
Closes #2186
> Remove max wallets limit.

- app/i18n/po/decrediton.pt.po
- app/i18n/pot/decrediton.pot
- app/i18n/translations/original.json
`Peers Count: 8` is not correct - we should either go with `Peers: 8` or `Peer Count: 8`.
I have gone with `Peers: 8` because the word "count" seems redundant.
> Fix peer count grammar.

- app/components/views/TicketsPage/VSPTicketsStatusTab/Page.jsx
Closes #2858 
Now, if a ticket is errored the sync button is visible independently of the ticket filter.
> [Tickets] Show "sync" button on fee error automatically

- app/components/views/TransactionsPage/SendTab/SendOutputRow/SendOutputRow.module.css
> Improve disabled `plus` button bg color in send funds

- app/actions/GovernanceActions.js
- app/components/views/GovernancePage/Proposals/ProposalsFilter/ProposalsFilter.jsx
- app/components/views/GovernancePage/Proposals/ProposalsFilter/ProposalsFilter.module.css
- app/components/views/GovernancePage/Proposals/ProposalsList/ProposalsList.jsx
- app/components/views/GovernancePage/Proposals/ProposalsList/ProposalsList.module.css
- app/components/views/GovernancePage/Proposals/ProposalsTab.jsx
- app/components/views/GovernancePage/Proposals/hooks.js
This diff adds the possibility to filter finished voting proposals by its approved or rejected status.
I think we cannot filter proposals by timestamp, since timestamp filtering is not implemented on politeia, but we can add some filters into the **Finished Vote** tab, so we could filter props by **Approved** and **Rejected** status.
Closes #2786
> [governance] "Finished Vote" tab filters

- app/components/views/TransactionsPage/SendTab/SendOutputRow/SendOutputRow.module.css
This commit adds a tiny css nit which was missed in #2908 - showing `not-allowed` cursor to give a better ux for
a disabled button.
Screenshot:
> Add `cursor: not-allowed` to `plus` button in send funds

- app/components/views/GovernancePage/Proposals/ProposalsListItem/ProposalsListItem.jsx
- app/components/views/GovernancePage/Proposals/ProposalsListItem/ProposalsListItem.module.css
This diff fixes a bug in ProposalListItem which showed incorrect dot color for proposals which finished voting.
After this commit, voting proposals' dots will be green if user voted yes, red if user voted no and grey if user
didn't vote yet.
Regarding proposals which finished voting, if they passed they show green, red if declined & grey if quorum not met. 
---
Closes #2905
> ProposalListItem: Polish proposals dot colors.

- app/components/SideBar/MenuBottom/MenuBottom.module.css
- app/components/SideBar/MenuBottom/MenuBottomExpanded.jsx
- app/components/views/GovernancePage/Proposals/PoliteiaDisabled.jsx
- app/components/views/GovernancePage/Proposals/ProposalsTab.module.css
- app/i18n/po/decrediton.de.po
- app/i18n/po/decrediton.es.po
- app/i18n/po/decrediton.fr.po
- app/i18n/po/decrediton.ja.po
- app/i18n/po/decrediton.pt.po
- app/i18n/po/decrediton.zh.po
- app/i18n/pot/decrediton.pot
- app/i18n/translations/original.json
- app/style/MiscComponents.less
Was previously being displayed as a square because the icon was cropped. Making the height and width match the background-size ensures the full icon is displayed
---
- Remove hardcoded "left" from the SPV icon. Use "margin-left: auto" instead.
- Revert from pi-ui tooltip to Decrediton tooltip. pi-ui tooltip is distinctly different to other tooltips, and forces the "SPV Mode" string to appear on two lines due to a bug.
There is already another issue open which should include migrating this to pi-ui with the correct styling #2512
---
> Assorted minor fixes

- app/actions/TrezorActions.js
- app/components/views/TrezorPage/ConfigSections.js
- app/components/views/TrezorPage/FirmwareUpdate.js
- app/connectors/trezor.js
- app/main.development.js
- app/main_dev/ipc.js
- app/reducers/trezor.js
- app/selectors.js
Part of #2681
We are unable to update firmware from TrezorActions.js. This is believed
to be due to the size of the firmware and the limitations of this
electron child process. We send the firmware to the main process to push
to the device. The main process uses a temporary connection to trezor in
order to accomplish this.
> TrezorActions: Allow updating firmware.

- app/actions/DaemonActions.js
- app/actions/GovernanceActions.js
- app/actions/SettingsActions.js
- app/middleware/politeiaapi.js
- app/wallet/politeia.js
This diff fixes #2914 by cleaning up csrf token on network switch, and changing actions order in order to 
ensure that we save new politeiaURL before fetching token inventory from politeia.
> [Settings] Cleanup politeia's network specific csrf on network switch

- app/actions/TrezorActions.js
- app/components/views/TrezorPage/ConfigSections.js
- app/components/views/TrezorPage/FirmwareUpdate.js
- app/connectors/trezor.js
- app/main.development.js
- app/main_dev/ipc.js
- app/package.json
- app/reducers/trezor.js
- app/selectors.js
- app/yarn.lock
- package.json
- yarn.lock
We are unable to update firmware from TrezorActions.js. This is believed
to be due to the size of the firmware and the limitations of this
electron child process. We send the firmware to the main process to push
to the device. The main process uses a temporary connection to trezor in
order to accomplish this.
Send path to ipc.
Better handle update firmware failures.
Move connect to app/node_modules.
For some reason importing connect in main_dev/ipc.js was not working
when building for release. Moving connect fixes it...
> TrezorActions: Allow updating firmware v2.

- app/actions/ControlActions.js
- app/components/views/PrivacyPage/Privacy/hooks.js
- app/selectors.js
This diff fixes an issue caused by recent change which deleted the `getMixedAccountBranch` selector and used `0` as mixed account branch.  This commit re-adds the selector and uses it when calling the wallet.
> [Purchase ticket] fix missing mixedAccountBranch selector

- app/actions/ControlActions.js
This PR prevents throwing an error if no peers were found.
> Check if peers were found

- app/main_dev/launch.js
It's not needed for dcrlnd and runs on a very commonly used port, which might
interfere with existing services.
Close #2797
> [LN] Disable rest service

- app/actions/ControlActions.js
- app/reducers/control.js
Closes #2950 
I could reproduce issue #2950 in win10 in VirtualBox. I found that sometimes responses for `constructTransaction` requests don't arrive in the same order as they requested.
My solution is to save the last request and cancel it before the next one if it is necessary.
> [tx] avoid race condition in tx send view

- app/components/views/PrivacyPage/Privacy/hooks.js
@jholdstock found this issue: "I cant seem to open the Privacy tab on a brand new wallet. I think its only working on wallets which already have privacy enabled"
```
hooks.js:50 Uncaught TypeError: Cannot read property 'spendable' of undefined
at usePrivacy (hooks.js:50)
at Privacy (Privacy.jsx:25)
at renderWithHooks (react-dom.development.js:14826)
at mountIndeterminateComponent (react-dom.development.js:17506)
at beginWork (react-dom.development.js:18630)
at HTMLUnknownElement.callCallback (react-dom.development.js:189)
at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
at invokeGuardedCallback (react-dom.development.js:293)
at beginWork$1 (react-dom.development.js:23235)
at performUnitOfWork (react-dom.development.js:22189)
```
> Fix Privacy tab on a brand new wallet

- app/reducers/snackbar.js
As of #2983, `RUNACCOUNTMIXER_INSUFFICIENT_BALANCE` is no longer dispatched, so it can be removed. Also removes a redundant i18n string so it wont be translated unnecessarily.
> Remove redundant insufficient balance action.

- app/components/views/PrivacyPage/Privacy/hooks.js
This diff fixes too many getbalance requests being sent when visiting privacy page by using
`useMountEffect` hook to call the `getMixerAcctsSpendableBalances` action only once - on mount.
> [privacy] fix: fetch spendable account balances only once

- app/components/shared/TxHistory/TxHistory.jsx
- app/helpers/dateFormat.js
- app/selectors.js
This diff uses `Intl.DateTimeFormat` to achieve custom date format (`23hour` date time - `00:29` instead on `24:29`) which isn't possible with latest `react-intl` versions.
See https://github.com/decred/decrediton/issues/2968#issuecomment-734437460 which explains the suggestion to work with `Intl.DateTimeFormat` as a solution.  
---
Closes #2968
> [transaction] Use native `Intl.DateTimeFormat` to format tx timestamp

- app/actions/TransactionActions.js
This diff dispatches `checkUnmixedAccountBalance` action, to update the mixer accounts balances and error
state in privacy page.
Also, it dispatches `getMixerAcctsSpendableBalances` to update the balances in the privacy/mixer page when new transaction received.
Closes #2992
> [privacy] Update mixer balances when new transaction recieved

- app/components/modals/CantCloseModals/AccountMixerRunningModal.jsx
- app/components/modals/CantCloseModals/CantCloseModals.jsx
- app/components/modals/CantCloseModals/PurchasingTicketsModal.jsx
- app/components/modals/CantCloseModals/hooks.js
- app/selectors.js
This PR adds the running indicator selector into the can't close selector.
This way decrediton will not allowed to be closed if it is perfoming any action represented by the running indicator: Ticket auto buyer, running mixer or purchasing tickets
> Add running indicator on cant close selector

- app/components/shared/TxHistory/RegularTxRow.jsx
The icon for Send is red, for Receive is green, but both had a tooltip which just said "Transaction". 
Now they have "Sent" or "Received".
> Distinguish sends/receives in tx icon tooltips

- app/components/views/SettingsPage/LogsTab/Page.jsx
I noticed that LN logs in the Logs tab are only visible during the LN start process. After that, they disappear. This diff fixes it.
> [Logs] missing dcrlnd logs

- app/actions/ClientActions.js
This diff handle rare case where treasury unspent balance info not available which caused `getTreasuryBalance` action in `ClientActions.js` to throw: `TypeError: Cannot read property 'toString' of undefined`.
As a fix I added a tiny check to make sure that the treasury info is available before trying to parse it.    
*Note*: I wasn't able to consistently reproduce the error, I had to refresh decrediton several times with `ctrl+r` in different pages/stages and jump between testnet/mainnet for it to show up.
Closes #3011
> fix: 'toString' of undefined console error

- app/components/views/GetStartedPage/GetStarted.module.css
#3051 and #3048 both included fixes for release note list styling and they didnt merge well.
> Resolve double <li> padding fix in release note

- app/components/shared/TxHistory/TxHistory.module.css
> [TxHistory] Use `monospace` font for dates & improve alignment

- app/components/views/TicketsPage/PurchaseTab/PurchaseTab.module.css
I noticed a CSS misalignment on the Purchase Tickets form in small width. This diff fixes it.
> [CSS] Purchase Tickets misalignment

- app/components/shared/TxHistory/TxHistory.module.css
This diff fixes a display bug which was introduced by #3090 - see screenshots below:
Before:
After:
> fix: TxHistory broken layout in Transactions History Page

- app/components/views/GetStartedPage/CreateWalletPage/CreateWalletPage.jsx
- app/components/views/GetStartedPage/GetStarted.jsx
- app/components/views/GetStartedPage/GetStartedMachinePage.jsx
- app/components/views/GetStartedPage/GetStartedPage.jsx
- app/components/views/GetStartedPage/hooks.js
- app/hooks/useDaemonStartup.js
This diff hides the top nav menu links `Settings` & `Logs` when navigating to a nested page in the
wallet creation or wallet restore flows.
Closes #3079
> GetStarted: Hide top nav menu links in nested pages

- app/components/shared/Collapse.jsx
- app/components/shared/index.js
- app/components/shared/shared.module.css
- app/components/views/GetStartedPage/GetStarted.module.css
- app/components/views/GetStartedPage/PreCreateWallet/CreateWalletForm.jsx
This diff adds tooltips for Watch Only and Trezor, since Privacy will be removed by #3020, and adds an "Advanced Options" label.
Closes #3020
> [get-started] style: improve messaging on restore wallet form

- app/config.js
- app/constants/config.js
This PR moves how we start our wallet initial config, based on how we start our global config, for keeping consistency and simplicity.
It moves the constants initial value to our constant file and initialize them.
> move wallet config initial values to constants

- app/actions/AccountMixerActions.js
- app/actions/ClientActions.js
- app/components/views/GetStartedPage/PreCreateWallet/CreateWalletForm.jsx
- app/components/views/GetStartedPage/PreCreateWallet/PreCreateWallet.jsx
- app/components/views/GetStartedPage/SetMixedAcctPage/SetMixedAcctPage.jsx
- app/components/views/GetStartedPage/hooks.js
- app/constants/Decrediton.js
- app/hooks/useAccounts.js
- app/stateMachines/GetStartedStateMachine.js
This diff deletes current `Privacy` toggle from wallet restore page and auto detects mixed wallet by 
checking for coinjoin outputs on startup.
---
Based on #3029 
Closes #2907
> [privacy] Auto-detect mixed wallet 

- app/components/shared/SendTransaction/hooks.js
- app/components/views/PrivacyPage/Privacy/hooks.js
- app/containers/Wallet.js
After some profiling, I found these issues:
- leaving the app for some time - or refresh it by F5 or close wallet and reopen it - the `GETPEERINFO_ATTEMPT/GETPEERINFO_SUCCESS` requests pile up (**update**: #2901 resolves this part of the issue)
- the `Privacy` and the `SendTransaction` components are redrawn after every `GETPEERINFO_ATTEMPT/GETPEERINFO_SUCCESS` request despite the redux state did not change at all.
- these two factors can increase CPU usage quite high after some time.
This PR fixes this.
> Redraw optimization

- app/components/views/GovernancePage/Proposals/ProposalsTab.module.css
In the governance page, this PR fixes the navigation bar that has been broken due to a larger translation to German of its introductory text. 
Closes https://github.com/decred/decrediton/issues/3015.
> Fix broken nav bar in governance page

- app/actions/LNActions.js
- app/middleware/ln/client.js
This makes the connection procedure to the underlying dcrlnd node services more
reliable by trying again when an EUNIMPLEMENTED error is returned.
Due to the gRPC server being restarted after an unlock, depending on the exact
timings, we might still connect to the wallet unlocker service so trying to
use the general services would fail.
While this isn't usually an issue today, it will be needed when switching to the grpc-js library in the future.
> [LN] Improve connection procedure

- app/actions/VSPActions.js
- app/components/views/GetStartedPage/ProcessManagedTickets/ProcessManagedTickets.jsx
- app/components/views/GetStartedPage/ProcessManagedTickets/ProcessUnmanagedTickets.module.css
- app/components/views/GetStartedPage/hooks.js
- app/hooks/useDaemonStartup.js
- app/stateMachines/GetStartedStateMachine.js
- app/wallet/control.js
This PR changes how we call processManaged tickets, to be called before processUnmanagedTickets and also to be called on every startup if the wallet have live tickets
> Call processManageTickets on every startup if having live tickets

- app/components/shared/Subtitle/Subtitle.module.css
- app/components/views/PrivacyPage/SecurityPage/SecurityPage.module.css
- app/components/views/PrivacyPage/SecurityPage/ValidateAddress/ValidateAddressForm.module.css
Closes #3147 and fix two more misalignments on smaller screens:
> [CSS] fix security page misalignments

- app/actions/GovernanceActions.js
- app/components/views/GovernancePage/Proposals/ProposalsListItem/ProposalsListItem.jsx
- app/components/views/GovernancePage/Proposals/ProposalsListItem/ProposalsListItem.module.css
- app/components/views/ProposalDetailsPage/ProposalDetails.jsx
- app/components/views/ProposalDetailsPage/ProposalDetails.module.css
- app/components/views/ProposalDetailsPage/ProposalDetailsPage.jsx
- app/components/views/ProposalDetailsPage/hooks.js
This PR closes https://github.com/decred/decrediton/issues/3108 through the following resolutions:
- Addition of **RFP** and **Proposed for RFP** flags in the respective list items.
- In a proposal marked with the **Proposed for RFP** flag, a Politeia link to the respective RFP has been added.
- Some changes in rejected items:
- All rejected list items now have a red left border.
- The tiny circle indicates if the proposal had no quorum (gray), was declined (red), or would be approved (green).
- Message below the vote bar indicates the rejection reason and obeys the order of precedence:
1 - Quorum Not Met;
2 - Declined;
3 - Request Not Chosen (Proposed for RFP, only).
> Add RFP flag to proposals list

- app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseTickets.jsx
After typing manually a value into ticket number input on the purchase tickets page, the increment button or the up cursor key adds "1" char to the tail of the value instead of incrementing it. 
This diff fixes it by converting the ticket number to Integer before incrementing.
> [Purchase Tickets] fix ticket number input increment button

- app/actions/GovernanceActions.js
- app/actions/SettingsActions.js
- app/middleware/politeiaapi.js
- app/wallet/politeia.js
This commit cleans logic related to storing and attaching CSRF tokens
when communicating with Politeia.
Closes #3117
> [governance] Remove politeia CSRF tokens

- app/main.development.js
- app/main_dev/externalRequests.js
- package.json
- yarn.lock
I set the `allowRendererProcessReuse` flag to `false` that reverts to the old behavior. It is functional for now, but this could be just a temporary solution until Electron 11.
> Bump to Electron 9.4.0

- app/components/views/TicketsPage/PurchaseTab/hooks.js
- app/reducers/snackbar.js
Closes  #3181
Also, I've added snackbar notifications for the new auto buyer's start and stop events similar to the legacy auto buyer's events. Thus it is a little bit easier to follow what is happening in the background.
> Disable autobuy when changing VSP modes

- app/components/SideBar/AccountsList/AccountsList.jsx
- app/components/SideBar/AccountsList/AccountsList.module.css
- app/components/SideBar/SideBar.jsx
- app/components/SideBar/hooks.js
- app/components/views/AccountsPage/Accounts/AccountRow/AccountDetails.jsx
- app/components/views/AccountsPage/Accounts/AccountRow/AccountRow.jsx
- app/components/views/AccountsPage/Accounts/AccountRow/AccountRowContent.jsx
- app/components/views/AccountsPage/Accounts/Accounts.jsx
- app/components/views/AccountsPage/Accounts/Accounts.module.css
- app/components/views/AccountsPage/Accounts/AccountsList.jsx
- app/components/views/AccountsPage/Accounts/hooks.js
Show mixed/change accounts icon in:
[x]  Accounts list.
[x]  Side bar.
Closes #3212.
> [privacy] mixed & change accounts icons in accounts list & side bar.

- app/components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfo.module.css
According to our [design specs](https://xd.adobe.com/spec/0b2049ed-80d2-4978-703a-72ad6ceea744-7d11/screen/374a754d-5ee4-4de1-b7e8-f3d1467ca3eb/specs/), the div showing tickets details in "Purchase Tickets" tab shouldn't have the property ``border-radius`` set. Currently, it's set to 5px, which causes some misalignments when expanding the div below. This PR fixes that.
> Remove border-radius from tickets details

- app/style/themes/lightTheme.js
Wrong `.svg` icon name was used for proposals refresh icon in light theme.
After:
Fixes #3217.
> [governance] Fix light theme refresh proposals icon.

- app/components/shared/TxHistory/TxHistory.module.css
- app/components/views/TransactionsPage/HistoryTab/HistoryPage/HistoryPage.module.css
> [Tx History] Improve tx history layout on smaller screens

- app/actions/TrezorActions.js
- app/actions/WalletLoaderActions.js
- app/helpers/trezor.js
- app/reducers/trezor.js
This ensures that session.connect is called when changing wallets, which
clears the password data stored on the Trezor, allowing switching trezor
wallets with password enabled.
> WalletLoaderActions: Clear trezor values on close.

- app/components/buttons/EyeFilterMenu/EyeFilterMenu.jsx
- app/components/views/TransactionsPage/HistoryTab/HistoryPage/HistoryPage.jsx
- app/components/views/TransactionsPage/HistoryTab/HistoryTab.jsx
- app/components/views/TransactionsPage/HistoryTab/helpers.js
- app/index.js
- app/reducers/grpc.js
- app/selectors.js
In this diff, I've added support for filtering transactions by multiple types at the same time. For example, when the user selects `sent` and `received`, it lists all the sent and received transactions: 
This feature closes #3180 because if just the `sent`, `received`, and `ticket fee` options are selected, it lists all "normal" transactions but mixed:
> [Tx History] filter txs by multiple type at once

- app/components/views/GetStartedPage/hooks.js
During wallet restore if syncing vsp tickets time out, the rejected promise is unhandled and the wallet restoring process stop. This diff fixes this.
> [Wallet restore] Unhandled rejected promise

- app/components/views/TransactionsPage/HistoryTab/HistoryTab.jsx
- app/selectors.js
After #3194, the `Filter by address`, list direction, and the amount range tx filters not working properly. 
Also, I noticed that the `All` option doesn't list `Mixed` transactions.
This PR fixes these issues.
> [Tx history] fix filter

- app/containers/App.js
- app/main_dev/templates.js
Closes https://github.com/decred/decrediton/issues/3228.
According to [Electron docs](https://github.com/electron/electron/blob/v9.4.0/docs/api/web-contents.md#contentssendchannel-args), since version 9, ``webContents`` can serialize only a [strict set of types](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#supported_types) that no more includes specific Electron ones. Thus, it's possible to bypass this limitation by using ``ipcRenderer.send`` method to send a message from the renderer process to the main process, instead of injecting the event emitter of the last through a callback function argument.
> Fix GUI reloading through menu bar and F5 shortcut

- app/components/SideBar/Logo/Logo.module.css
- app/components/shared/SendTransaction/Form.jsx
- app/components/shared/SendTransaction/SendTransaction.jsx
- app/components/shared/SendTransaction/hooks.js
- app/components/views/PrivacyPage/Privacy/Privacy.jsx
- app/components/views/PrivacyPage/Privacy/PrivacyContent.jsx
- app/components/views/PrivacyPage/Privacy/hooks.js
- app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_PurchaseTickets/Form.js
- app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_TicketAutoBuyer/Form.js
- app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_Tickets.js
- app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/hooks.js
- app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/index.js
- app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/Page.jsx
- app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseForm.jsx
- app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseTickets.jsx
- app/components/views/TicketsPage/PurchaseTab/TicketAutoBuyer/Form.jsx
- app/components/views/TicketsPage/PurchaseTab/TicketAutoBuyer/TicketAutoBuyer.jsx
- app/components/views/TicketsPage/PurchaseTab/hooks.js
To avoid issues and to help UX a bit, we should be disallowing various features to be run at the same time.
Currently when mixer, autobuyer or ticket purchases are running we disable all the other buttons as well as the send transactions.
I've also included a change to the sidebar running indicator css to remove the animation that has been shown to be really bad for performance.
> [various] Disable buttons when mixing, autobuyer or purchase tickets running

- app/wallet/control.js
We've had various reports of legacy ticket purchases not having Pool Address and Pool Fees populated which resulted in malformed legacy VSP tickets.  This is a final sanity check that should catch any that are attempted.  While this won't fix what's causing the core problem, it will stop them from happening until it's identified.
> [tickets] Add sanity check for legacy purchase tickets

- app/actions/VSPActions.js
- app/components/views/GetStartedPage/ProcessManagedTickets/ProcessManagedTickets.jsx
- app/components/views/GetStartedPage/ProcessUnmanagedTickets/ProcessUnmanagedTickets.jsx
- app/components/views/GetStartedPage/hooks.js
- app/hooks/useDaemonStartup.js
- app/index.js
- app/reducers/snackbar.js
- app/reducers/vsp.js
- app/selectors.js
- app/stateMachines/GetStartedStateMachine.js
A user reported that no error was shown after a bad passphrase was entered for the process managed tickets modal.  This should fix this.
> [launcher] Show error and retry on bad passphrase for ProcessManaged/ProcessUnmanagedTickets

- app/components/shared/TabsHeader/TabsHeader.jsx
- app/components/shared/TabsHeader/TabsHeader.module.css
- app/components/views/GovernancePage/Proposals/ProposalsFilter/ProposalsFilter.module.css
- app/components/views/HomePage/HomePage.jsx
- app/components/views/HomePage/HomePage.module.css
This improves the alignment of TabHeader component which used is in the finished proposals list.
It Replaces `TabsHeader`'s `tabsWrapperClassName` prop with a new `className` prop which is used to override
the default absolute position css attributes.
With that I was able to position the tabs in `HomePage` and  `ProposalsFilter` components differently.
> TabsHeader: Fix wrong aligned tabs in finished propsoals list.

- app/actions/ControlActions.js
- app/reducers/control.js
- app/reducers/snackbar.js
Due to utxos requirements for ticket purchasing, sometimes when a user requests more tickets than they are able to construct it only purchases as many as it's able to.  This message alerts the user to this situation.
> [tickets] Show different message when less tickets bought

- app/components/views/GetStartedPage/CreateWalletPage/CreateWalletPage.jsx
- app/components/views/GetStartedPage/CreateWalletPage/ExistingSeed/ExistingSeed.jsx
- app/stateMachines/CreateWalletStateMachine.js
- test/unit/components/views/GetStaredPage/CreateWallet.spec.js
closes #3235
Now the `Create Wallet` button reacts to invalid inputs properly. 
After the button was enabled, it is toggled to disabled state when:
- passphrases cleared or,
- passphrases do not match or,
- seeds are not valid or,
- one or more seeds are deleted
Automated tests were expanded to cover this new behavior.
> Improve error handling on wallet create and restore views

- app/actions/AccountMixerActions.js
After creating default mixing accounts on the privacy page the `Unmixed Balance` and the `Mixed Balance` value is not 0.00 DCR, but the default account's value:
Closing and reopening the privacy page updates the balances to the correct value (0.00 DCR)
This diff fixes this issue.
> fix initial mixing account balances on the privacy page

- app/actions/SettingsActions.js
- app/main.development.js
- app/main_dev/templates.js
This PR allows runtime translation of Electron menus - top menu bar and context menu - when setting a different locale on the Settings page.
Closes https://github.com/decred/decrediton/issues/3132.
> Allow runtime translation of Electron menus

- app/containers/App.js
- app/containers/Wallet.jsx
- package.json
- yarn.lock
As discussed in Decrediton room in Matrix, according to @alexlyp:
> (...) wondering if you guys could take a look at a performance issue i've noticed recently. was running tip decrediton and noticed a bit of CPU churn after starting the mixer (on the privacy page). I'm thinking it could be the gifs on that page, though i still see the CPU bump when toggling to a different page (transactions or tickets, etc)
and @vctt94:
> I noticed my CPU struggling more on latest master, as well
It seems that our recent changes mainly in the privacy page resonated in some lack of performance. After investigating, we realized high CPU usage due to ``react-router-transition`` expensive transitions and ``menuMixer.svg`` CSS animation.
Below, the performance of three use cases, all of them following the …
> Improve UI performance

- app/actions/ControlActions.js
- app/components/shared/SendTransaction/SendTransaction.jsx
- app/components/shared/SendTransaction/hooks.js
- app/selectors.js
Closes https://github.com/decred/decrediton/issues/3188 by removing ``getNextAddressAttempt`` redundant call. This issue can be reproduced by trying to send from _mixed_ to _unmixed_ accounts when having insufficient funds to do that. As ``nextAddress`` was updated, ``useEffect`` hook in ``app/components/shared/SendTransaction/SendTransaction.jsx`` tended to run indefinitely and new outputs were generated based on that new address, so the transaction was constructed generating a new address again. There's no need of calling ``getNextAddressAttempt``, for it's already called every time a new destination account is selected. It means that ``nextAddress`` is always synced with the selected destination account (``nextAddressAccount``).
> Fix flickering insufficient funds message in "Send" tab

- app/components/shared/VericalAccordion/VerticalAccordion.jsx
- app/components/views/AccountsPage/Accounts/AccountRow/AccountRowContent.jsx
- app/components/views/AccountsPage/Accounts/AccountRow/RenameAccount.jsx
- app/components/views/AccountsPage/Accounts/AccountRow/index.js
- app/components/views/AccountsPage/Accounts/Accounts.module.css
- app/components/views/AccountsPage/Accounts/AccountsList.jsx
- app/components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfo.module.css
- app/components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfoDisplay.jsx
- app/style/AccountRow.less
- app/style/AccountsPage.less
- app/style/PurchaseTickets.less
This gets rid of two more `.less` files: `AccountRow.less`, `AccountsPage.less`.
Also, it adds new `activeArrowClassName` prop to `VerticalAccordion` to make it possible for consumers
to custom style active arrows.
Part of #2439 - and another good example why local encapsulate css modules makes our app much more readable, 
predictable, debuggable & flexible.
> [css modules] Ditch AccountRow & AccountsPage .less files.

- app/components/layout/StandaloneHeader.js
- app/components/layout/TitleHeader/TitleHeader.jsx
- app/components/views/AccountsPage/AccountsPage.jsx
- app/components/views/GovernancePage/GovernancePage.jsx
- app/components/views/LNPage/ConnectPage.js
- app/components/views/LNPage/index.js
- app/components/views/ListUtxo/ListUtxo.jsx
- app/components/views/PrivacyPage/PrivacyPage.jsx
- app/components/views/ProposalDetailsPage/helpers/Header.jsx
- app/components/views/SettingsPage/SettingsPage.jsx
- app/components/views/TicketsPage/TicketsPage.jsx
- app/components/views/TransactionPage/TransactionHeader/TransactionHeader.jsx
- app/components/views/TransactionsPage/TransactionsPage.jsx
- app/components/views/TrezorPage/TrezorPage.jsx
- app/constants/Decrediton.js
This PR adds several constants to ``app/constants/Decrediton.js`` to increase verbosity and avoid explicit strings throughout our code. These constants represent CSS classes that place the right header icon depending on the page at ``app/components/layout/TitleHeader/TitleHeader.module.css``.
Closes https://github.com/decred/decrediton/issues/3295.
> Add icon type constants

- app/actions/TransactionActions.js
There were pretty constant `wallet.TransactionSummary(XXXX): item does not exist` errors being logged, but no noticeable problems in the UI.  Apparently the ticket spender hash that was being requested here was reversed so the tx was thought to be missing.
> Reverse txhash to avoid missing Transaction errors

- app/containers/App/App.jsx
- app/containers/hooks/useApp.js
This fixes a bug in the App container when can close check listener didn't update when provided canClose updated.
This also re-arranges the App container (see second commit) and moves all state related logic to the `useApp` custom hook.
> App container: fix ipcRenderer listeners not updating bug.

- app/actions/ControlActions.js
- app/components/modals/hooks.js
- app/reducers/control.js
This adds two control redux actions, to switch `modalVisible` redux flag on & off when modals are visible
or hidden.
Closes #3338.
> Reintroduce blur effect when modals are visible.

- app/components/SideBar/MenuBottom/MenuBottom.module.css
- app/components/buttons/RescanButton/RescanButton.module.css
- app/components/layout/StandaloneHeader/StandaloneHeader.module.css
- app/components/layout/StandalonePageBody/StandalonePageBody.module.css
- app/components/layout/TabbedPage/TabbedPage.module.css
- app/components/modals/Modals.module.css
- app/components/shared/TxHistory/TxHistory.module.css
- app/components/views/AccountsPage/Accounts/Accounts.module.css
- app/components/views/GetStartedPage/GetStarted.module.css
- app/components/views/GovernancePage/Blockchain/AgendaOverview/Overview.module.css
- app/components/views/GovernancePage/Blockchain/VotingPrefs.module.css
- app/components/views/GovernancePage/Proposals/ProposalsFilter/ProposalsFilter.module.css
- app/components/views/GovernancePage/Proposals/ProposalsListItem/ProposalsListItem.jsx
- app/components/views/GovernancePage/Proposals/ProposalsListItem/ProposalsListItem.module.css
- app/components/views/GovernancePage/Proposals/ProposalsTab.module.css
- app/components/views/LNPage/WatchtowersTab/AddWatchtower/AddWatchtower.module.css
- app/components/views/ProposalDetailsPage/ProposalDetails.module.css
- app/components/views/ProposalDetailsPage/helpers/EligibleTickets/EligibleTickets.module.css
- app/components/views/SettingsPage/SettingsTab/Settings.module.css
- app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_StakePools/StakePools.module.css
- app/components/views/TransactionPage/TransactionContent/TransactionContent.module.css
- app/components/views/TransactionPage/TransactionHeader/TransactionHeader.module.css
- app/components/views/TransactionsPage/ExportTab/ExportPage/ExportPage.module.css
- app/components/views/TransactionsPage/ReceiveTab/ReceivePage/QRCodeModal/QRCodeModal.module.css
- app/components/views/TransactionsPage/ReceiveTab/ReceivePage/ReceivePage.module.css
- app/components/views/TransactionsPage/SendTab/SendForm.module.css
- app/style/main.css
This gets rid of a styling hack which was used to resolve a global styling conflict between `pi-ui` and
`decrediton`.
Before this commit:
```
/* TODO: delete box-sizing: content-box;
// I added this ugly `:not` workaround to be able to skip pi-ui's classes
// which are prefixed with 'styles_'.
// Ideally we should use `* { box-sizing: inherit; } and html { box-sizing: border-box }`(already done in pi-ui)
// we shouldn't override it in a global level - we should take care of this while migrating this file to a css module.*/
*:not([class^="styles_"]),
*:not([class^="styles_"])::before,
*:not([class^="styles_"])::after {
box-sizing: content-box;
}
[class^="styles_"] > * {
box-sizing: inherit;
}
```
As mentioned in the code comment above; before this diff decrediton's needed `box-sizing: …
> Align decrediton's global `box-sizing` property with `pi-ui`.

- app/components/views/HomePage/HomePage.module.css
- app/components/views/HomePage/Tabs/BalanceTab/BalanceTab.jsx
> Improve balance overview tooltip's alignment & width.

- app/index.js
- app/style/main.css
- app/style/themes/index.js
- app/style/themes/sharedTheme.js
This replaces legacy css variables used to be in `main.css` with a new `app/style/themes/sharedTheme.js`
which is provided using `pi-ui`'s `ThemeProvider`.
> Replace main.css global vars with sharedTheme.

- app/components/shared/TxHistory/LiveStakeTxRow.jsx
- app/components/shared/TxHistory/TxHistory.module.css
> overview: fix pending indicator minor styling bug.

- app/components/shared/TxHistory/TxHistory.module.css
As follow up for #3347;  this adds missing `!important` in `TxHistory` styling to fix unmined ticket alignment. 
Before:
After:
> [overview] TxHistory: fix unmined ticket alignement.

- webpack.config.development.js
- webpack.config.production.js
Our webpack 4.* config didn't work as is becuase of `css-loader` moving `localIdentName` option to be under `modules` instead of directly under options - see https://stackoverflow.com/a/57903310/8148239:
webpack 4:
```
{
loader: "css-loader",
options: {
sourceMap: true,
importLoaders: 1,
localIdentName: "[local]__[hash:base64:5]",
modules: true
}
}
```
webpack 5:
```
"style-loader",
{
loader: "css-loader",
options: {
sourceMap: true,
importLoaders: 1,
modules: {
localIdentName: "[local]__[hash:base64:5]"
}
}
}
```
> Fix webpack css modules & pure css configs.

- app/components/views/AccountsPage/Accounts/AccountRow/AccountDetails.jsx
- app/components/views/HomePage/Tabs/BalanceTab/BalanceTab.jsx
- app/i18n/docs/en/InfoModals/BalanceOverview.md
This diff implements @davecgh idea from matrix:
I wonder if the "Immature Stake Gen" label should be changed to "Immature Vote Returns" or similar.
I suspect "stake gen" is not at all obvious to 99.9999% of people who aren't devs.
> Change "Immature Stake Generation" label to "Immature Staking Returns"

- app/main.development.js
When going to Logs on the Launcher or under Settings was causing a crash due to a change to winston logging transports.
> [logger] Fix log crash from winston upgrade

- app/actions/GovernanceActions.js
- app/components/views/ProposalDetailsPage/ProposalDetails.jsx
- app/components/views/ProposalDetailsPage/ProposalDetailsPage.jsx
- app/components/views/ProposalDetailsPage/utils.js
- app/constants/governance.js
- app/helpers/index.js
- app/helpers/politeia.js
This is a small followup after #3345 moving proposal body parsing logic from component
to governance redux actions layer. 
After this commit `ProposalDetailsPage` gets the proposal's body as part objects returned from the custom hook.
> [governance] parse & store proposal's body on redux level.

- app/components/views/TransactionPage/TransactionContent/TransactionContent.jsx
- app/selectors.js
I found that the output in the redeeming transactions on DEX is generated as internal. In Decrediton during the tx normalizing the internal outputs are considered as change outputs. 
In this diff, if a received transaction has only one output and it is internal and its value equal to the amount prop of the decoded transaction data, it is assumed as an atomic swap redeem transaction and use its internal output's value as the amount.
The zero inputs (mentioned in #3354) on the transaction details page is a separate bug and it affects other types of transactions too. I handled this issue in this PR too.
Closes #3354.
> Show the correct amount of incoming DEX transactions

- app/actions/GovernanceActions.js
This diff fixes some issues noticed when casting votes. The `castvotes` request returned an unexpected "signature invalid" error due to an invalid param on message encoding.
Due to that, votes were not being cast, but the GUI returned a successful action notification.
Depends on https://github.com/decred/politeia/pull/1399
> [governance] Use correct cast vote params

- app/actions/GovernanceActions.js
This diff closes #3385, which reported an unhandled error on votes cast requests. We needed to parse the response and check for any CastVoteReply error on receipts response.
> [governance] Display cast votes error

- app/components/views/GetStartedPage/CreateWalletPage/CreateWallet.module.css
- app/components/views/GetStartedPage/CreateWalletPage/ExistingSeed/Form.jsx
- app/components/views/HomePage/HomePage.module.css
- app/components/views/TicketsPage/MyTicketsTab/MyTicketsTab.module.css
- app/components/views/TicketsPage/StatisticsTab/Statistics.module.css
- app/components/views/TicketsPage/StatisticsTab/StatisticsTab.jsx
- app/components/views/TicketsPage/VSPTicketsStatusTab/MyTicketsTab.module.css
Found and fixed:
- too tight locked balance summary tooltip on the dashboard:
- on staking statistics page:
- on ticket history page:
- on ticket status page:
- back button tooltip on existing seed
> Improve tooltip sizes and layouts

- .stylelintrc
This prevents false positives when the computer already has an app/dist folder.
> [lint] Ignore app/dist/*.css files

- app/main_dev/externalRequests.js
- app/main_dev/launch.js
This has become necessary due to macOS not properly resolving the path for the packaged version.
Also removes a testnet dex listening address at 127.0.0.2 since macOS doesn't appear to let you bind to those addresses automatically.
Confirmed on linux (yarn dev/start/package)
Confirmed on mac (yarn dev/start/package)
Confirmed on win (yarn start/package)
> [dexc] Fix paths to libdexc.so

- app/reducers/control.js
Closes #3368
I'm not very happy with this solution, but I could not figure out what causes the sync delay. The redux store updates fine, but the selector reads the value of `modalVisible` wrong at first, and after some delay, it is updated with the right value. 
I did not notice this blur lingering issue with other modal though.
> Dismiss blur effect instantly after ticket purchase modal closing

- app/middleware/api.proto
- app/middleware/walletrpc/api_pb.js
Closes #3414
This was causing the incoming req to dcrwallet to be malformed which led to the mixer not firing as expected.
> [mixer] Revert incorrect api.proto changes

- app/components/modals/MixerSettingsModal/MixerSettingsModal.module.css
- app/components/shared/PrivacyForm/PrivacyForm.module.css
**Before:** 
See #3415.
**After:**
Closes #3415.
> Improve `Mixer Settings` modal layout.

- app/actions/VSPActions.js
- app/components/views/GetStartedPage/SetupWallet/hooks.js
- app/reducers/vsp.js
- app/selectors.js
- app/stateMachines/SetupWalletConfigMachine.js
This PR adds a new step into the setup wallet state machine, to find available vsp and its pubkeys.
This is being done to separate it from process managed tickets.
> Move get vsp info to setup machine

- app/actions/DexActions.js
- app/components/views/DexPage/CreateDexAcctPage/CreateDexAcctPage.jsx
- app/components/views/DexPage/CreateDexAcctPage/CreateDexAcctPage.module.css
- app/components/views/DexPage/hooks.js
- app/reducers/dex.js
- app/reducers/walletLoader.js
- app/selectors.js
This diff allows users to select an existing account to become the dex account besides creating a new account.
Closes #3419
> [dex] Allow selection of Dex account

- app/components/views/GetStartedPage/SetupWallet/hooks.js
This fixes the issue for me, but I think this is the second time this has happened. I don't know why there are these two sets of values, but I think I will use another pr to get to the bottom of it and make sure the code base only has to deal with one of these and this doesn't happen again.
closes #3431
> SetupWallet: Check selectedWallet.value for isTrezor.

- app/actions/DaemonActions.js
- app/actions/VSPActions.js
- app/components/shared/TicketAutoBuyerForm/TicketAutoBuyerForm.jsx
- app/components/shared/TicketAutoBuyerForm/TicketAutoBuyerForm.module.css
- app/components/views/TicketsPage/PurchaseTab/hooks.js
- app/constants/config.js
- app/reducers/vsp.js
- app/selectors.js
- test/unit/components/TicketsPage/PurchaseTab/PurchasePage.spec.js
This diff saves the new (not legacy) auto buyer settings to wallet config, so users don't need to refill the form again after close and re-open the application.
Closes #3211
Closes #3410
> [tickets] Remember ticket auto buyer settings

- app/actions/AccountMixerActions.js
- app/actions/ControlActions.js
- app/actions/GovernanceActions.js
- app/actions/VSPActions.js
- app/reducers/snackbar.js
- app/wallet/control.js
Closes a few of the issues notes in #3423
No longer unlocks whole wallet for Revoke Tickets.
Due to voting address needing to be unlocked for tickets to communicate with the VSPs.  Typically the voting account is currently the default account, but there are certain circumstances if using the Auto-buyer that the voting account is the purchase account.
> [locking] Various account locking issues patched

- app/components/inputs/AccountsSelect/AccountsSelect.jsx
- app/components/inputs/AccountsSelect/hooks.js
- app/components/shared/SendTransaction/Form.jsx
- app/components/shared/SendTransaction/SendTransaction.jsx
- app/components/views/TransactionsPage/SendTab/SendOutputRow/SendOutputRow.module.css
Closes #3416 
The details part on the `SendTransaction` form (e.g. `Total amount sending`) sometimes does not follow the actual state of the inputs and shows inconsistent data. This diff fixes this also.
> [transactions] allow account transfers for non-mixed accounts

- app/actions/LNActions.js
- app/actions/StatisticsActions.js
- app/components/buttons/EyeFilterMenu/EyeFilterMenu.jsx
- app/components/charts/VoteTimeChart.jsx
- app/components/inputs/AccountsSelect/hooks.js
- app/components/layout/TabbedPage/TabbedPage.jsx
- app/components/layout/TabbedPage/helpers.js
- app/components/shared/TransitionMotionWrapper.jsx
- app/components/views/GetStartedPage/CreateWalletPage/ExistingSeed/Form/Form.jsx
- app/components/views/GetStartedPage/hooks.js
- app/components/views/ProposalDetailsPage/helpers/VotePreferenceWrapper/hooks.js
- app/components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_PurchaseTickets/index.js
- app/config.js
- app/fp.js
- app/helpers/strings.js
- app/main_dev/externalRequests.js
- app/main_dev/launch.js
- app/selectors.js
- app/stateMachines/GetStartedStateMachine.js
- app/wallet/app.js
- app/wallet/control.js
- app/wallet/daemon.js
Closes https://github.com/decred/decrediton/issues/3131.
> Remove util type checks

- app/components/views/AccountsPage/Accounts/AccountRow/AccountDetails/AccountDetails.jsx
- app/components/views/HomePage/Tabs/BalanceTab/BalanceTab.jsx
- app/i18n/docs/en/InfoModals/BalanceOverview.md
This diff changes "Immature Staking Returns" labels to "Immature Staking Rewards" as @xaur suggested in #3360.
> Change "Immature Staking Returns" labels to "Immature Staking Rewards"

- app/components/indicators/LinearProgress/AnimatedLinearProgressFull.jsx
- app/components/views/GetStartedPage/GetStartedMachinePage/GetStartedMachinePage.jsx
- app/components/views/GetStartedPage/SetupWallet/SetupWallet.jsx
- app/components/views/GetStartedPage/SetupWallet/SetupWallet.module.css
- app/components/views/GetStartedPage/helpers/Header/Header.jsx
- app/components/views/GetStartedPage/helpers/Header/Header.module.css
- app/components/views/GetStartedPage/helpers/Header/index.js
- app/components/views/GetStartedPage/helpers/index.js
- app/components/views/GetStartedPage/hooks.js
On wallet startup during Setup Wallet state, some tasks need time to finish: #3433
This diff doesn't try to optimize the background tasks but shows a loading bar instead of the blank page.
> [startup] Add loader to Setup Wallet state

- app/actions/ControlActions.js
Incorrect passphrase during account security migration allowed users to proceed without completing the migration.
> [locks]  Fix incorrect passphrase allowing to continue

- go.mod
- go.sum
This updates the dcrdex require to the final 0.2 release.  Since rc1
this includes a fix to update the frontend's wallet lock icon when
a wallet is automatically unlocked on order placement or other
action that unlocks as needed.
> require dcrdex v0.2.0 final release

- app/actions/ControlActions.js
Previously, only the selected account was unlocked for the autobuyer.  For privacy autobuyers, we need to unlock the unlocked/change account too.
> [tickets] Unlock unmixed account for autobuyer

- package.json
- scripts/dexsite.js
The `dexsite` script executes this command: `rm -rf bin/site && cp -R ./node_modules/dcrdex-assets/dexc/site bin/` which isn't valid on windows.
This diff introduce `scripts/dexsite.js`. It deletes `bin/site` dir and copy dex site dir with `rd /s /q \"bin/site\" && Xcopy /E /I \"./node_modules/dcrdex-assets/dexc/site\" \"bin/site\"` on windows.
> [dex] Improve `dexsite` script compatibility

- app/main_dev/paths.js
Roaming is the used directory for bitcoin instead of Local.
> [dex] Fix default windows bitoin directory

- README.md
As stated in #3478, yarn install on node version 16.2.0 at least does not work on a clean installation. When inquiring what node version to use, I was recommended 14.16.1. Set that in the readme.
> README: Set recommended node version to 14.16.1.

- app/actions/DaemonActions.js
- app/components/views/GetStartedPage/CreateWalletPage/CreateWalletPage.jsx
- app/components/views/GetStartedPage/CreateWalletPage/hooks.js
- app/components/views/GetStartedPage/PreCreateWallet/CreateWalletForm/CreateWalletForm.jsx
- app/components/views/GetStartedPage/PreCreateWallet/CreateWalletForm/CreateWalletForm.module.css
- app/components/views/GetStartedPage/PreCreateWallet/PreCreateWallet.jsx
- app/main.development.js
- app/main_dev/ipc.js
- app/main_dev/launch.js
- app/wallet/daemon.js
- test/unit/components/views/GetStaredPage/CreateWallet.spec.js
- test/unit/components/views/GetStaredPage/PreCreateWallet.spec.js
This diff adds two new (`disablecointtypeupgrades` and `gaplimit`) advanced options to the restoring wallet view then use these options for next dcrwallet spawn.
Closes #3482
> [launcher] Add advanced options to Restore wallet

- app/components/shared/SendTransaction/Form.jsx
- app/components/shared/SendTransaction/SendTransaction.jsx
- app/components/views/TransactionsPage/SendTab/SendOutputRow/SendOutputRow.jsx
- app/components/views/TransactionsPage/SendTab/SendOutputRow/SendOutputRow.module.css
- app/components/views/TransactionsPage/SendTab/index.js
- app/components/views/TransactionsPage/TransactionsPage.jsx
- app/components/views/TransactionsPage/index.js
- test/unit/components/views/TransactionsPage/SendTab/SendTab.spec.js
This is the continuation of #2957. I've covered the SendTab view:
- app/components/shared/SendTransaction/*
- app/components/views/TransactionsPage/TransactionsPage.jsx
- app/components/views/TransactionsPage/SendTab/*
> Send tab: automated tests

- app/components/views/TransactionsPage/ReceiveTab/ReceivePage/QRCodeModal/index.js
- app/components/views/TransactionsPage/ReceiveTab/ReceivePage/ReceivePage.jsx
- app/components/views/TransactionsPage/ReceiveTab/ReceivePage/index.js
- app/components/views/TransactionsPage/ReceiveTab/ReceiveTab.jsx
- app/components/views/TransactionsPage/ReceiveTab/index.js
- app/components/views/TransactionsPage/TransactionsPage.jsx
- app/containers/Wallet/Wallet.jsx
- test/unit/components/views/TransactionsPage/ReceiveTab/ReceiveTab.spec.js
This is the continuation of #3489. I've covered the ReceiveTab view:
- app/components/views/TransactionsPage/ReceiveTab/*
- app/components/views/TransactionsPage/ReceiveTab/ReceivePage/*
- app/components/views/TransactionsPage/ReceiveTab/ReceivePage/QRCodeModal/*
> Receive tab: automated tests

- app/main_dev/paths.js
On the mainnet, the dcrwallet could not start because of the invalid cert path. This diff fixes it. 
~~Also fixes the wallet import in `ExternalButton` component. See: https://github.com/decred/decrediton/pull/3398#issuecomment-856603163~~
> Fix getCertsPath 

- app/main.development.js
- app/main_dev/externalRequests.js
~**Rebased on top of #3492**~
This re-disables the remote module on windows and enables the `webSecurity` feature.
`webSecurity` is used to tighten up external requests by enabling same-origin policy and disallowing mixed content. 
In order to enable this in development mode, external requests are modified in to return a `Allow-Origin: http://localhost:3000` header so that the main wallet page loaded via the HMR server is allowed to perform them. Additionally, we fix the `OPTIONS` request performed as a prefetch step to politeia servers when performing a `POST` request to always return a 200 response.
> [electron] Enable WebSecurity

- app/components/SideBar/MenuLinks/MenuLinks.jsx
- app/components/SideBar/MenuLinks/MenuLinks.module.css
- app/components/SideBar/MenuLinks/hooks.js
- app/components/SideBar/SideBar.module.css
- test/unit/components/SideBar/Sidebar.spec.js
This diff implements @jholdstock's idea on the matrix: "Maybe decrediton in SPV mode should just gray out the Dex tab, with a tooltip to explain that SPV needs to be switched off. Hiding it completely has caught a lot of people out)"
> Disabled Dex menu with tooltip in SPV mode

- app/selectors.js
- app/wallet/service.js
Closes #3507
In this diff:
- tx's `isPending` property is determined from the block height instead of timestamp. 
- from `getTransaction` (service.js) the `formatTransaction` function is called with `null` block timestamp instead of -1 making sure that timestamp will be set using transaction's timestamp here: https://github.com/decred/decrediton/blob/7a152c1bae5bd914ee7f0e482bfaef13efdccb06/app/wallet/service.js#L156-L158
> Fix details of transactions

- .gitignore
- app/actions/DaemonActions.js
- app/config.js
- app/helpers/files.js
- app/helpers/strings.js
- app/i18n/locales/index.js
- app/main.development.js
- app/main_dev/constants.js
- app/main_dev/externalRequests.js
- app/main_dev/ipc.js
- app/main_dev/launch.js
- app/main_dev/paths.js
- app/main_dev/proxy.js
- app/middleware/grpc/client.js
- app/wallet/app.js
- app/wallet/config.js
- app/wallet/control.js
- app/wallet/daemon.js
- app/wallet/service.js
- babel.config.js
- package.json
- scripts/generateDepGraphs.js
- yarn.lock
This reduces the dependencies to third party packages in the main electron and preload script layers of the application. 
This improves the codebase by relying less on third party code, slightly reduces compilation time and improves security by reducing the attack surface of a possible supply chain attack.
The main changes introduced by this PR are:
- Add a script that can generate graphs for the dependency tree of each layer of the application
- This was added as the first commit so that dependencies before and after the refactor can be checked by doing a `node ./scripts/generateDepGraphs.js`
- Remove the now unneeded (due to updated electron version) intl-relativetimeformat polyfill
- Reduce (but not yet eliminate) dependency on lodash by performing specific imports and functions
- …
> [multi] Reduce dependencies in main and preload layers

- app/actions/ControlActions.js
- app/actions/VSPActions.js
- app/components/modals/ConfirmationDialogModal/ConfirmationDialogModal.jsx
- app/components/modals/ConfirmationDialogModal/index.js
- app/components/modals/Modal/Modal.jsx
- app/components/modals/index.js
- app/constants/config.js
- app/containers/App/App.jsx
- app/index.js
- app/main.development.js
- app/main_dev/externalRequests.js
- app/reducers/control.js
- app/selectors.js
- app/staticPages/confirmation-dialog.html
- app/wallet/config.js
- app/wallet/confirmationDialog/allowVspHost.js
- app/wallet/confirmationDialog/dialog.js
- app/wallet/confirmationDialog/index.js
- app/wallet/index.js
- app/wallet/vsp.js
- package.json
- webpack/ui.dev.js
- webpack/ui.prod.js
~**Requires #3509**~
This adds a confirmation dialog entirely controlled by the preload script and the main electron process through the use of a `BrowserView` instance.
The main benefit for this approach is having a confirmation screen that lives outside the main UI and cannot be modified by code running in the UI layer.
The `BrowserView` class is an electron feature that allows overlapping a new rendering frame on top of the existing window, but without adding it to the corresponding document's DOM. All the code loaded in a BrowserView is effectively in a separate window and thus inaccessible to anything except the main electron process.
After splitting the code across the various layers of the app, turning on electron's security features (`nodeIntegration` and `contextIsolation`) and …
> [Multi] Confirm access to VSPs via BrowserView dialog

- app/wallet/vsp.js
This adds a missing check from the previous PR to ensure a VSP is already
allowed before asking for confirmation for external accesses.
This prevents having to always allow all VSPs during startup.
> [wallet] Check if VSP is allowed instead of re-confirming

- app/actions/ClientActions.js
- app/actions/ControlActions.js
- app/middleware/grpc/client.js
- app/reducers/grpc.js
- app/selectors.js
- app/wallet/confirmationDialog/dialog.js
- app/wallet/confirmationDialog/index.js
- app/wallet/confirmationDialog/signTx.js
- app/wallet/control.js
- app/wallet/service.js
~**Requires #3515**~
This switches the wallet's `SignTx` function to confirm with the user the transaction to be signed via the recently introduced confirmation dialog that runs in a BrowserView.
This ensures that any attempts by UI code to modify the transaction are visible to the user before the tx is sent to the underlying wallet to be signed.
The dialog is formatted such that only outputs and amounts that are not returning to the wallet (i.e. addresses in outputs that do _not_ correspond to one of the wallet's BIP0044 account) are shown.
> [wallet] Use BrowserView ConfirmDialog on SignTx

- app/i18n/extracted/static/menus.json
- app/main.development.js
- app/main_dev/templates.js
This makes it so that the devtools for the confirmation window doesn't show up automatically, but still allows opening it from the main menu for debugging.
> [main] Add menu toggle devtools in conf window

- app/components/views/GetStartedPage/CreateWalletPage/CreateWalletPage.jsx
- app/helpers/seed.js
- app/stateMachines/CreateWalletStateMachine.js
- app/staticPages/confirmation-dialog.html
- app/wallet/confirmationDialog/index.js
- app/wallet/confirmationDialog/seed.js
- app/wallet/loader.js
- package.json
- test/mocks/walletMock.js
- test/setup.js
- test/unit/components/views/GetStaredPage/CreateWallet.spec.js
- test/unit/components/views/GetStaredPage/PreCreateWallet.spec.js
- test/unit/helpers/seed.spec.js
- yarn.lock
**Requires #3519**
This adds a final confirmation window to the wallet creation flow which displays the seed that is about to be used to create the wallet via the recently introduced, BrowserView based confirmation dialog.
This prevents UI code from tampering with the seed without user acknowledgement. 
Seeds that are exactly 256 bits long (standard decred seeds) are displayed with the usual 33 word mnemonic sequence. Seeds of different length are displayed as raw hexadecimal.
Please note that rejecting the seed currently breaks wallet setup. This is not specifically related to this PR, but rather the fact that any errors during the final wallet setup aren't being correctly handled right now. This will need to be fixed in a separate PR.
Thanks to @vctt94 for some help in fixing the reject …
> [Wallet] Confirm seed via BrowserView dialog

- app/components/views/GetStartedPage/PreCreateWallet/PreCreateWallet.jsx
- test/unit/components/views/GetStaredPage/PreCreateWallet.spec.js
Disallow some problematic characters in wallet names.
closes #3359
This works in the same way it did before, just adds a few more characters to the replace and doesn't allow for leading spaces. space, +, -, _, and : look to be fine on linux, but Windows may be more restrictive. Will test there if noone else can. Parenthesis and brackets may also be fine and used by some people. Allow?
> PreCreateWallet: Replace more name chars.

- app/actions/GovernanceActions.js
- app/components/views/AgendaDetailsPage/helpers/AgendaCard/AgendaCard.module.css
- app/components/views/GovernancePage/Proposals/ProposalsListItem/ProposalsListItem.jsx
- app/components/views/GovernancePage/Proposals/hooks.js
- app/components/views/ProposalDetailsPage/ProposalDetails.jsx
- app/components/views/ProposalDetailsPage/helpers/ProposalCard/ProposalCard.jsx
- app/components/views/ProposalDetailsPage/helpers/ProposalCard/ProposalCard.module.css
- app/components/views/ProposalDetailsPage/helpers/VoteInfo.jsx
- app/components/views/ProposalDetailsPage/helpers/VotePreferenceWrapper/VotePreference/VotePreference.jsx
- app/components/views/ProposalDetailsPage/helpers/VotePreferenceWrapper/hooks.js
- app/components/views/ProposalDetailsPage/helpers/VoteSection/VoteSection.jsx
- app/components/views/ProposalDetailsPage/utils.js
- app/constants/governance.js
- app/helpers/politeia.js
- app/index.js
- app/main_dev/externalRequests.js
- app/main_dev/paths.js
- app/middleware/politeiaapi.js
- app/reducers/governance.js
- app/selectors.js
- app/wallet/politeia.js
Closes #3391.
**Note:** The new API supports paginated vote inventory calls, I decided to keep the pagination work to a separate 
future PR to try maintain incermental easily reviewable PRs.
**Testing against local PI**
To run against local PI instance add the following commented out code:
- https://github.com/decred/decrediton/blob/master/app/main_dev/externalRequests.js#L52-L62
- https://github.com/decred/decrediton/blob/master/app/middleware/politeiaapi.js#L6
> Politeia: Migrate to new API.

- app/main.development.js
- app/main_dev/launch.js
- app/main_dev/logging.js
- app/wallet/app.js
- package.json
- yarn.lock
This removes the winston log library as a dependency from the project. This helps reduce the number of dependencies on the main electron layer.
This is done by implementing a very basic logger that replicates the features we were using from winston: writing both to a log file and to the terminal when `debug` is set.
Dependencies of the main electron layer before winston is removed:
After removing winston:
> [electron] Remove winston as a dependency

- app/actions/ControlActions.js
Previously we were just updating the private passphrase, but after the forced upgrade for account locking we need to update all accounts to the new private passphrase as well.
> settings: Update account passphrases on private passphrase change

- app/actions/DaemonActions.js
- app/actions/WalletLoaderActions.js
- app/components/views/GetStartedPage/CreateWalletPage/CreateWalletPage.jsx
- app/components/views/GetStartedPage/GetStartedMachinePage/GetStartedMachinePage.jsx
- app/components/views/GetStartedPage/hooks.js
- app/hooks/useDaemonStartup.js
- app/stateMachines/CreateWalletStateMachine.js
- app/stateMachines/GetStartedStateMachine.js
- test/unit/components/views/GetStaredPage/CreateWallet.spec.js
- test/unit/components/views/GetStaredPage/PreCreateWallet.spec.js
Closes #3524
Found and fixed these errors in create wallet flow:
1. rejecting the final confirmation dialog (or receiving an error from the wallet create request) at the final stage of creation/restore wallet jumps back to the create/restore view (`PreCreateWallet`) and displays an error: `loader.OpenExistingWallet: item does not exist:: wallet.OpenDB: missing database file`. The wallet is partially created and started but until the restart of the app, it can not be stopped or start any other wallet. 
2. when an app refresh breaks the creation/restore process, a similar thing happens. The partially created/restored wallet is running in the background and it can not be stopped or start any other wallet. 
3. the flashing wallet selection screen after creating a wallet is also fixed. It is …
> Fix error flows in create wallet

- app/actions/ControlActions.js
- app/reducers/control.js
- app/selectors.js
- scripts/dexsite.js
Fixes #3541 
Previously change addresses were the same as the sent addresses for mixed sends. 
This adds a new action for getting new change addresses.  This allows us to get new change addresses without messing with the new address requests which also change various GUI elements (receive account select).
> [transactions] Fix change address for mixed sends

- app/actions/TrezorActions.js
- app/components/modals/TrezorModals/TrezorModals.jsx
- app/components/modals/TrezorModals/TrezorWordModal.jsx
- app/components/shared/ButtonsToolbar.jsx
- app/components/views/TrezorPage/TrezorPageContent.jsx
- app/components/views/TrezorPage/hooks.js
- app/hooks/useTrezor.js
- app/index.js
- app/reducers/trezor.js
- app/selectors.js
This keeps the trezor word modal alive during the restore device process and display loading state between the individual word request.
closes #3427
> [trezor] keep the trezor word modal alive during the restore device process

- app/actions/TransactionActions.js
- app/components/views/TransactionPage/TransactionContent/TransactionContent.jsx
- app/constants/decred.js
We were able to determine various crashes in 1.6.3 were caused by the processing of transactions that contained very large amounts of outputs.  So avoid this we will limit the number of outputs to check to 10.  Also this is just for display purposes in transaction details so it shouldn't effect any functionality.
> [transactions] Limit number of non wallet outputs

- app/components/views/GetStartedPage/hooks.js
@JoeGruffins reported an issue on the matrix: "If I go to restore from seed, and reject there, Settings are missing from the top right until I go to create/restore and go back"
This diff fixes it.
> Fix missing navigation links

- app/actions/VSPActions.js
> Show "error refreshing stakepool data" error msg only in legacy mode

- app/components/inputs/VSPSelect/VSPSelect.jsx
- app/components/inputs/VSPSelect/VSPSelect.modules.css
- app/components/modals/AutoBuyerSettingsModal/AutoBuyerSettingsModal.module.css
This PR improves the responsivity of the ``VSPSelect`` and ``AutoBuyerSettingsModal`` components by:
- Stretching the account select to adjust the modal width.
- Enabling clicks on the right corner of a VSP option (currently, there's a padding inserted by ``react-select``).
- Inserting ellipsis on long VSP host names.
Also, the small "close" icon should clear the current input only when typing, since it's useless for clearing the selected VSP.
> Improve VSPSelect usability and responsivity 

- package.json
- yarn.lock
This diff fixes the following alert by bumping `recharts` from 1.8.5 to 2.1.4.
```
react_devtools_backend.js:2560 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod …
```
> Bump recharts from 1.8.5 to 2.1.4

- app/components/views/AgendaDetailsPage/hooks.js
Previously, when the treasury agenda is clicked it would throw a choice.getId() is not a function.
> [governance] Choice getId error fix 

- app/actions/DexActions.js
- app/components/views/DexPage/InitPage/InitPage.jsx
- app/components/views/DexPage/InitPage/InitPage.module.css
- app/components/views/DexPage/InitPage/hooks.js
- app/components/views/DexPage/RegisterPage/RegisterPage.jsx
- app/components/views/DexPage/RegisterPage/hooks.js
- app/components/views/DexPage/hooks.js
- app/index.js
- app/main.development.js
- app/main_dev/ipc.js
- app/main_dev/launch.js
- app/reducers/dex.js
- app/selectors.js
- app/wallet/dex/index.js
- modules/dex/libdexc/adapter.go
Require #3549 
This adds the ability to restore a DEX account from seed.  Along with that functionality, when a user restores from seed we check to see if they have already paid the server's registration fee.  If they have they can skip the step that asks for payment.
> dex: Add dex seed and pre-registration check

- app/components/shared/PurchaseTicketsForm/PurchaseTicketsForm.jsx
- app/selectors.js
- test/unit/components/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_PurchasePage.spec.js
- test/unit/components/TicketsPage/PurchaseTab/PurchasePage.spec.js
This diff is a preliminary step toward #3586 and hides the legacy purchase option for now without nuking the code.
> Hide the legacy purchase option

- app/actions/ControlActions.js
Probably there is a race around signing the transaction. 
As @davecgh suggested on matrix, this adds some logging for debugging purposes when the wallet is on the testnet.
> Log signing parameters on testnet if the produced tx rejected

- app/i18n/translator.html
This fixes several bugs in the new `translator.html` tool:
- Indent generated JSON with 2 spaces to reduce diffs with all existing
translation `.json` files.
- Limit the height of the left-hand panel to fix excessive scrolling
between an item selected down the list and input fields at the top of
the view.
- Fix going to next item on Untranslated list.
- Fix going to next item on Changed list.
Closes #3575.
> i18n: translator fixes

- app/components/views/GetStartedPage/PreCreateWallet/PreCreateWallet.jsx
- app/components/views/GetStartedPage/SetupWallet/SetAccountsPassphrase/SetAccountsPassphrase.js
- app/hooks/useDaemonStartup.js
- app/index.js
- app/main_dev/ipc.js
- app/reducers/control.js
- app/selectors.js
- test/unit/components/views/GetStaredPage/PreCreateWallet.spec.js
This fixes the migrate to per account passphrase stage of wallet startup to
ignore watching only wallets.
It also adds an indicator to the same stage, to prevent double execution of
the process.
> [Startup] Fix account pwd for watching only

- .github/workflows/nodejs.yml
Node version v15 is not supported anymore: (https://nodejs.org/en/about/releases/) and there is no point in building on it. 
Later, we can add 16.x, when we update electron to v16.
> Remove 15.x node version from CI build matrix

- app/components/Snackbar/Snackbar.module.css
- app/components/Snackbar/index.js
- app/components/views/GetStartedPage/PreCreateWallet/CreateWalletForm/CreateWalletForm.jsx
- app/components/views/GetStartedPage/PreCreateWallet/CreateWalletForm/CreateWalletForm.module.css
- app/components/views/PrivacyPage/PrivacyTab/ConfigMixer/CreateDefaultAccounts/CreateDefaultAccounts.jsx
- app/components/views/PrivacyPage/PrivacyTab/ConfigMixer/CreateNeededAccounts/CreateNeededAccounts.jsx
- test/unit/components/views/PrivacyPage/PrivacyTab.spec.js
Found and fixed:
- style of watch-only warning snack bar was broken. Before/after: 
- label of `Master Pub Key` was misaligned. Before/after: <img width="469" alt="image" src="https://user-images.githubusercontent.com/52497040/143918068-13c9c782-fefa-4ec8-83d9-e54b789083f5.png">
- on `Privacy Configuration` view the `Create Default Accounts` button was simply disabled for watch-only wallets and the watch-only warning snack bar never showed.
> [Multi] Watch-only wallet fixes

- app/components/views/TicketsPage/MyTicketsTab/MyTicketsTab.jsx
- app/components/views/TicketsPage/MyTicketsTab/MyTicketsTab.module.css
- app/components/views/TicketsPage/MyTicketsTab/Page.jsx
- app/components/views/TicketsPage/MyTicketsTab/hooks.js
- app/components/views/TransactionsPage/HistoryTab/HistoryPage/HistoryPage.jsx
- app/selectors.js
Closes #2492
This diff adds filter by tx hash to `Transaction History` and filter by ticket hash to `Ticket History` views.
> [transactions filter] Add filter by tx id 

- app/helpers/files.js
This fixes a bug that was relatively common among users in support.
Some older wallets would require upgrades for dcrd cert/keys.  "is_electron8": false would hit these.
> [launcher] Fix bug for old rpc backup

- app/style/icons/dex.svg
- app/style/icons/dexDark.svg
This ensures the Dex icon appears more similar in size to other icons in the navigation menu. Previously it was undersized.
> Reduce borders on Dex icon.

- go.mod
- go.sum
Since the last revision referenced in the go.mod, this includes a check for the Bitcoin Core wallet type to ensure it is not a "descriptor" wallet, which does not support a number of standard RPCs (!).
> use the tagged dcrdex v0.4.0-rc1

- app/components/indicators/LoadingMoreTickets/LoadingMoreTickets.module.css
- app/components/modals/ListUTXOsModal/ListUTXOsModal.module.css
- app/components/views/GetStartedPage/CreateWalletPage/ExistingSeed/Form/Form.module.css
- app/components/views/TransactionPage/TransactionContent/TransactionContent.jsx
This diff fixes:
- a misalignment on the restore view
- the copy icon on the UTXO modal 
- and fixes the missing ticket fee on the transaction details view
- fix cancel button in loading more tickets component. (found by @matheusd)
> Minor fixes

- app/actions/DaemonActions.js
- app/actions/DexActions.js
- app/components/views/DexPage/CreateWalletsPage/CreateWalletsPage.jsx
- app/components/views/DexPage/hooks.js
- app/constants/config.js
- app/reducers/walletLoader.js
- app/selectors.js
This adds the ability to chose whether or not you'd like to use the new native (spv/neutrino) btc wallet that is included within dexc.
We have also decided to bypass the Register page and actions since the funnel within dexc is much more flushed out and allows for payment from a variety of assets instead of just DCR.  I have left the RegisterPage and Actions in for now and when we have finalized the functionality we can remove all that is unused.
> [dex] Add BTC SPV question and remove Register

- app/actions/LNActions.js
- app/components/views/LNPage/ConnectPage/ConnectPage.jsx
- app/components/views/LNPage/ConnectPage/ConnectPage.module.css
- app/components/views/LNPage/ConnectPage/hooks.js
- app/components/views/LNPage/hooks.js
- app/index.js
- app/main.development.js
- app/middleware/ln/rpc.proto
- app/middleware/ln/rpc_pb.js
- app/reducers/ln.js
- app/selectors.js
- app/wallet/daemon.js
This adds a linear progress component during the router pruning stage of the
LN wallet startup. It also adds the last log line of the dcrlnd process to the
startup UI and removes the 60 second limit of the startup sync time.
These help mitigate issues when opening an LN wallet that has been offline for
a long time.
~Depends on https://github.com/decred/dcrlnd/pull/153~ (merged)
Closes #3636
> [LN] Show startup progress and log line

- app/actions/DaemonActions.js
- app/actions/DexActions.js
- app/components/views/DexPage/ConfirmDexSeed/ConfirmDexSeed.jsx
- app/components/views/DexPage/ConfirmDexSeed/ConfirmDexSeed.module.css
- app/components/views/DexPage/ConfirmDexSeed/ConfirmDexSeedHeader.jsx
- app/components/views/DexPage/ConfirmDexSeed/index.js
- app/components/views/DexPage/hooks.js
- app/constants/config.js
- app/main.development.js
- app/main_dev/ipc.js
- app/main_dev/launch.js
- app/reducers/dex.js
- app/reducers/snackbar.js
- app/reducers/walletLoader.js
- app/selectors.js
- app/wallet/dex/index.js
- modules/dex/libdexc/adapter.go
Close #3646 
This now allows all users to copy down their DEX account seed.  
When a user completes their initial passphrase setting or logs in they will be shown this information until they have clicked the button on the confirm seed page.
> [dex] Add ExportSeed and ConfirmSeed page

- go.mod
- go.sum
- package.json
- yarn.lock
This updates to dcrdex v0.4.0-rc2.
For libdexc this brings:
- A bug fix with BTC funding UTXO selection when there are p2sh outputs ([dda8654](https://github.com/decred/dcrdex/commit/dda86540ad9b585b3165bf0eb06c733576596a9d))
- slightly quieter logging with "spot price" notifications silent ([61e9138](https://github.com/decred/dcrdex/commit/61e913882708a2cfc059c1c47b4c48e48462d99c))
- Removes a hard coded 100 sat/vB fee rate used with BTC `Withdraw` in SPV mode, instead using a server's fee suggestion ([deab1c9](https://github.com/decred/dcrdex/commit/deab1c9deeab70876059d5246c60f023fa6a3e28))
For dcrdex-assets (frontend), just fix a zero price in the depth chart legend ([94eedbd](https://github.com/decred/dcrdex/commit/94eedbd56241e10c40859ed2206f354688ce8c5e)).
> dcrdex v0.4.0-rc2

- app/components/views/DexPage/ConfirmDexSeed/ConfirmDexSeed.jsx
- app/components/views/DexPage/ConfirmDexSeed/ConfirmDexSeed.module.css
- app/components/views/DexPage/CreateDexAcctPage/CreateDexAcctPage.module.css
- app/components/views/DexPage/CreateWalletsPage/CreateWalletsPage.jsx
- app/components/views/DexPage/CreateWalletsPage/CreateWalletsPage.module.css
- app/components/views/DexPage/EnablePage/EnablePage.jsx
- app/components/views/DexPage/EnablePage/EnablePage.module.css
- app/components/views/DexPage/InitPage/InitPage.jsx
- app/components/views/DexPage/InitPage/InitPage.module.css
Closes #3662
This diff improves the style of the `Connect Wallets to Dex` view. 
Also, enhanced the style of pages shown before this view a little bit. 
Screenshots:
> [dex] Improve the style of the Connect Wallets to Dex view

- app/actions/ControlActions.js
Currently peer count is broken and always shows 0.  I'm not sure the reason for checking resp.wrappers_ in the past, but doesn't seem necessary anymore.
> Fix Peer Count display

- app/selectors.js
- app/wallet/service.js
- test/unit/components/views/TransactionPage/mocks.js
This moves the determination of whether a transaction is a mix transaction
from the selectors to the formatTransaction function that runs after fetching
transactions from the wallets.
This avoids having to decode and recalculate whether a tx is a mix transaction
every time the selectors are updated, which was causing slowdown on wallets
that participated in mixed transactions.
> [selectors] Move isMix determination to higher level

- go.mod
- go.sum
- package.json
- yarn.lock
One minor change to frontend in case server supports an asset the client doesn't recognize.  No visible changes with unmodified v0.4 servers and clients.
> [dex] Bump to dcrdex v0.4.0 final

- app/actions/LNActions.js
- app/staticPages/confirmation-dialog.html
- app/wallet/confirmationDialog/index.js
- app/wallet/confirmationDialog/sendLNPayment.js
- app/wallet/ln/index.js
**Requires #3521**
This adds user confirmation of outgoing LN payments via the recently introduced BrowserView dialog.
This prevents UI code from attempting to send unacknowledged LN payments.
> [Multi] Confirm LN Payments via BrowserView dialog

- app/components/shared/TxHistory/TxHistory.jsx
- test/unit/components/views/HomePage/HomePage.spec.js
This was causing Live tickets to not show their fee status or their time on the overview or Ticket Status page.
> [tickets] Live tickets not showing information

- app/actions/ControlActions.js
- app/components/inputs/AccountsSelect/hooks.js
Closes #3697
Also, I noticed if some error happened during the account creation, the error only dispatched into redux, and the dex registration progress silently moved on. It maybe causes an error like reported in #3694. Now the error is thrown toward, and it can be handled in `DexActions/CreateDexAccount`
> [dex] Fix error occurring when creating an account for dex

- app/actions/ClientActions.js
- app/actions/GovernanceActions.js
- app/components/SideBar/MenuLinks/Links.jsx
- app/components/SideBar/MenuLinks/hooks.js
- app/components/views/GovernancePage/GovernancePage.jsx
- app/components/views/GovernancePage/GovernancePage.module.css
- app/components/views/GovernancePage/hooks.js
- app/components/views/HomePage/GovernanceNotification/GovernanceNotification.jsx
- app/components/views/HomePage/GovernanceNotification/GovernanceNotification.module.css
- app/components/views/HomePage/GovernanceNotification/hooks.js
- app/components/views/HomePage/GovernanceNotification/index.js
- app/components/views/HomePage/HomePage.module.css
- app/components/views/HomePage/Tabs/BalanceTab/BalanceTab.jsx
- app/components/views/HomePage/Tabs/TicketsTab/TicketsTab.jsx
- app/components/views/HomePage/Tabs/TransactionsTab/TransactionsTab.jsx
- app/components/views/HomePage/hooks.js
- app/selectors.js
- test/unit/components/SideBar/Sidebar.spec.js
Closes #3721
This diff notifies show notifications if there is any consensus agenda or pi vote which is abstain:
- on the sidebar: 
- on the overview screen as a clickable link 
- on the governance page
> [ux] Notify user of votes

- app/components/Snackbar/Snackbar.module.css
> [css] Fix snackbar layout

- app/actions/VSPActions.js
- app/components/views/GovernancePage/Blockchain/Blockchain.jsx
- app/components/views/GovernancePage/Blockchain/Blockchain.module.css
- app/components/views/GovernancePage/Blockchain/hooks.js
- app/reducers/vsp.js
- app/selectors.js
- test/unit/actions/VSPActions.spec.js
- test/unit/actions/vspMocks.js
- test/unit/components/views/GovernancePage/Blockchain/Blockchain.spec.js
This diff alerts the user for any un-upgraded used vsp that has > 0 unspent tickets on the governance page.
Requires https://github.com/decred/dcrwallet/pull/2146
Requires #3732
Part of #3723
Screenshots:
> [vsp] Alert user for any un-upgraded used vsp that has > 0 unspent tickets

- app/components/Snackbar/Notification/Transaction.jsx
- app/components/layout/TabbedPage/TabbedPage.jsx
- app/components/layout/TabbedPage/TabbedPage.module.css
- app/components/shared/TxHistory/TxHistory.jsx
- app/components/shared/TxHistory/index.js
- app/components/shared/index.js
- app/components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfoDisplay.jsx
- app/components/views/TransactionsPage/HistoryTab/HistoryPage/HistoryPage.module.css
- app/containers/Wallet/Wallet.jsx
This diff improves the transaction history view in multiple ways:
- Fix infinite scroll. Before this, when the user arrived at the history page, the app loaded immediately all data chunks independently from the scroll state. In a wallet with long tx history, this could have caused a slow, unresponsive state.
- Now history tab remembers its scroll position after coming back from the tx details page.
- Fix search tx input width
> [ui] Improve transaction history view

- app/actions/ClientActions.js
- app/components/SideBar/MenuLinks/hooks.js
- app/constants/config.js
- app/index.js
- app/selectors.js
This will go with a v0.4.3 shortly.  We should try to release a 1.7 patch with said dex patch.
Working for me, not blocking DEX in SPV mode, but this is a fairly naive purge of the option based on the commit that added it, so I may have missed something.
> [dex]: dcr spv no longer experimental

- app/components/shared/TxHistory/RegularTxRow.jsx
- app/components/shared/TxHistory/Row.jsx
- app/components/shared/TxHistory/TxHistory.jsx
- app/components/shared/TxHistory/TxHistory.module.css
- app/components/shared/TxHistory/TxRow.jsx
- app/components/views/TransactionsPage/HistoryTab/HistoryTab.jsx
- app/components/views/TransactionsPage/HistoryTab/hooks.js
- app/selectors.js
- test/unit/components/views/TransactionsPage/HistoryTab/HistoryTab.spec.js
Requires #3743
The tx history tab tends to become a bit sluggish if the tx history is large. After I investigated the bottlenecks, added these performance improvements:
-  Loads the rows gradually using the infinite scroll's functionality, even if the data is already fetched from the dcrwallet. Before this PR, if the user scrolls down deep to the older transactions first and leaves the tab, then comes back, the application renders all the previously loaded items at once, which could be quite time-consuming.
- Moved the `filteredRegularTxs` from the selectors to the `HistoryTab` custom hooks to be able to memoize it.
- Memoize each row item and render it only if there was a data change
- tests are updated
Also, I noticed that after clicking on one of the transaction items to reach the …
> [ui] Improve performance of the tx history tab 

- go.mod
- go.sum
- modules/dex/libdexc/adapter.go
- package.json
- yarn.lock
This updates to dcrdex v0.4.3 with some important bug fixes and new features.
https://github.com/decred/dcrdex/milestone/19?closed=1
```sh
$  nvm use v14
Now using node v14.17.6 (npm v6.14.15)
$  yarn
yarn install v1.22.18
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
...
Done in 8.46s.
$  yarn upgrade dcrdex-assets@https://github.com/decred/dcrdex-assets#v0.4.3
yarn upgrade v1.22.18
...
[5/5] Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ dcrdex-assets@0.0.0
info All dependencies
└─ dcrdex-assets@0.0.0
Done in 8.64s.
$  go get -d decred.org/dcrdex@v0.4.3
go: downloading decred.org/dcrdex v0.4.3
go: upgraded decred.org/dcrdex v0.4.2 => v0.4.3
$  go mod tidy
```
yarn.lock …
> [dex] Bump to dcrdex v0.4.3

- app/actions/ControlActions.js
- app/actions/VSPActions.js
- app/components/views/TicketsPage/PurchaseTab/hooks.js
- app/components/views/TransactionPage/TransactionContent/TransactionContent.jsx
- app/components/views/TransactionPage/TransactionPage.jsx
- app/components/views/TransactionPage/hooks.js
- app/main_dev/externalRequests.js
- app/middleware/vspapi.js
- app/reducers/snackbar.js
- app/reducers/vsp.js
- app/selectors.js
- app/wallet/vsp.js
- test/unit/actions/VSPActions.spec.js
- test/unit/components/views/TransactionPage/TransactionPage.spec.js
Closes #2859
Closes #3083
One step further to #3010
Requires https://github.com/decred/dcrwallet/pull/2146 (has been merged)
This diff displays a button on the tx details page if the vsp host info is present. Clicking on it, it asks for the private passphrase and signs the message for the vsp communication. After fetching the vsp info, displays the clickable tx hash and the fee status. 
Also, if the received fee tx is in confirmed status for an unspent ticket but the dcrwallet thinks it's not yet confirmed, the app processes and updates the status in the background.
> [vsp] Show fee tx hash and fee status on tx details view

- app/components/views/SettingsPage/SettingsPage.jsx
- app/i18n/docs/en/Tutorials/TicketsPage01.md
- app/i18n/docs/en/Tutorials/TicketsPage02.md
- app/i18n/docs/en/Tutorials/TicketsPage03.md
- test/unit/actions/VSPActions.spec.js
- test/unit/components/views/TransactionPage/TransactionPage.spec.js
With a release coming out soon, and a large number of tutorial's text still in flux, we're going to hide the majority of them.
This also includes the completed text for the Tickets tutorial (that is shown as the staking page warning).
> [settings] Update Tickets tutorial, hide the rest

- package.json
- yarn.lock
Close #3707 
This fixes an issue that caused dcrwallet/dcrd to not be able to be launch on macOS 10.15 (Catalina).  Users with this issue have confirmed it to be working as expected with the bump.
> Bump electron to v17.4.2

- app/components/views/TransactionPage/TransactionContent/TransactionContent.jsx
- app/components/views/TransactionPage/TransactionHeader/TransactionHeader.jsx
- test/unit/components/views/TicketsPage/MyVSPTickets/MyVSPTicketsTab.spec.js
- test/unit/components/views/TransactionPage/TransactionPage.spec.js
- test/unit/components/views/TransactionPage/mocks.js
This diff adds the Ticket spent entry to the revocation tx details page and renamed "Voted On" to "Missed On", as @davecgh suggested on the matrix.
Also, I noticed that the titles of the details page are often not correct (e.g. revocation was `revoke`, the revoked tickets were `ticket, voted`).  I tried to find and fix all such cases. Tests were updated and extended.
> [staking] Add Ticket spent entry to the revocation tx details page

- app/components/views/HomePage/GovernanceNotification/GovernanceNotification.module.css
The governance notification icon stays visible when the user clicks one of the transactions on the home view. This diff fixes it by removing the unnecessary z-index property.
> [css] Fix governance notification icon

- app/components/views/PrivacyPage/PrivacyTab/PrivacyContent.jsx
- app/i18n/docs/en/Warnings/MixerIntroduction.md
This renames `Stakeshuffle++` to `StakeShuffle` as @xaur suggested: https://github.com/decred/decrediton/pull/3767#issuecomment-1156804362
> [privacy] renaming StakeShuffle

- app/components/buttons/ToggleSwitch/ToggleSwitch.jsx
This fixes js warning:
```
react_devtools_backend.js:6 Warning: Failed prop type: The prop `toggled` is marked as required in `Toggle`, but its value is undefined`.
```
reported in https://github.com/decred/decrediton/pull/2869#issuecomment-1165400364
> Fix js warning in ToggleSwitch component

- app/components/views/GovernancePage/TreasurySpendingTab/TreasurySpendingTab.jsx
- app/components/views/GovernancePage/TreasurySpendingTab/hooks.js
- app/constants/decred.js
- test/unit/components/views/GovernancePage/TreasurySpending/TreasurySpending.spec.js
Now treasury spending page use testnet governance keys on testnet and it links to the testnet dcrd source code.
Thanks to @dreacot and @davecgh for reporting this issue on the matrix.
> [governance] use testnet PiKeys on testnet

- app/main.development.js
```
This changes from the use of GlobalShortcut.register, which registers
a global shortcut that hijacks a shortcut key for the entire system,
with a key capture just for the dex's BrowserWindow.
```
https://www.electronjs.org/docs/latest/tutorial/keyboard-shortcuts#intercepting-events-in-the-main-process
> local F5 reload

- go.mod
- go.sum
No critical updates, but keeping up with the DEX releases.
See https://github.com/decred/dcrdex/releases/tag/v0.5.3
> [dex] Bump to dcrdex v0.5.3

- package.json
- webpack/ui.prod.js
- yarn.lock
- Upgrade pi-ui
- Add [source-map-explorer](https://github.com/danvk/source-map-explorer) dev dependency.
- Add `analyze` and `analyze:gzip` scripts to analyze the bundle size.
- Change `ui.prod` `devtool` from `cheap-module-source-map` to `source-map` because the [TerserPlugin source map generation doesn't work with the first](https://webpack.js.org/plugins/terser-webpack-plugin/#note-about-source-maps).
> chore: upgrade pi-ui + add source-map-explorer + fix TerserPlugin source map generation

- app/actions/ControlActions.js
- app/actions/VSPActions.js
- app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseTickets.jsx
- app/components/views/TicketsPage/PurchaseTab/hooks.js
- app/index.js
- app/reducers/vsp.js
- app/selectors.js
- test/unit/actions/ControlActions.spec.js
Noticed that `filterUnlockableAccounts` function in `ControlActions` does not filter out the account used for ticket autobuyer, even if the auto buyer has been switched on. This diff probably fixes #3680. Add tests for the function as well.
Also addresses one of the suggestions from #3310:
"[Possible Issue] While manually buying tickets if I change tab and then go back to staking tab sometimes the values given on Purchase Tickets are resetting."
> [multi] Fix filterUnlockableAccounts 

- app/actions/DaemonActions.js
Closes #2431
Way to reproduce: 
1. start syncing blocks (SPV disabled)
2. enable SPV from settings. 
3. open a wallet
4. disable SPV from settings. It resets the app, and when the syncing restarts, the time estimation breaks:
The estimated time should look something like this:
> [launcher] Fix time estimation during block syncing

- app/actions/SettingsActions.js
- test/unit/actions/SettingsActions.spec.js
- test/unit/actions/SidebarActions.spec.js
This diff is the continuation of #3808. I've covered the settings and sidebar actions.
The unused `updateStateVoteSettingsChanged` function ditched from settings actions.
> SettingsActions, SidebarActions: automated tests

- app/actions/ControlActions.js
- app/actions/DexActions.js
- app/components/modals/ChangePassphraseModal/ChangePassphraseModal.jsx
- app/components/modals/ChangePassphraseModal/ChangePassphraseModal.module.css
- app/components/modals/ChangePassphraseModal/ChangePassphraseModalContent.jsx
- app/hooks/useSettings.js
- app/main.development.js
- app/main_dev/ipc.js
- app/main_dev/launch.js
- app/reducers/dex.js
- app/reducers/walletLoader.js
- app/wallet/dex/index.js
- modules/dex/libdexc/adapter.go
- test/unit/actions/ControlActions.spec.js
- test/unit/actions/DexActions.spec.js
- test/unit/actions/accountMocks.js
- test/unit/components/views/SettingsPage/SettingsPage.spec.js
Closes  #3820
Builds on top of  #3800
This diff introduces an additional DEX app password input on the private passphrase modal if DEX is active.
If the user provides the DEX app password, the app automatically propagates the changes to `dexc` too
> [DEX] Auto update wallet passphrase on update private passphrase

- app/actions/DaemonActions.js
- app/reducers/daemon.js
- test/mocks/fsMock.js
- test/mocks/walletPreloadShimMock.js
- test/test-utils.js
- test/unit/actions/DaemonActions.spec.js
This diff is the continuation of #3811. I've covered the daemon actions.
The unused `getDcrdLogs`, `getDecreditonLogs` and `getDcrlndLogs`  functions ditched from daemon actions.
`new Date()` replaced with `Date().now` for the easier testing.
> DaemonActions: automated tests

- app/actions/ControlActions.js
- app/helpers/addresses.js
- test/unit/actions/AccountMixerActions.spec.js
- test/unit/actions/ControlActions.spec.js
- test/unit/actions/accountMocks.js
Builds on #3819
This diff finishes off the testing of the `ControlActions` that was started in #3919.
Also ditched the unused `importPrivateKey` code and introduced `accountMocks` which contains shared mocks with  `AccountMixerActions` tests
> ControlActions: automated tests

- app/actions/TransactionActions.js
- app/actions/VSPActions.js
- app/components/shared/TxHistory/RegularTxRow.jsx
- app/components/views/TransactionPage/TransactionContent/TransactionContent.jsx
- app/components/views/TransactionPage/TransactionContent/TransactionContent.module.css
- app/reducers/grpc.js
- test/unit/actions/TransactionActions.spec.js
- test/unit/components/views/SettingsPage/SettingsPage.spec.js
- test/unit/components/views/TicketsPage/MyVSPTickets/MyVSPTicketsTab.spec.js
- test/unit/components/views/TransactionPage/TransactionPage.spec.js
- test/unit/components/views/TransactionPage/mocks.js
- test/unit/components/views/TransactionPage/mocks_decodedTransactions.js
- test/unit/components/views/TransactionPage/mocks_spenderTransactions.js
- test/unit/components/views/TransactionPage/mocks_stakeTransactions.js
- test/unit/components/views/TransactionPage/mocks_tickets.js
This diff cleans and adds detailed tests for TransactionActions, and TransactionPage.
Builds on top of https://github.com/decred/decrediton/pull/3778
Closes #3689
Also, it improves the Transaction details view:
- truncates the addresses and account names, if necessary. Before/after:
- truncates the long account names on the overview view. Before/after: 
- show the correct plural address label on the tx details view. (To address: vs. To addresses: )
- Stakebase transactions (votes) have only one (`stakebase`) non-wallet output.
- fix block display and URL on tx details view. before/after:
- show `Spending Tx` on the tx details view: 
- sometimes on the Ticket History view, the app showed the ticket as `Solo` though it is paid (or in another fee status). This diff fixes it: before/after
> TransactionAction and Txdetails improvements

- app/actions/VSPActions.js
- app/components/views/AgendaDetailsPage/hooks.js
- app/reducers/snackbar.js
- test/unit/actions/VSPActions.spec.js
- test/unit/actions/vspMocks.js
- test/unit/components/views/TicketsPage/PurchaseTab/mocks.js
Closes #3717 
By updating voting preference asynchronous, the process takes 3 times faster on mainnet (3s vs 11s) in my environment.
The error handling improved too. For example: 
Tests are also added.
> [governance] Update voting preference async

- app/actions/SettingsActions.js
- app/components/views/SettingsPage/ConnectivitySettingsTab/ProxySettings/ProxySettings.jsx
- app/components/views/SettingsPage/ConnectivitySettingsTab/ProxySettings/ProxySettings.module.css
- app/components/views/SettingsPage/ConnectivitySettingsTab/ProxySettings/hooks.js
- app/main_dev/launch.js
- app/main_dev/proxy.js
- test/unit/actions/SettingsActions.spec.js
- test/unit/components/views/SettingsPage/SettingsPage.spec.js
Before this, proxy settings determine only links/API calls.
This diff applies proxy settings to dcrd and dcrwallet too, when the proxy type is SOCKS 5. With this, users can configure dcrd/dcrwallet as a Tor client.
It changes the proxy settings view a bit too:
- After changing the proxy settings, the daemon and wallet need to restart after confirmation.
- Since the proxy type and location values are firmly related, the submit event does not trigger automatically, but by clicking on a dedicated submit button:
Tests updated also.
> [settings] Apply proxy on dcrd/dcrwallet

- go.mod
- go.sum
This updates dcrdex from v0.5.6 to v0.5.7:
- Fix the client revoking trade orders when order revocation messages for a cancel order targeting the trade are received from the server.
- Add automatic order cancellation when the server reports an order that the client does not have loaded and cannot locate.
These fixes are not particularly urgent, but may resolve issues with some clients, so I wanted to have it ready if needed.
> [dex] Bump to dcrdex v0.5.7

- app/actions/ClientActions.js
- app/actions/VSPActions.js
- app/components/views/GetStartedPage/SetupWallet/ProcessManagedTickets/ProcessManagedTickets.jsx
- app/components/views/GetStartedPage/SetupWallet/ProcessManagedTickets/index.js
- app/components/views/GetStartedPage/SetupWallet/ProcessUnmanagedTickets/ProcessUnmanagedTickets.jsx
- app/components/views/GetStartedPage/SetupWallet/ProcessUnmanagedTickets/ProcessUnmanagedTickets.module.css
- app/components/views/GetStartedPage/SetupWallet/ProcessUnmanagedTickets/hooks.js
- app/components/views/GetStartedPage/SetupWallet/ProcessUnmanagedTickets/index.js
- app/components/views/GetStartedPage/SetupWallet/hooks.js
- app/stateMachines/SetupWalletConfigMachine.js
- test/unit/actions/VSPActions.spec.js
- test/unit/components/views/GetStaredPage/SetupWallet/ProcessManagedTickets.spec.js
- test/unit/components/views/GetStaredPage/SetupWallet/ProcessUnmanagedTickets.spec.js
Closes #3843
This removes the unnecessary `gettingVSPInfo` step from the setup wallet process. The fetched vsp info is used only in the manage processed tickets part of the flow. Now it's requested only if needed.
Also, this diff cleans up the process managed and unmanaged views and adds tests for them.
> [launcher] Speed up opening the wallet

- modules/dex/libdexc/adapter.go
Some Decrediton users have changed their DEX Decred wallet to be of type "SPV" (native) in the DEX Wallets page.  This means DEX on longer uses Decrediton's dcrwallet.  While there is no point in doing this, people still do it and they will get an error similar to the following:
That above error came from `UpdateWallet` (`createWalletDexCall`), not the private password change form.  I still do not understand how to reproduce that particular error or even the circumstances when `createWalletDexCall` is used, but it lead me to the related issue with changing the wallet password.
> dex: do not set password on native dex wallet

- app/components/SideBar/MenuLinks/Links.jsx
- app/components/SideBar/MenuLinks/hooks.js
- app/components/views/HomePage/HomePage.jsx
- app/components/views/TransactionsPage/ReceiveTab/ReceivePage/ReceivePage.jsx
- app/components/views/TransactionsPage/ReceiveTab/ReceivePage/ReceivePage.module.css
Staking does not currently work for hardware wallets. Remove the screens and options that have to do with staking for now to avoid confusion. Hardware wallets also cannot currently handle stake inputs when signing. Add a warning to receiving screens not to use addresses for staking or treasury receives.
Part of #3865
> multi: Remove staking from hw wallet menus.

- app/actions/LedgerActions.js
> ledger: Enable mainnet.

- package.json
- yarn.lock
This rolls back electron from 23.3.13 to 21.2.3
Something in https://github.com/electron/electron/releases/tag/v21.3.0 is causing the DEX Window not to load anything below the top bar and the hamburger button in the top right is non-responsive.
> deps: Rollback electron since DEX window not loading

- app/actions/ControlActions.js
This commit fixes a bug in the ticket purchase flow, where wrong passphrase 
error wasnt displayed in the toast.
Fixes #3897.
> staking: display wrong passphrase error.

- app/components/views/SettingsPage/ConnectivitySettingsTab/NetworkSettings/NetworkSettings.jsx
- test/unit/components/views/SettingsPage/SettingsPage.spec.js
Save an empty array (which is default value) if the `SPV Connect` field has been cleared instead of:
```    
"spv_connect": [
""
],
```
Probably solves #3883
> [Settings] Fix SPV Connect on the Settings Page

- app/actions/TrezorActions.js
- app/main.development.js
- app/main_dev/constants.js
- app/main_dev/ipc.js
- app/main_dev/launch.js
- app/main_dev/logging.js
- app/wallet-preload-shim.js
- app/wallet-preload.js
- app/wallet/trezord/index.js
- appveyor.yml
- package.json
- test/mocks/trezordMock.js
- test/mocks/walletPreloadShimMock.js
If a user opens a trezor wallet, also start the trezor bridge that is
needed for communications.
part of #3901
> trezor: Add trezord-go to bin.

- app/main_dev/templates.js
Add the missing `View -> Load Custom Translation` menu item on macOS.
Closes #3896
> Add the missing `Load Custom Translation` menu item on macOS

- app/helpers/ledger.js
- test/unit/helpers/ledger.spec.js
I thought this was a problem with v2.0.3 but it seems to just be a bug. The raw numbers were not behaving as expected causing an out of bounds value when trying to use buff.writeUInt32LE.
The current code still cannot handle a uint64 number with full precision it seems but numbers larger than a uint32 no longer make it barf.
> ledger: Fix writeUint64LE

- app/actions/LNActions.js
- app/actions/TrezorActions.js
- app/components/views/FatalErrorPage/FatalErrorPage.jsx
- app/components/views/FatalErrorPage/hooks.js
- app/main.development.js
- app/main_dev/ipc.js
- app/main_dev/launch.js
- app/reducers/trezor.js
- app/selectors.js
- app/wallet/trezord/index.js
- test/unit/components/views/GetStaredPage/PreCreateWallet.spec.js
- test/unit/components/views/TrezorPage/TrezorPage.spec.js
> trezor: Add udev error and instructions.

- package.json
- yarn.lock
This dep appears to be unused and had some critical vulns included as well (underscore v1.6.0)
> deps: remove old react-intl-po dep

- go.mod
- go.sum
Added a [relevant fix](https://github.com/decred/dcrdex/pull/2937) for the market marker.
> libdexc: bump commit for mm fix
